-- Lokale Testumgebung: Supabase-Stubs + exportiertes Schema (Constraints nachgebaut)
create extension if not exists pgcrypto;
create schema if not exists auth;
create table if not exists auth.users(id uuid primary key default gen_random_uuid(), raw_user_meta_data jsonb default '{}');
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role anon; exception when duplicate_object then null; end $$;
create sequence if not exists user_active_defenses_id_seq;

create table public.achievement_defs(
id text not null,
name text not null,
description text not null,
reward numeric(12,2) default 0 not null,
sort_order integer default 0 not null,
primary key(id));
create table public.daily_missions(
user_id uuid not null,
mission_day date default CURRENT_DATE not null,
progress integer default 0 not null,
claimed boolean default false not null,
primary key(user_id,mission_day));
create table public.defense_items(
id text not null,
name text not null,
kind text not null,
amount integer not null,
duration_type text not null,
duration_minutes integer,
price numeric(12,2) not null,
sort_order integer not null,
primary key(id));
create table public.fights(
id bigint generated by default as identity not null,
attacker_id uuid not null,
defender_id uuid not null,
winner_id uuid not null,
attacker_power integer not null,
defender_power integer not null,
loot numeric(12,2) default 0 not null,
created_at timestamp with time zone default now() not null,
primary key(id));
create table public.gang_members(
gang_id uuid not null,
user_id uuid not null,
role text default 'member'::text not null,
joined_at timestamp with time zone default now() not null,
primary key(user_id));
create table public.gangs(
id uuid default gen_random_uuid() not null,
name text not null,
owner_id uuid not null,
balance numeric(14,2) default 0 not null,
attack_level integer default 0 not null,
defense_level integer default 0 not null,
created_at timestamp with time zone default now() not null,
primary key(id));
create table public.inventory(
user_id uuid not null,
item_id text not null,
quantity integer default 1 not null,
equipped boolean default false not null,
primary key(user_id,item_id));
create table public.messages(
id bigint generated by default as identity not null,
sender_id uuid not null,
recipient_id uuid not null,
body text not null,
created_at timestamp with time zone default now() not null,
read_at timestamp with time zone,
primary key(id));
create table public.pet_catalog(
id text not null,
name text not null,
description text not null,
price numeric(12,2) not null,
attack integer default 0 not null,
defense integer default 0 not null,
required_level integer default 1 not null,
health integer,
primary key(id));
create table public.player_reports(
id bigint generated by default as identity not null,
reporter_id uuid not null,
reported_id uuid not null,
reason text not null,
status text default 'open'::text not null,
created_at timestamp with time zone default now() not null,
primary key(id));
create table public.profile_audit(
id bigint generated by default as identity not null,
user_id uuid not null,
old_money numeric(12,2),
new_money numeric(12,2),
old_energy integer,
new_energy integer,
old_bottles integer,
new_bottles integer,
changed_at timestamp with time zone default now() not null,
primary key(id));
create table public.profiles(
id uuid not null,
username text not null,
money numeric(12,2) default 0 not null,
energy integer default 100 not null,
bottles integer default 0 not null,
xp integer default 0 not null,
level integer default 1 not null,
created_at timestamp with time zone default now() not null,
last_action_at timestamp with time zone,
bag_level integer default 1 not null,
shelter_level integer default 1 not null,
streetwise integer default 1 not null,
stamina integer default 1 not null,
energy_updated_at timestamp with time zone default now() not null,
container_level integer default 1 not null,
cash_capacity numeric(12,2) default 20 not null,
cleanliness integer default 100 not null,
area_level integer default 1 not null,
music_level integer default 0 not null,
music_collected_at timestamp with time zone default now() not null,
last_beg_at timestamp with time zone,
total_earned numeric(14,2) default 0 not null,
training_type text,
training_ends_at timestamp with time zone,
attack_skill integer default 1 not null,
defense_skill integer default 1 not null,
protection_until timestamp with time zone,
wins integer default 0 not null,
losses integer default 0 not null,
is_admin boolean default false not null,
is_banned boolean default false not null,
ban_reason text,
collection_ends_at timestamp with time zone,
collection_started_at timestamp with time zone,
collection_minutes integer,
collection_ready_at timestamp with time zone,
speech_skill integer default 1 not null,
music_skill integer default 1 not null,
social_skill integer default 1 not null,
pickpocket_skill integer default 1 not null,
last_side_action_at timestamp with time zone,
daily_claim_date date,
login_streak integer default 0 not null,
alcohol_level numeric default 0 not null,
alcohol_bonus_until timestamp with time zone,
wash_level integer default 0 not null,
bottles_lifetime_earned numeric(14,2) default 0 not null,
concentration_ends_at timestamp with time zone,
jail_until timestamp with time zone,
jail_bail numeric(12,2) default 0 not null,
alcohol_updated_at timestamp with time zone default now() not null,
insurance_active boolean default false not null,
insurance_since timestamp with time zone,
insurance_next_charge_at timestamp with time zone,
insurance_days_paid integer default 0 not null,
mat_nails integer default 0 not null,
mat_wood integer default 0 not null,
mat_shards integer default 0 not null,
mat_textile integer default 0 not null,
primary key(id));
create table public.shop_items(
id text not null,
name text not null,
description text not null,
price numeric(12,2) not null,
attack integer default 0 not null,
defense integer default 0 not null,
required_level integer default 1 not null,
category text default 'ausruestung'::text not null,
primary key(id));
create table public.side_action_log(
id bigint generated by default as identity not null,
user_id uuid not null,
action_type text not null,
success boolean not null,
money_change numeric(12,2) default 0 not null,
bottle_change integer default 0 not null,
xp_change integer default 0 not null,
created_at timestamp with time zone default now() not null,
primary key(id));
create table public.user_achievements(
user_id uuid not null,
achievement_id text not null,
unlocked_at timestamp with time zone default now() not null,
primary key(user_id,achievement_id));
create table public.user_active_defenses(
id bigint default nextval('user_active_defenses_id_seq'::regclass) not null,
user_id uuid not null,
item_id text not null,
amount integer not null,
expires_at timestamp with time zone,
consume_on_attack boolean default false not null,
created_at timestamp with time zone default now() not null,
primary key(id));
create table public.user_pets(
user_id uuid not null,
pet_id text not null,
level integer default 1 not null,
active boolean default false not null,
training_ends_at timestamp with time zone,
attack_level integer default 1 not null,
defense_level integer default 1 not null,
mitleid_level integer default 1 not null,
training_stat text,
primary key(user_id,pet_id));
