-- ENTWURF (ungetestet, nicht live): Vorlage für Ideen 38–45 aus ROADMAP.md. Vor Nutzung als nächste freie Nummer nach supabase/migrations/ kopieren, testen (test_NNNN.sh) und Nutzer fragen.
-- 0017: Runde 7 – alle 3–5 Minuten etwas zu tun
-- Mülltonne (alle 3 Min.), kurze Pfandtouren (3/5 Min.), plötzliche Chancen, Glückssträhne (Punkte-Bonus für schnelles
-- Weiterspielen), Blitzaufträge (alle 5 Min.), Flaschen-Sortierspiel, Live-Ticker „Gerade im Kiez“.

alter table public.profiles
  add column if not exists trash_at timestamptz,
  add column if not exists trash_count integer not null default 0,
  add column if not exists streak_count integer not null default 0,
  add column if not exists streak_last_at timestamptz,
  add column if not exists sort_started_at timestamptz,
  add column if not exists sort_done_at timestamptz,
  add column if not exists sort_count integer not null default 0,
  add column if not exists chance_kind text,
  add column if not exists chance_amount numeric(12,2),
  add column if not exists chance_until timestamptz,
  add column if not exists chance_last timestamptz,
  add column if not exists chance_try_at timestamptz;

-- ---------- Live-Ticker ----------
create table if not exists public.kiez_feed(
  id bigint generated by default as identity primary key,
  kind text not null, body text not null,
  created_at timestamptz not null default now());
create index if not exists kiez_feed_idx on public.kiez_feed(created_at desc);
create or replace function public.kiez_feed_add(k text, txt text)
returns void language plpgsql security definer set search_path to 'public' as $function$
begin
  insert into public.kiez_feed(kind,body) values(k,txt);
  delete from public.kiez_feed where created_at < now()-interval '3 days';
end $function$;
revoke execute on function public.kiez_feed_add(text,text) from public, anon, authenticated;

create or replace function public.kiez_feed_fight() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.winner_id=new.attacker_id then
    perform public.kiez_feed_add('kampf','👊 '||public.kiez_name(new.attacker_id)||' hat '||public.kiez_name(new.defender_id)||' verprügelt');
  else
    perform public.kiez_feed_add('kampf','🛡 '||public.kiez_name(new.defender_id)||' hat den Angriff von '||public.kiez_name(new.attacker_id)||' abgewehrt');
  end if;
  return new;
end $function$;
drop trigger if exists fights_feed on public.fights;
create trigger fights_feed after insert on public.fights for each row execute function public.kiez_feed_fight();

create or replace function public.kiez_feed_level() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.level > old.level and new.level % 5 = 0 then
    perform public.kiez_feed_add('level','⬆ '||new.username||' ist jetzt Level '||new.level);
  end if;
  return new;
end $function$;
drop trigger if exists profiles_feed_level on public.profiles;
create trigger profiles_feed_level after update of level on public.profiles for each row execute function public.kiez_feed_level();

create or replace function public.kiez_feed_district() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.gang_id is not null then
    perform public.kiez_feed_add('revier','🏴 '||coalesce((select name from public.gangs where id=new.gang_id),'Eine Bande')||' regiert jetzt '||(select name from public.districts where id=new.district_id));
  end if;
  return new;
end $function$;
drop trigger if exists district_owners_feed on public.district_owners;
create trigger district_owners_feed after insert on public.district_owners for each row execute function public.kiez_feed_district();

create or replace function public.kiez_feed_dice() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.status='done' and old.status='open' then
    perform public.kiez_feed_add('zocken','🎲 '||public.kiez_name(new.winner_id)||' gewinnt ein Würfelduell um '||to_char(new.stake*2,'FM999990.00')||' €');
  end if;
  return new;
end $function$;
drop trigger if exists dice_feed on public.dice_challenges;
create trigger dice_feed after update on public.dice_challenges for each row execute function public.kiez_feed_dice();

create or replace function public.kiez_feed_gang() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.kiez_feed_add('bande','🏴 Neue Bande im Kiez: '||new.name);
  return new;
end $function$;
drop trigger if exists gangs_feed on public.gangs;
create trigger gangs_feed after insert on public.gangs for each row execute function public.kiez_feed_gang();

-- ---------- Glückssträhne: wer innerhalb von 5 Minuten wieder Punkte holt, bekommt +5 % je Stufe (max. +50 %) ----------
create or replace function public.kiez_streak_xp() returns trigger language plpgsql as $function$
begin
  -- nur eigene Spieleraktionen zählen (keine Auszahlungen an andere, keine Admin-/Testwerte)
  if auth.uid() is null or auth.uid() <> new.id or new.xp <= old.xp then return new; end if;
  if old.streak_last_at is not null and old.streak_last_at > now()-interval '5 minutes' then
    new.streak_count := least(11, old.streak_count+1);
  else
    new.streak_count := 1;
  end if;
  new.streak_last_at := now();
  new.xp := old.xp + round((new.xp-old.xp) * (1 + (new.streak_count-1)*0.05))::int;
  return new;
end $function$;
drop trigger if exists kiez_streak_xp on public.profiles;
create trigger kiez_streak_xp before update of xp on public.profiles for each row execute function public.kiez_streak_xp();

-- ---------- Mülltonne: alle 3 Minuten durchwühlen ----------
create or replace function public.dig_trash()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r numeric := random(); k text; txt text; n int := 0; amt numeric(12,2) := 0; pl text; pl_name text; wait int;
begin
  p := public.kiez_actor(); perform public.kiez_assert_free(p);
  if p.trash_at is not null and p.trash_at > now()-interval '3 minutes' then
    wait := ceil(extract(epoch from (p.trash_at+interval '3 minutes'-now())))::int;
    raise exception 'Die Tonne ist noch leer – in % Sek. ist wieder was drin', wait;
  end if;
  if r < 0.08 then
    k := 'ratte'; txt := 'Autsch! Eine Ratte hat dich gebissen: −5 Energie, −5 % Sauberkeit.';
    update public.profiles set energy=greatest(0,energy-5), cleanliness=greatest(0,cleanliness-5) where id=p.id;
  elsif r < 0.12 then
    k := 'plunder'; pl := public.kiez_random_plunder(); perform public.kiez_give_plunder(p.id, pl);
    select name into pl_name from public.plunder_catalog where id=pl;
    txt := 'Ganz unten in der Tonne: Plunder „'||pl_name||'“!';
    perform public.kiez_feed_add('fund','🗑 '||p.username||' hat „'||pl_name||'“ aus der Mülltonne gezogen');
    update public.profiles set xp=xp+2 where id=p.id;
  elsif r < 0.27 then
    k := 'kronkorken'; n := 1 + (random()<0.3)::int; txt := n||' Kronkorken gefunden.';
    update public.profiles set bottlecaps=bottlecaps+n, xp=xp+1 where id=p.id;
  elsif r < 0.47 then
    k := 'geld'; amt := round((0.05 + random()*0.45 + p.level*0.01)::numeric,2);
    perform public.kiez_pay(p.id, amt); txt := to_char(amt,'FM999990.00')||' € Kleingeld zwischen dem Müll.';
    update public.profiles set xp=xp+1, total_earned=total_earned+amt where id=p.id;
  else
    k := 'flaschen'; n := 2 + floor(random()*5)::int + floor(p.streetwise/3.0)::int; txt := n||' Pfandflaschen aus der Tonne gefischt.';
    update public.profiles set bottles=bottles+n, xp=xp+1 where id=p.id;
    insert into public.daily_missions(user_id,progress) values(p.id,n)
    on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  end if;
  update public.profiles set trash_at=now(), trash_count=trash_count+1 where id=p.id returning * into p;
  return jsonb_build_object('kind',k,'text',txt,'amount',greatest(n,amt),'plunder',pl,'profile',to_jsonb(p));
end $function$;

-- ---------- Kurze Pfandtouren (3 und 5 Minuten) ----------
create or replace function public.start_collection(duration_minutes integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  if p.cleanliness<20 then raise exception 'Du bist zu dreckig für die Tour – erst waschen (mindestens 20 Prozent Sauberkeit nötig)'; end if;
  if duration_minutes not in (3,5,10,30,60,240,480) then raise exception 'Ungültige Sammelzeit'; end if;
  if p.collection_ends_at is not null and p.collection_ends_at>now() then raise exception 'Der Einkaufswagen ist noch unterwegs'; end if;
  if p.collection_ends_at is not null then raise exception 'Erst den Einkaufswagen ausladen'; end if;
  if p.collection_ready_at is not null and p.collection_ready_at>now() then raise exception 'Der Einkaufswagen braucht noch Pause'; end if;
  update public.profiles set collection_started_at=now(),collection_ends_at=now()+make_interval(mins=>duration_minutes),collection_minutes=duration_minutes
  where id=p.id returning * into p;
  return to_jsonb(p);
end $function$;

-- Kurze Touren sind pro Minute genau so ergiebig wie die 10-Minuten-Tour (Flaschen, Punkte, Material, Plunder)
create or replace function public.finish_collection()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; found_count int; factor numeric; efficiency numeric; alcohol_factor numeric := 1.0;
  weather jsonb := public.kiez_weather(current_date); weather_factor numeric; plunder_factor numeric := 1.0;
  gained_xp int; found_nails int; found_wood int; found_shards int; found_textile int; caps int; pl text; pl_name text;
  short numeric;
begin
  select * into p from public.profiles where id=auth.uid() for update;
  if p.id is null or p.is_banned then raise exception 'Zugriff gesperrt'; end if;
  if p.collection_ends_at is null then raise exception 'Keine Pfandtour aktiv'; end if;
  if p.collection_ends_at>now() then raise exception 'Der Einkaufswagen ist noch unterwegs'; end if;
  short := least(1.0, p.collection_minutes/10.0);   -- 3 Min. = 0,3 · 5 Min. = 0,5 · ab 10 Min. = 1
  factor := (array[1.0,1.25,1.55,1.95,2.5])[least(p.area_level,5)];
  efficiency := case p.collection_minutes when 3 then 1.0 when 5 then 1.0 when 10 then 1.0 when 30 then 0.88 when 60 then 0.78 when 240 then 0.62 when 480 then 0.52 else 0.50 end;
  if p.alcohol_level >= 5 then alcohol_factor := 0.6; else alcohol_factor := 1 + least(p.alcohol_level,4.99)*0.15; end if;
  weather_factor := 1 + ((weather->>'bonus')::numeric + public.kiez_event_bonus('bottles'))/100;
  select 1 + bottle_bonus/100.0 into plunder_factor from public.plunder_catalog where id=p.equipped_plunder;
  plunder_factor := coalesce(plunder_factor,1.0);
  found_count := greatest(1,floor((p.collection_minutes/10.0)*(5+p.streetwise*0.8+(p.bag_level-1)*2)*factor*efficiency*alcohol_factor
                  *weather_factor*plunder_factor*(0.85+random()*0.30))::int);
  if p.collection_minutes < 10 then
    gained_xp := round(greatest(1, p.collection_minutes*0.4) * (1 + public.kiez_event_bonus('xp')/100.0))::int;
  else
    gained_xp := round(greatest(5,floor(p.collection_minutes/10.0)::int*2) * (1 + public.kiez_event_bonus('xp')/100.0))::int;
  end if;
  found_nails := (random()<least(0.35,0.10+p.collection_minutes/480.0*0.20)*short)::int;
  found_wood := (random()<least(0.32,0.09+p.collection_minutes/480.0*0.18)*short)::int;
  found_shards := (random()<least(0.10,0.02+p.collection_minutes/480.0*0.06)*short)::int;
  found_textile := (random()<least(0.28,0.08+p.collection_minutes/480.0*0.16)*short)::int;
  caps := floor(random()*(1+p.collection_minutes/60.0)*short)::int;
  if random() < least(0.45, 0.04+p.collection_minutes/480.0*0.36)*short then
    pl := public.kiez_random_plunder();
    perform public.kiez_give_plunder(p.id, pl);
    select name into pl_name from public.plunder_catalog where id=pl;
  end if;
  update public.profiles set bottles=bottles+found_count, mat_nails=mat_nails+found_nails, mat_wood=mat_wood+found_wood,
    mat_shards=mat_shards+found_shards, mat_textile=mat_textile+found_textile, bottlecaps=bottlecaps+caps,
    cleanliness=greatest(0,cleanliness-least(80,p.collection_minutes/10)), xp=xp+gained_xp,
    collection_started_at=null, collection_ends_at=null, collection_minutes=null, collection_ready_at=now()+interval '30 seconds'
  where id=p.id returning * into p;
  insert into public.daily_missions(user_id,progress) values(p.id,found_count)
  on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  return jsonb_build_object('found',found_count,'xp',gained_xp,'alcohol_bonus',alcohol_factor,'weather',weather,
    'nails',found_nails,'wood',found_wood,'shards',found_shards,'textile',found_textile,'bottlecaps',caps,
    'plunder',pl,'plunder_name',pl_name,'profile',to_jsonb(p));
end $function$;

-- ---------- Plötzliche Chancen (nur wer gerade auf der Seite ist, 20 Sekunden Zeit) ----------
create or replace function public.spawn_chance()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r numeric; k text; amt numeric(12,2); txt text;
begin
  p := public.kiez_actor();
  if p.chance_until is not null and p.chance_until > now() then
    return jsonb_build_object('kind',p.chance_kind,'amount',p.chance_amount,'until',p.chance_until,'text',null);
  end if;
  -- höchstens alle 90 Sek. würfeln, frühestens 3 Min. nach der letzten Chance
  if (p.chance_try_at is not null and p.chance_try_at > now()-interval '90 seconds')
     or (p.chance_last is not null and p.chance_last > now()-interval '3 minutes') then return null; end if;
  update public.profiles set chance_try_at=now() where id=p.id;
  if random() >= 0.45 then return null; end if;
  r := random();
  if r < 0.45 then k := 'tourist'; amt := round((0.40 + random()*1.2 + p.level*0.03)::numeric,2);
  elsif r < 0.80 then k := 'kiste'; amt := 8 + floor(random()*12)::int + p.level/5;
  elsif r < 0.97 then k := 'kronkorken'; amt := 2 + floor(random()*3)::int;
  else k := 'plunder'; amt := 1; end if;
  update public.profiles set chance_kind=k, chance_amount=amt, chance_until=now()+interval '20 seconds', chance_last=now() where id=p.id;
  return jsonb_build_object('kind',k,'amount',amt,'until',now()+interval '20 seconds');
end $function$;

create or replace function public.claim_chance()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; txt text; pl text; nm text;
begin
  p := public.kiez_actor();
  if p.chance_until is null or p.chance_until < now() then
    update public.profiles set chance_kind=null, chance_amount=null, chance_until=null where id=p.id;
    raise exception 'Zu spät – jemand anderes war schneller';
  end if;
  if p.chance_kind='tourist' then perform public.kiez_pay(p.id,p.chance_amount); txt := 'Eingesackt: '||to_char(p.chance_amount,'FM999990.00')||' €!';
    update public.profiles set total_earned=total_earned+p.chance_amount where id=p.id;
  elsif p.chance_kind='kiste' then
    update public.profiles set bottles=bottles+p.chance_amount::int where id=p.id; txt := p.chance_amount::int||' Pfandflaschen geschnappt!';
    insert into public.daily_missions(user_id,progress) values(p.id,p.chance_amount::int)
    on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  elsif p.chance_kind='kronkorken' then update public.profiles set bottlecaps=bottlecaps+p.chance_amount::int where id=p.id; txt := p.chance_amount::int||' Kronkorken aufgesammelt!';
  else pl := public.kiez_random_plunder(); perform public.kiez_give_plunder(p.id,pl); select name into nm from public.plunder_catalog where id=pl; txt := 'Plunder „'||nm||'“ abgestaubt!';
  end if;
  update public.profiles set chance_kind=null, chance_amount=null, chance_until=null, xp=xp+2 where id=p.id returning * into p;
  return jsonb_build_object('text',txt,'profile',to_jsonb(p));
end $function$;

-- ---------- Blitzaufträge: alle 5 Minuten ein neuer Mini-Auftrag ----------
create table if not exists public.blitz_tasks(
  user_id uuid primary key references public.profiles(id) on delete cascade,
  kind text not null, label text not null, target numeric not null, base numeric not null,
  expires_at timestamptz not null, claimed boolean not null default false,
  reward_money numeric(12,2) not null, reward_xp integer not null, reward_caps integer not null default 0);

create or replace function public.kiez_blitz_value(p public.profiles, k text) returns numeric language sql stable security definer set search_path to 'public' as $$
  select case k when 'xp' then p.xp::numeric when 'money' then p.total_earned when 'trash' then p.trash_count::numeric
    when 'sort' then p.sort_count::numeric when 'bottles' then (public.kiez_stats(p)->>'bottles_total')::numeric else 0 end
$$;
revoke execute on function public.kiez_blitz_value(public.profiles,text) from public, anon, authenticated;

create or replace function public.blitz_status()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; t public.blitz_tasks; k text; lbl text; tg numeric; val numeric;
begin
  p := public.kiez_actor();
  select * into t from public.blitz_tasks where user_id=p.id for update;
  if t.user_id is null or t.expires_at < now() then
    k := (array['xp','bottles','money','trash','sort'])[1+floor(random()*5)::int];
    case k
      when 'xp' then tg := 6 + p.level/4; lbl := 'Hol '||(6 + p.level/4)||' Punkte';
      when 'bottles' then tg := 12 + p.level; lbl := 'Sammle '||(12 + p.level)||' Pfandflaschen';
      when 'money' then tg := round((0.5 + p.level*0.05)::numeric,2); lbl := 'Verdiene '||to_char(round((0.5 + p.level*0.05)::numeric,2),'FM999990.00')||' €';
      when 'trash' then tg := 1; lbl := 'Durchwühl die Mülltonne';
      else tg := 1; lbl := 'Spiel eine Runde Flaschen sortieren';
    end case;
    insert into public.blitz_tasks(user_id,kind,label,target,base,expires_at,claimed,reward_money,reward_xp,reward_caps)
    values(p.id,k,lbl,tg,public.kiez_blitz_value(p,k),now()+interval '5 minutes',false,
           round((0.20 + p.level*0.03)::numeric,2), 4 + p.level/10, (random()<0.25)::int)
    on conflict (user_id) do update set kind=excluded.kind,label=excluded.label,target=excluded.target,base=excluded.base,
      expires_at=excluded.expires_at,claimed=false,reward_money=excluded.reward_money,reward_xp=excluded.reward_xp,reward_caps=excluded.reward_caps
    returning * into t;
  end if;
  val := public.kiez_blitz_value(p,t.kind) - t.base;
  return jsonb_build_object('label',t.label,'kind',t.kind,'target',t.target,'progress',least(val,t.target),'done',val>=t.target,
    'claimed',t.claimed,'expires_at',t.expires_at,'reward_money',t.reward_money,'reward_xp',t.reward_xp,'reward_caps',t.reward_caps);
end $function$;

create or replace function public.claim_blitz()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; t public.blitz_tasks;
begin
  p := public.kiez_actor();
  select * into t from public.blitz_tasks where user_id=p.id for update;
  if t.user_id is null or t.expires_at < now() then raise exception 'Der Blitzauftrag ist abgelaufen – gleich kommt ein neuer'; end if;
  if t.claimed then raise exception 'Schon abgeholt – der nächste Blitzauftrag kommt in ein paar Minuten'; end if;
  if public.kiez_blitz_value(p,t.kind) - t.base < t.target then raise exception 'Noch nicht geschafft: %', t.label; end if;
  update public.blitz_tasks set claimed=true where user_id=p.id;
  perform public.kiez_pay(p.id,t.reward_money);
  update public.profiles set xp=xp+t.reward_xp, bottlecaps=bottlecaps+t.reward_caps where id=p.id returning * into p;
  return jsonb_build_object('money',t.reward_money,'xp',t.reward_xp,'caps',t.reward_caps,'profile',to_jsonb(p));
end $function$;

-- ---------- Flaschen sortieren (30-Sekunden-Spiel, alle 5 Minuten) ----------
create or replace function public.start_sort_game()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; wait int;
begin
  p := public.kiez_actor(); perform public.kiez_assert_free(p);
  if p.sort_done_at is not null and p.sort_done_at > now()-interval '5 minutes' then
    wait := ceil(extract(epoch from (p.sort_done_at+interval '5 minutes'-now())))::int;
    raise exception 'Der Sortierhof hat Pause – wieder in % Sek.', wait;
  end if;
  update public.profiles set sort_started_at=now() where id=p.id;
  return jsonb_build_object('started',true);
end $function$;

create or replace function public.finish_sort_game(score integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; secs numeric; n int; gx int;
begin
  p := public.kiez_actor();
  if p.sort_started_at is null then raise exception 'Erst ein Spiel starten'; end if;
  secs := extract(epoch from (now()-p.sort_started_at));
  if secs < 25 then raise exception 'Das ging zu schnell'; end if;
  if secs > 180 then update public.profiles set sort_started_at=null where id=p.id; raise exception 'Zu lange gebraucht – das Spiel ist abgelaufen'; end if;
  n := greatest(0, least(coalesce(score,0), 45));
  gx := 1 + n/8;
  update public.profiles set bottles=bottles+n, xp=xp+gx, sort_started_at=null, sort_done_at=now(), sort_count=sort_count+1
  where id=p.id returning * into p;
  if n>0 then
    insert into public.daily_missions(user_id,progress) values(p.id,n)
    on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  end if;
  return jsonb_build_object('bottles',n,'xp',gx,'profile',to_jsonb(p));
end $function$;

-- ---------- Leserechte ----------
alter table public.kiez_feed enable row level security;
alter table public.blitz_tasks enable row level security;
drop policy if exists "feed public" on public.kiez_feed;
create policy "feed public" on public.kiez_feed for select using (auth.uid() is not null);
drop policy if exists "own blitz" on public.blitz_tasks;
create policy "own blitz" on public.blitz_tasks for select using (user_id = auth.uid());
grant select on public.kiez_feed, public.blitz_tasks to authenticated;
revoke insert, update, delete, truncate on public.kiez_feed, public.blitz_tasks from anon, authenticated;
