# Runde 2: alte Sprite-Bilder im ganzen Spiel durch Fotos ersetzen (gleicher Stil wie erzeugen.py)
# (datei, art, motiv)  art: o = Gegenstand 512, q = Szene quadratisch 512, s = Szene 800x500, h = 1600x700
BILDER2 = [
 # Seitenköpfe (.section-scene)
 ("szene-pfand", "h", "a homeless man pushing a shopping cart full of empty bottles along a street"),
 ("szene-schnorren", "h", "a homeless person sitting on cardboard begging with a paper cup in a busy pedestrian street, passers-by walking past"),
 ("szene-stadt", "h", "a wide view of a shabby city square with a kiosk, bus stop and pigeons"),
 ("szene-unterkunft", "h", "a sleeping place of a homeless person under a railway bridge with mattress, blankets and cardboard"),
 ("szene-training", "h", "a shabby basement room with old books, a punching bag made of a sleeping bag and a blackboard"),
 ("szene-post", "h", "a wall of old rusty letterboxes in a run-down apartment house entrance"),
 ("szene-bande", "h", "a backyard behind a fence with old sofas, a fire barrel and beer crates, a gang meeting place"),
 ("szene-auftrag", "h", "a notice board with torn paper notes on a lamp post at a square"),
 ("szene-tiere", "h", "stray dogs and pigeons next to a homeless camp under a railway arch"),
 ("szene-erfolge", "h", "old medals and trophies on a flea market table on the street"),
 ("szene-pruegelei", "h", "a backyard fighting spot with a ring drawn in chalk on the ground, beer crates as seats"),
 ("szene-laden", "h", "a flea market stall on the street selling used clothes, tools and junk"),
 ("szene-rangliste", "h", "a long street with many homeless camps and shopping carts lined up"),
 ("szene-karriere", "h", "a worn path on a wet sidewalk leading from a park bench to a small hut"),
 # Stadtplan
 ("stadt-zubehoer", "s", "a small shabby second-hand shop with used gear in the window"),
 ("stadt-supermarkt", "s", "the entrance of a cheap discount supermarket with shopping carts outside"),
 ("stadt-tierhandlung", "s", "a small run-down pet shop front with cages in the window"),
 ("stadt-waffenladen", "s", "a dodgy hardware shop front with tools and baseball bats in the window"),
 ("stadt-apotheke", "s", "a small pharmacy front with a green cross sign"),
 ("stadt-waschhaus", "s", "a shabby laundromat with washing machines seen through the window"),
 ("stadt-schnorrplaetze", "s", "a busy pedestrian street with a homeless person begging on the side"),
 ("stadt-musikladen", "s", "a small second-hand music shop front with old guitars in the window"),
 ("stadt-eigenheime", "s", "a row of makeshift huts and tents made of tarp and wood on wasteland"),
 ("stadt-gluecksspiel", "s", "the entrance of a shabby betting shop and casino arcade with blinking lights"),
 # Apotheke, Ausbau-Stufen (equipment-sprite data-pos 0-7)
 ("apo-magenpumpe", "o", "an old medical stomach pump with rubber tube and glass bottle"),
 ("apo-versicherung", "o", "a worn health insurance card next to a small first aid kit"),
 ("ausbau-0", "o", "a plastic bag full of empty deposit bottles"),
 ("ausbau-1", "q", "a park bench with a sleeping bag and blanket on it"),
 ("ausbau-2", "o", "a metal cup with coins next to a small cash box"),
 ("ausbau-3", "o", "a shopping cart packed with bags and belongings"),
 ("ausbau-4", "o", "a big backpack stuffed with empty bottles"),
 ("ausbau-5", "q", "a small tent with a tarp in a corner under a bridge"),
 ("ausbau-6", "o", "a black metal cash box with banknotes"),
 ("ausbau-7", "o", "a shopping cart with a small motor and wheels attached, homemade vehicle"),
 # Laden: Kleidung, Zubehör
 ("laden-jacke", "o", "a moth-eaten old jacket with holes"),
 ("laden-schirm-halb", "o", "half of a broken umbrella"),
 ("laden-wagen", "o", "a tuned shopping cart with big wheels and a headlight, homemade"),
 ("laden-warnweste", "o", "a faded dirty yellow high visibility vest"),
 ("laden-kartonruestung", "o", "a body armor made of layers of cardboard and tape"),
 ("laden-bauhelm", "o", "a scratched yellow construction helmet"),
 ("laden-wintermantel", "o", "a heavy old military winter coat"),
 ("laden-mofamotor", "o", "an old moped engine with a chain"),
 ("laden-gluecksflasche", "o", "a strange old glass bottle with a four-leaf clover inside"),
 ("laden-kettenhandschuhe", "o", "a pair of chain mail gloves"),
 ("laden-trillerpfeife", "o", "a metal whistle on a cord"),
 ("laden-klappspaten", "o", "a folding army shovel"),
 ("laden-taschenlampe", "o", "a sturdy black flashlight switched on"),
 ("laden-rucksack", "o", "a large worn survival backpack"),
 ("laden-funkgeraet", "o", "a black walkie-talkie radio"),
 ("laden-solarpanel", "o", "a small foldable solar panel with a power bank"),
 ("laden-handkarre", "o", "a handcart reinforced with metal sheets"),
 ("laden-geldversteck", "o", "a hidden money stash in an old tin can with rolled euro banknotes"),
 # Laden: Waffen
 ("waffe-zahnstocher", "o", "a crooked bundle of toothpicks tied with string"),
 ("waffe-limoflasche", "o", "a broken glass soda bottle with sharp edges"),
 ("waffe-wasserbomben", "o", "a few colorful water balloons"),
 ("waffe-kettenschloss", "o", "a heavy bicycle chain lock"),
 ("waffe-schlagring", "o", "a brass knuckle duster"),
 ("waffe-schwert", "o", "an old rusty sword"),
 ("waffe-silvesterknaller", "o", "red firecrackers"),
 ("waffe-spraydose", "o", "a used spray paint can without label"),
 ("waffe-gummiknueppel", "o", "a black rubber baton"),
 ("waffe-heizungsrohr", "o", "a rusty piece of heating pipe"),
 ("waffe-hammer", "o", "an old hammer"),
 ("waffe-pfefferspray", "o", "a small pepper spray can without label"),
 ("waffe-elektroschocker", "o", "a black stun gun"),
 ("waffe-feuerloescher", "o", "an old red fire extinguisher"),
 ("waffe-gullideckel", "o", "a round cast iron manhole cover lying loose"),
 ("waffe-nagelkeule", "o", "a wooden club with nails sticking out"),
 # Supermarkt / Essen
 ("essen-dosenbier", "o", "a dented beer can without label"),
 ("essen-kartonwein", "o", "a cheap carton of red wine"),
 ("essen-kurzer", "o", "a small shot glass of clear schnapps"),
 ("essen-wodka", "o", "a cheap bottle of vodka without label"),
 ("essen-feuerwasser", "o", "a bottle of strong brown liquor without label"),
 ("essen-broetchen", "o", "an old hard bread roll"),
 ("essen-currywurst", "o", "a currywurst with fries on a paper plate"),
 ("essen-doener", "o", "a doner kebab in flatbread wrapped in paper"),
 ("essen-eintopf", "o", "a tin bowl of hot stew with a spoon"),
 # Verteidigung (die ersten 10)
 ("vert-sand", "o", "a hand full of sand"),
 ("vert-bananen", "o", "banana peels scattered on the ground"),
 ("vert-salz", "o", "a hand full of coarse salt"),
 ("vert-wegweiser", "q", "a wooden signpost with blank arrows pointing in different directions"),
 ("vert-juckpulver", "o", "a small paper bag of itching powder"),
 ("vert-totstellen", "q", "a man lying on the ground playing dead next to his shopping cart"),
 ("vert-tarnen", "q", "a man hiding under a pile of cardboard and leaves"),
 ("vert-katzen", "q", "angry hissing stray cats in a backyard"),
 ("vert-spiegel", "o", "an old hand mirror reflecting bright light"),
 ("vert-giftbier", "o", "a beer bottle with a skull drawn on it"),
 # Begleiter
 ("tier-kakerlake", "o", "a cockroach"),
 ("tier-goldfisch", "o", "a goldfish in a small dirty glass jar"),
 ("tier-maus", "o", "a small grey mouse"),
 ("tier-hamster", "o", "a hamster in a cardboard box"),
 ("tier-wellensittich", "o", "a budgie sitting on a shopping cart handle"),
 ("tier-taube", "o", "a street pigeon"),
 ("tier-ratte", "o", "a brown rat"),
 ("tier-hase", "o", "a rabbit sitting on a blanket"),
 ("tier-frettchen", "o", "a ferret"),
 ("tier-katze", "o", "a scruffy stray cat"),
 ("tier-falke", "q", "a falcon sitting on the glove of a homeless man"),
 ("tier-schlange", "o", "a snake coiled on a blanket"),
 ("tier-ziege", "q", "a goat on a leash on a city sidewalk"),
 ("tier-pudel", "q", "a scruffy poodle on a leash on a city sidewalk"),
 ("tier-dressierte-maus", "o", "a white mouse standing on its hind legs on a hand"),
 ("tier-adler", "q", "an eagle sitting on a lamp post in the city"),
 ("tier-schaeferhund", "q", "a german shepherd dog lying next to the sleeping bag of a homeless person"),
 ("tier-pitbull", "q", "a pitbull with a worn collar on a sidewalk"),
 ("tier-cocker", "q", "a cocker spaniel sitting on a blanket on the sidewalk"),
 ("tier-chihuahua", "o", "a chihuahua wearing a small knitted sweater"),
 ("tier-pferd", "q", "a horse standing on a city street next to parked cars"),
 ("tier-giraffe", "q", "a giraffe standing in a run-down backyard behind a fence"),
 ("tier-krokodil", "q", "a small crocodile lying in a puddle on a city sidewalk"),
 ("tier-tiger", "q", "a tiger walking through a run-down city street"),
 ("tier-affe", "q", "a small monkey sitting on a shopping cart"),
 ("tier-nashorn", "q", "a rhino standing on a city street"),
 ("plunder-taubenpfeife", "o", "a small tin whistle next to a grey pigeon feather"),
 # Unterkünfte (Park = klein-park aus Runde 1)
 ("heim-buergersteig", "q", "a sleeping bag on a bare sidewalk against a house wall"),
 ("heim-parkbank", "q", "a park bench with a sleeping bag and a plastic bag"),
 ("heim-pennerbox", "q", "a large cardboard box shelter with a blanket inside"),
 ("heim-brunnen", "q", "a sleeping spot next to an old city fountain"),
 ("heim-bruecke", "q", "a sleeping camp under a concrete bridge"),
 ("heim-katakomben", "q", "an old brick cellar vault with a mattress and candles"),
 ("heim-elbstrand", "q", "a small camp with a tarp on a river beach"),
 ("heim-baumhaus", "q", "a shabby treehouse made of old boards in a park"),
 ("heim-zelt", "q", "an old dome tent on a meadow at the city edge"),
 ("heim-wolfsrudel", "q", "a homeless man sleeping between several stray dogs on blankets"),
 ("heim-wohnwagen", "q", "an old rusty caravan parked on wasteland"),
 ("heim-boot", "q", "an old small boat on the river bank used as a shelter"),
 ("heim-grabkammer", "q", "an old stone crypt entrance in a cemetery"),
 ("heim-tiefgarage", "q", "a sleeping place in the corner of an underground car park"),
 ("heim-kakaofabrik", "q", "an abandoned factory hall with a camp inside"),
 ("heim-kran", "q", "a construction crane cabin high above the city"),
 ("heim-leuchtturm", "q", "an old small lighthouse at a harbor"),
 ("heim-kirche", "q", "an old abandoned church with boarded windows"),
 ("heim-burg", "q", "a small castle ruin on a hill"),
 # Schnorrplätze, Körperpflege
 ("schnorr-garten", "q", "a homeless person begging on a path in a big city park"),
 ("schnorr-bahnhof", "q", "a homeless person begging in front of a main train station"),
 ("schnorr-fussgaengerzone", "q", "a homeless person begging in a busy pedestrian zone"),
 ("schnorr-jahrmarkt", "q", "a homeless person begging at a fairground with rides"),
 ("schnorr-oper", "q", "a homeless person begging on the steps in front of an opera house"),
 ("pflege-katzenwaesche", "o", "a plastic bowl of water with a washcloth"),
 ("pflege-schwamm", "o", "a sponge and a bar of soap"),
 ("pflege-waschanlage", "q", "a public washroom with old sinks"),
 # Musik (Grashalmflöte = klein-grashalm aus Runde 1)
 ("musik-instrument", "o", "a collection of old music instruments in a shopping cart"),
 ("musik-flaschenfloete", "o", "several empty glass bottles filled with different amounts of water"),
 ("musik-glocke", "o", "an old brass hand bell"),
 ("musik-trommel", "o", "a drum made of a plastic bucket with sticks"),
 ("musik-akkordeon", "o", "an old accordion"),
 ("musik-radio", "o", "an old portable radio"),
 ("musik-gitarre", "o", "an old acoustic guitar with a crack"),
 ("musik-saxophon", "o", "an old brass saxophone"),
 ("musik-chor", "q", "a small group of homeless people singing together on the street"),
 ("musik-kasse", "o", "an open guitar case with coins in it"),
 # Pfand, Training, Verbrechen
 ("pfand-uebersicht", "o", "a pile of empty deposit bottles and cans next to a shopping cart"),
 ("pfand-kurs", "o", "a handwritten price list for bottles taped to a crate"),
 ("training-konzentrieren", "q", "a homeless man meditating cross-legged on a blanket"),
 ("training-parallel", "o", "two worn books and a notebook side by side"),
 ("training-anforderungen", "o", "a stack of books getting higher and higher"),
 ("skill-angriff", "q", "a homeless man with taped fists in a boxing stance in a backyard"),
 ("skill-verteidigung", "o", "a homemade armor vest made of cardboard and tape"),
 ("skill-geschick", "q", "a homeless man sorting bottles quickly into a crate"),
 ("skill-ausdauer", "q", "worn out sneakers walking through a puddle"),
 ("skill-sprechen", "q", "a homeless man talking loudly into a megaphone on the street"),
 ("skill-musik", "o", "an old taped guitar leaning against a wall"),
 ("skill-sozial", "q", "two homeless men shaking hands next to a fire barrel"),
 ("skill-taschentricks", "q", "a gloved hand pulling a wallet out of a coat pocket"),
 ("verbrechen-handtasche", "q", "a hooded man running away with a handbag"),
 ("verbrechen-laden", "q", "a hand hiding a bottle under a jacket in a supermarket aisle"),
 ("verbrechen-auto", "q", "a smashed car side window"),
 ("verbrechen-einbruch", "q", "a broken door lock with a crowbar"),
 ("verbrechen-tankstelle", "q", "a small gas station shop"),
 ("verbrechen-bank", "q", "a bag of money and a ski mask on the ground"),
 ("verbrechen-kaugummi", "o", "a broken red gumball machine with gumballs spilling out"),
 # Kampf, Post, Aktionen, Übersicht
 ("kampf-gegner", "q", "a scruffy homeless man with taped fists ready to fight in a backyard"),
 ("kampf-staerke", "o", "taped fists and a broken bottle on the ground"),
 ("kampf-verteidigung", "o", "a trash can lid used as a shield next to a cardboard armor"),
 ("post-schreiben", "o", "a pencil and a crumpled letter"),
 ("post-fach", "o", "an old rusty letterbox full of letters"),
 ("mission-heute", "q", "a notice board with torn paper notes"),
 ("mission-serie", "o", "a calendar page with days crossed out"),
 ("rubbellose", "o", "a few scratched lottery scratch cards and a coin"),
 ("uebersicht-aufstieg", "q", "a steep stone staircase in the city"),
]
