-- 0004: Etappe 5 – Banden komplett: Ränge & Rechte, Einladungen/Bewerbungen, offene Banden, Kassen-/Ereignisprotokoll,
-- Bandenchat, Bandenprofil, Chefwechsel, Rauswurf, Bandenkriege (24 Std.) und Banden-Highscore

alter table public.gangs
  add column if not exists description text not null default '',
  add column if not exists is_open boolean not null default false,
  add column if not exists war_wins integer not null default 0,
  add column if not exists war_losses integer not null default 0;

-- Rollen: owner (Chef), co (Vize), officer (Offizier), member
update public.gang_members set role='member' where role not in ('owner','co','officer','member');
alter table public.gang_members drop constraint if exists gang_members_role_check;
alter table public.gang_members add constraint gang_members_role_check check (role in ('owner','co','officer','member'));

create table if not exists public.gang_requests(
  gang_id uuid not null references public.gangs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('invite','apply')),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(gang_id, user_id));
alter table public.gang_requests enable row level security;
drop policy if exists "gang requests visible" on public.gang_requests;
create policy "gang requests visible" on public.gang_requests for select using (
  user_id = auth.uid() or exists(select 1 from public.gang_members m where m.gang_id=gang_requests.gang_id and m.user_id=auth.uid()));

create table if not exists public.gang_log(
  id bigint generated by default as identity primary key,
  gang_id uuid not null references public.gangs(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  kind text not null,
  amount numeric(14,2) not null default 0,
  info text not null default '',
  created_at timestamptz not null default now());
create index if not exists gang_log_idx on public.gang_log(gang_id, created_at desc);
alter table public.gang_log enable row level security;
drop policy if exists "gang log members" on public.gang_log;
create policy "gang log members" on public.gang_log for select using (
  exists(select 1 from public.gang_members m where m.gang_id=gang_log.gang_id and m.user_id=auth.uid()));

create table if not exists public.gang_messages(
  id bigint generated by default as identity primary key,
  gang_id uuid not null references public.gangs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now());
create index if not exists gang_messages_idx on public.gang_messages(gang_id, created_at desc);
alter table public.gang_messages enable row level security;
drop policy if exists "gang chat members" on public.gang_messages;
create policy "gang chat members" on public.gang_messages for select using (
  exists(select 1 from public.gang_members m where m.gang_id=gang_messages.gang_id and m.user_id=auth.uid()));

create table if not exists public.gang_wars(
  id bigint generated by default as identity primary key,
  attacker_gang uuid not null references public.gangs(id) on delete cascade,
  defender_gang uuid not null references public.gangs(id) on delete cascade,
  stake numeric(12,2) not null,
  attacker_score integer not null default 0,
  defender_score integer not null default 0,
  started_at timestamptz not null default now(),
  ends_at timestamptz not null default now()+interval '24 hours',
  winner_gang uuid,
  resolved boolean not null default false);
create index if not exists gang_wars_open_idx on public.gang_wars(resolved, ends_at);
alter table public.gang_wars enable row level security;
drop policy if exists "gang wars public" on public.gang_wars;
create policy "gang wars public" on public.gang_wars for select using (true);

create trigger guard_banned_actor before insert or delete or update on public.gang_messages for each row execute function public.block_banned_actor();
create trigger guard_banned_actor before insert or delete or update on public.gang_requests for each row execute function public.block_banned_actor();

-- ---------- Helfer ----------
create or replace function public.kiez_gang_log(gid uuid, uid uuid, k text, amt numeric, txt text)
returns void language sql as $$ insert into public.gang_log(gang_id,user_id,kind,amount,info) values(gid,uid,k,coalesce(amt,0),coalesce(txt,'')) $$;

-- eigene Mitgliedschaft; wirft Fehler, wenn Rolle nicht reicht
create or replace function public.kiez_my_gang(min_role text default 'member')
returns public.gang_members language plpgsql security definer set search_path to 'public' as $function$
declare m public.gang_members; rank_of jsonb := '{"member":1,"officer":2,"co":3,"owner":4}';
begin
  select * into m from public.gang_members where user_id=auth.uid();
  if m.gang_id is null then raise exception 'Du bist in keiner Bande'; end if;
  if (rank_of->>m.role)::int < (rank_of->>min_role)::int then raise exception 'Dafür reicht dein Rang in der Bande nicht'; end if;
  return m;
end $function$;

create or replace function public.kiez_join(gid uuid, uid uuid)
returns void language plpgsql security definer set search_path to 'public' as $function$
begin
  if exists(select 1 from public.gang_members where user_id=uid) then raise exception 'Schon in einer Bande'; end if;
  if (select count(*) from public.gang_members where gang_id=gid)>=30 then raise exception 'Die Bande ist voll (30 Mitglieder)'; end if;
  insert into public.gang_members(gang_id,user_id,role) values(gid,uid,'member');
  delete from public.gang_requests where user_id=uid;
  perform public.kiez_gang_log(gid,uid,'join',0,'ist beigetreten');
end $function$;

-- ---------- Gruenden / Beitreten / Verlassen ----------
create or replace function public.create_gang(gang_name text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare g public.gangs; p public.profiles; cost numeric := 50; clean text := trim(gang_name);
begin
  p := public.kiez_actor();
  if exists(select 1 from public.gang_members where user_id=p.id) then raise exception 'Du bist bereits in einer Bande'; end if;
  if not public.valid_game_name(clean,3,30) then raise exception 'Bandenname: 3 bis 30 Zeichen, nur Buchstaben, Zahlen, Leerzeichen, _ . -'; end if;
  if exists(select 1 from public.gangs where lower(name)=lower(clean)) then raise exception 'Diesen Bandennamen gibt es schon'; end if;
  if p.money<cost then raise exception 'Eine Bandengründung kostet 50 €'; end if;
  insert into public.gangs(name,owner_id) values(clean,p.id) returning * into g;
  insert into public.gang_members(gang_id,user_id,role) values(g.id,p.id,'owner');
  delete from public.gang_requests where user_id=p.id;
  update public.profiles set money=money-cost where id=p.id;
  perform public.kiez_gang_log(g.id,p.id,'create',0,'hat die Bande gegründet');
  return to_jsonb(g);
end $function$;

-- Beitreten: offene Bande oder vorliegende Einladung
create or replace function public.join_gang(wanted_gang uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; g public.gangs;
begin
  p := public.kiez_actor();
  select * into g from public.gangs where id=wanted_gang for update;
  if g.id is null then raise exception 'Bande unbekannt'; end if;
  if exists(select 1 from public.gang_members where user_id=p.id) then raise exception 'Du bist bereits in einer Bande'; end if;
  if not g.is_open and not exists(select 1 from public.gang_requests where gang_id=g.id and user_id=p.id and kind='invite') then
    raise exception 'Diese Bande nimmt nur mit Einladung auf – bewirb dich'; end if;
  perform public.kiez_join(g.id,p.id);
  return jsonb_build_object('joined',g.id,'name',g.name);
end $function$;

create or replace function public.gang_apply(wanted_gang uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  if not exists(select 1 from public.gangs where id=wanted_gang) then raise exception 'Bande unbekannt'; end if;
  if exists(select 1 from public.gang_members where user_id=p.id) then raise exception 'Du bist bereits in einer Bande'; end if;
  if (select count(*) from public.gang_requests where user_id=p.id and kind='apply')>=3 then raise exception 'Höchstens 3 offene Bewerbungen'; end if;
  insert into public.gang_requests(gang_id,user_id,kind,created_by) values(wanted_gang,p.id,'apply',p.id)
  on conflict (gang_id,user_id) do nothing;
  if not found then raise exception 'Da läuft schon eine Anfrage'; end if;
  return jsonb_build_object('applied',wanted_gang);
end $function$;

create or replace function public.gang_invite(target_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('officer');
  if not exists(select 1 from public.profiles where id=target_id and not is_banned) then raise exception 'Spieler unbekannt'; end if;
  if exists(select 1 from public.gang_members where user_id=target_id) then raise exception 'Der Spieler ist schon in einer Bande'; end if;
  -- Bewerbung liegt vor -> direkt aufnehmen
  if exists(select 1 from public.gang_requests where gang_id=m.gang_id and user_id=target_id and kind='apply') then
    perform public.kiez_join(m.gang_id,target_id);
    return jsonb_build_object('status','joined');
  end if;
  insert into public.gang_requests(gang_id,user_id,kind,created_by) values(m.gang_id,target_id,'invite',p.id)
  on conflict (gang_id,user_id) do nothing;
  if not found then raise exception 'Der Spieler ist schon eingeladen'; end if;
  perform public.kiez_gang_log(m.gang_id,p.id,'invite',0,'hat '||(select username from public.profiles where id=target_id)||' eingeladen');
  return jsonb_build_object('status','invited');
end $function$;

-- Anfrage/Einladung zurueckziehen oder ablehnen (Spieler selbst oder Bandenfuehrung)
create or replace function public.gang_request_delete(wanted_gang uuid, target_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; allowed boolean;
begin
  p := public.kiez_actor();
  allowed := target_id=p.id or exists(select 1 from public.gang_members where gang_id=wanted_gang and user_id=p.id and role in ('owner','co','officer'));
  if not allowed then raise exception 'Das darfst du nicht'; end if;
  delete from public.gang_requests where gang_id=wanted_gang and user_id=target_id;
  return jsonb_build_object('deleted',true);
end $function$;

drop function if exists public.leave_gang();
create or replace function public.leave_gang()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; members int;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('member');
  select count(*) into members from public.gang_members where gang_id=m.gang_id;
  if m.role='owner' and members>1 then raise exception 'Übergib erst die Chefrolle an ein anderes Mitglied'; end if;
  delete from public.gang_members where user_id=p.id;
  if members=1 then delete from public.gangs where id=m.gang_id;
  else perform public.kiez_gang_log(m.gang_id,p.id,'leave',0,'hat die Bande verlassen'); end if;
  return jsonb_build_object('left',m.gang_id);
end $function$;

create or replace function public.kick_gang_member(target_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; t public.gang_members; rank_of jsonb := '{"member":1,"officer":2,"co":3,"owner":4}';
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('co');
  select * into t from public.gang_members where user_id=target_id and gang_id=m.gang_id;
  if t.user_id is null then raise exception 'Nicht in deiner Bande'; end if;
  if (rank_of->>t.role)::int >= (rank_of->>m.role)::int then raise exception 'Du kannst nur niedrigere Ränge rauswerfen'; end if;
  delete from public.gang_members where user_id=target_id;
  perform public.kiez_gang_log(m.gang_id,p.id,'kick',0,'hat '||(select username from public.profiles where id=target_id)||' rausgeworfen');
  return jsonb_build_object('kicked',target_id);
end $function$;

create or replace function public.set_gang_role(target_id uuid, new_role text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('owner');
  if new_role not in ('co','officer','member','owner') then raise exception 'Unbekannter Rang'; end if;
  if target_id=p.id then raise exception 'Deinen eigenen Rang kannst du nicht ändern'; end if;
  if not exists(select 1 from public.gang_members where user_id=target_id and gang_id=m.gang_id) then raise exception 'Nicht in deiner Bande'; end if;
  if new_role='owner' then
    update public.gang_members set role='co' where user_id=p.id;
    update public.gangs set owner_id=target_id where id=m.gang_id;
  end if;
  update public.gang_members set role=new_role where user_id=target_id;
  perform public.kiez_gang_log(m.gang_id,p.id,'role',0,(select username from public.profiles where id=target_id)||' ist jetzt '||
    case new_role when 'owner' then 'Chef' when 'co' then 'Vize' when 'officer' then 'Offizier' else 'Mitglied' end);
  return jsonb_build_object('role',new_role);
end $function$;

create or replace function public.update_gang_profile(new_description text, open_for_all boolean)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; g public.gangs; d text := trim(coalesce(new_description,''));
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('co');
  if char_length(d)>1000 then raise exception 'Beschreibung höchstens 1000 Zeichen'; end if;
  update public.gangs set description=d, is_open=coalesce(open_for_all,false) where id=m.gang_id returning * into g;
  return to_jsonb(g);
end $function$;

-- ---------- Kasse & Ausbau ----------
create or replace function public.donate_to_gang(amount numeric)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; amt numeric(12,2) := round(coalesce(amount,0),2);
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('member');
  if amt<=0 then raise exception 'Betrag ungültig'; end if;
  if p.money<amt then raise exception 'Dafür reicht deine Kohle nicht'; end if;
  update public.profiles set money=money-amt where id=p.id;
  update public.gangs set balance=balance+amt where id=m.gang_id;
  perform public.kiez_gang_log(m.gang_id,p.id,'donate',amt,'hat eingezahlt');
  return jsonb_build_object('donated',amt);
end $function$;

create or replace function public.upgrade_gang(kind text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; g public.gangs; cost numeric; lvl int;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('co');
  select * into g from public.gangs where id=m.gang_id for update;
  if kind='attack' then lvl:=g.attack_level; elsif kind='defense' then lvl:=g.defense_level; else raise exception 'Ungültiger Ausbau'; end if;
  if lvl>=10 then raise exception 'Bereits maximal ausgebaut'; end if;
  cost := 50*power(lvl+1,2);
  if g.balance<cost then raise exception 'Zu wenig in der Bandenkasse (% € nötig)', cost; end if;
  if kind='attack' then update public.gangs set balance=balance-cost,attack_level=attack_level+1 where id=g.id returning * into g;
  else update public.gangs set balance=balance-cost,defense_level=defense_level+1 where id=g.id returning * into g; end if;
  perform public.kiez_gang_log(g.id,p.id,'upgrade',-cost,case kind when 'attack' then 'Angriff' else 'Verteidigung' end||' auf Stufe '||(lvl+1));
  return to_jsonb(g);
end $function$;

-- ---------- Bandenchat ----------
create or replace function public.post_gang_message(message_body text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; clean text := trim(coalesce(message_body,'')); mid bigint;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('member');
  if char_length(clean) not between 1 and 500 then raise exception 'Nachricht muss 1 bis 500 Zeichen haben'; end if;
  if (select count(*) from public.gang_messages where user_id=p.id and created_at>now()-interval '1 minute')>=6 then
    raise exception 'Nicht so schnell – warte kurz'; end if;
  insert into public.gang_messages(gang_id,user_id,body) values(m.gang_id,p.id,clean) returning id into mid;
  return jsonb_build_object('id',mid);
end $function$;

-- ---------- Bandenkriege ----------
create or replace function public.resolve_gang_wars()
returns integer language plpgsql security definer set search_path to 'public' as $function$
declare w public.gang_wars; n int := 0; taken numeric;
begin
  for w in select * from public.gang_wars where not resolved and ends_at<=now() for update skip locked loop
    if w.attacker_score>w.defender_score then
      select least(w.stake, balance) into taken from public.gangs where id=w.defender_gang;
      taken := coalesce(taken,0);
      update public.gangs set balance=balance-taken, war_losses=war_losses+1 where id=w.defender_gang;
      update public.gangs set balance=balance+w.stake+taken, war_wins=war_wins+1 where id=w.attacker_gang;
      update public.gang_wars set winner_gang=w.attacker_gang, resolved=true where id=w.id;
      perform public.kiez_gang_log(w.attacker_gang,null,'war',w.stake+taken,'Bandenkrieg gewonnen');
      perform public.kiez_gang_log(w.defender_gang,null,'war',-taken,'Bandenkrieg verloren');
    elsif w.defender_score>w.attacker_score then
      update public.gangs set balance=balance+w.stake, war_wins=war_wins+1 where id=w.defender_gang;
      update public.gangs set war_losses=war_losses+1 where id=w.attacker_gang;
      update public.gang_wars set winner_gang=w.defender_gang, resolved=true where id=w.id;
      perform public.kiez_gang_log(w.defender_gang,null,'war',w.stake,'Bandenkrieg abgewehrt');
      perform public.kiez_gang_log(w.attacker_gang,null,'war',0,'Bandenkrieg verloren');
    else
      update public.gangs set balance=balance+w.stake where id=w.attacker_gang;
      update public.gang_wars set resolved=true where id=w.id;
      perform public.kiez_gang_log(w.attacker_gang,null,'war',w.stake,'Bandenkrieg unentschieden – Einsatz zurück');
      perform public.kiez_gang_log(w.defender_gang,null,'war',0,'Bandenkrieg unentschieden');
    end if;
    n := n+1;
  end loop;
  return n;
end $function$;
grant execute on function public.resolve_gang_wars() to authenticated;

create or replace function public.declare_gang_war(target_gang uuid, stake numeric)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; g public.gangs; st numeric(12,2) := round(coalesce(stake,0),2); w public.gang_wars;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('co');
  perform public.resolve_gang_wars();
  if target_gang=m.gang_id then raise exception 'Keinen Krieg gegen die eigene Bande'; end if;
  if not exists(select 1 from public.gangs where id=target_gang) then raise exception 'Bande unbekannt'; end if;
  if st<20 then raise exception 'Mindesteinsatz 20 €'; end if;
  if (select count(*) from public.gang_members where gang_id=m.gang_id)<2 or (select count(*) from public.gang_members where gang_id=target_gang)<2 then
    raise exception 'Beide Banden brauchen mindestens 2 Mitglieder'; end if;
  if exists(select 1 from public.gang_wars where not resolved and (attacker_gang in (m.gang_id,target_gang) or defender_gang in (m.gang_id,target_gang))) then
    raise exception 'Eine der Banden steckt schon in einem Krieg'; end if;
  if exists(select 1 from public.gang_wars where attacker_gang=m.gang_id and defender_gang=target_gang and started_at>now()-interval '3 days') then
    raise exception 'Gegen diese Bande erst wieder in 3 Tagen'; end if;
  select * into g from public.gangs where id=m.gang_id for update;
  if g.balance<st then raise exception 'Zu wenig in der Bandenkasse'; end if;
  update public.gangs set balance=balance-st where id=g.id;
  insert into public.gang_wars(attacker_gang,defender_gang,stake) values(g.id,target_gang,st) returning * into w;
  perform public.kiez_gang_log(g.id,p.id,'war',-st,'hat den Krieg erklärt gegen '||(select name from public.gangs where id=target_gang));
  perform public.kiez_gang_log(target_gang,null,'war',0,g.name||' hat euch den Krieg erklärt');
  return to_jsonb(w);
end $function$;

-- Kaempfe zaehlen im Bandenkrieg: Sieger-Bande bekommt einen Punkt
create or replace function public.kiez_count_war_fight()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare wg uuid; lg uuid; loser uuid;
begin
  loser := case when new.winner_id=new.attacker_id then new.defender_id else new.attacker_id end;
  select gang_id into wg from public.gang_members where user_id=new.winner_id;
  select gang_id into lg from public.gang_members where user_id=loser;
  if wg is null or lg is null then return new; end if;
  update public.gang_wars set attacker_score=attacker_score+1 where not resolved and ends_at>now() and attacker_gang=wg and defender_gang=lg;
  update public.gang_wars set defender_score=defender_score+1 where not resolved and ends_at>now() and defender_gang=wg and attacker_gang=lg;
  return new;
end $function$;
drop trigger if exists fights_gang_war on public.fights;
create trigger fights_gang_war after insert on public.fights for each row execute function public.kiez_count_war_fight();

-- ---------- Banden-Highscore ----------
create or replace function public.gang_highscore()
returns table(id uuid, name text, members bigint, points bigint, war_wins integer, attack_level integer, defense_level integer)
language sql stable security definer set search_path to 'public' as $$
  select g.id, g.name, count(m.user_id), coalesce(sum(p.xp),0)::bigint + g.war_wins*500, g.war_wins, g.attack_level, g.defense_level
  from public.gangs g left join public.gang_members m on m.gang_id=g.id left join public.profiles p on p.id=m.user_id
  group by g.id order by 4 desc, g.name limit 50
$$;
grant execute on function public.gang_highscore() to anon, authenticated;

revoke execute on function public.kiez_my_gang(text) from public, anon, authenticated;
revoke execute on function public.kiez_join(uuid,uuid) from public, anon, authenticated;
revoke execute on function public.kiez_gang_log(uuid,uuid,text,numeric,text) from public, anon, authenticated;
