-- 0005: Etappe 6 – Tierkämpfe, Wochen-Wettbewerbe, 30+ Erfolge, Events verwalten, Startgeld

-- Neue Spieler starten mit 5 EUR, damit die erste Weiterbildung sofort geht
alter table public.profiles alter column money set default 5;

-- ---------- Tierkämpfe ----------
create table if not exists public.pet_fights(
  id bigint generated by default as identity primary key,
  attacker_id uuid not null references public.profiles(id) on delete cascade,
  defender_id uuid not null references public.profiles(id) on delete cascade,
  attacker_pet text not null,
  defender_pet text not null,
  winner_id uuid not null,
  attacker_power integer not null,
  defender_power integer not null,
  reward numeric(12,2) not null default 0,
  created_at timestamptz not null default now());
create index if not exists pet_fights_idx on public.pet_fights(attacker_id, created_at desc);
alter table public.pet_fights enable row level security;
drop policy if exists "pet fight participants" on public.pet_fights;
create policy "pet fight participants" on public.pet_fights for select using (attacker_id=auth.uid() or defender_id=auth.uid());
alter table public.profiles add column if not exists pet_wins integer not null default 0;

create or replace function public.pet_fight(target_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare a public.profiles; d public.profiles; ap record; dp record; apow int; dpow int; won boolean; reward numeric(12,2):=0; cost int:=10;
  min_lvl int; max_lvl int;
begin
  if target_id=auth.uid() then raise exception 'Dein Tier kämpft nicht gegen sich selbst'; end if;
  a := public.kiez_actor();
  perform public.kiez_assert_free(a);
  select * into d from public.profiles where id=target_id;
  if d.id is null or d.is_banned then raise exception 'Gegner verschwunden'; end if;
  if a.energy<cost then raise exception 'Nicht genug Energie (10 nötig)'; end if;
  min_lvl := greatest(1,floor(a.level*0.8)::int); max_lvl := ceil(a.level*1.5)::int;
  if d.level<min_lvl or d.level>max_lvl then raise exception 'Nur gegen Level % bis %', min_lvl, max_lvl; end if;
  select up.*, pc.name, pc.attack as base_att, pc.defense as base_def into ap
    from public.user_pets up join public.pet_catalog pc on pc.id=up.pet_id where up.user_id=a.id and up.active;
  if ap.pet_id is null then raise exception 'Du hast keinen aktiven Begleiter'; end if;
  select up.*, pc.name, pc.attack as base_att, pc.defense as base_def into dp
    from public.user_pets up join public.pet_catalog pc on pc.id=up.pet_id where up.user_id=d.id and up.active;
  if dp.pet_id is null then raise exception 'Der Gegner hat keinen aktiven Begleiter'; end if;
  if exists(select 1 from public.pet_fights where attacker_id=a.id and defender_id=d.id and created_at>now()-interval '1 hour') then
    raise exception 'Gegen dieses Tier erst wieder in einer Stunde'; end if;
  apow := ap.base_att*ap.attack_level*2 + ap.base_def*ap.defense_level + floor(random()*11)::int;
  dpow := dp.base_def*dp.defense_level*2 + dp.base_att*dp.attack_level + floor(random()*11)::int;
  won := apow>dpow;
  if won then
    reward := least(round(0.5+a.level*0.05,2), greatest(0,a.cash_capacity-a.money));
    update public.profiles set energy=energy-cost, money=money+reward, xp=xp+8, pet_wins=pet_wins+1 where id=a.id returning * into a;
  else
    update public.profiles set energy=energy-cost, xp=xp+2 where id=a.id returning * into a;
    update public.profiles set xp=xp+4, pet_wins=pet_wins+1 where id=d.id;
  end if;
  insert into public.pet_fights(attacker_id,defender_id,attacker_pet,defender_pet,winner_id,attacker_power,defender_power,reward)
  values(a.id,d.id,ap.pet_id,dp.pet_id,case when won then a.id else d.id end,apow,dpow,reward);
  return jsonb_build_object('result',case when won then 'win' else 'loss' end,'my_pet',ap.name,'enemy_pet',dp.name,
    'opponent',d.username,'attacker_power',apow,'defender_power',dpow,'reward',reward,'profile',to_jsonb(a));
end $function$;

-- ---------- Wochen-Wettbewerbe (Flaschen & Siege, Montag–Sonntag) ----------
create table if not exists public.weekly_scores(
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  bottles integer not null default 0,
  wins integer not null default 0,
  primary key(user_id, week_start));
alter table public.weekly_scores enable row level security;
drop policy if exists "weekly public" on public.weekly_scores;
create policy "weekly public" on public.weekly_scores for select using (true);

create table if not exists public.competition_payouts(
  week_start date not null,
  category text not null,
  rank integer not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  caps integer not null,
  points integer not null,
  primary key(week_start, category, rank));
alter table public.competition_payouts enable row level security;
drop policy if exists "payouts public" on public.competition_payouts;
create policy "payouts public" on public.competition_payouts for select using (true);

create or replace function public.kiez_week(d date) returns date language sql immutable as $$ select date_trunc('week',d)::date $$;

create or replace function public.kiez_track_bottles()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare delta int := new.progress - case when tg_op='UPDATE' then old.progress else 0 end;
begin
  if delta>0 then
    insert into public.weekly_scores(user_id,week_start,bottles) values(new.user_id,public.kiez_week(new.mission_day),delta)
    on conflict (user_id,week_start) do update set bottles=public.weekly_scores.bottles+excluded.bottles;
  end if;
  return new;
end $function$;
drop trigger if exists daily_missions_weekly on public.daily_missions;
create trigger daily_missions_weekly after insert or update of progress on public.daily_missions for each row execute function public.kiez_track_bottles();

create or replace function public.kiez_track_wins()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  insert into public.weekly_scores(user_id,week_start,wins) values(new.winner_id,public.kiez_week(current_date),1)
  on conflict (user_id,week_start) do update set wins=public.weekly_scores.wins+1;
  return new;
end $function$;
drop trigger if exists fights_weekly on public.fights;
create trigger fights_weekly after insert on public.fights for each row execute function public.kiez_track_wins();

-- Zahlt vergangene Wochen einmalig aus: Platz 1–3 je Kategorie
create or replace function public.resolve_competitions()
returns integer language plpgsql security definer set search_path to 'public' as $function$
declare wk date; cat text; r record; n int := 0; caps int[] := array[50,30,15]; pts int[] := array[500,300,150];
begin
  for wk in select distinct week_start from public.weekly_scores
            where week_start < public.kiez_week(current_date)
              and week_start not in (select week_start from public.competition_payouts) loop
    foreach cat in array array['bottles','wins'] loop
      for r in select user_id, row_number() over (order by case cat when 'bottles' then bottles else wins end desc, user_id) as rk
               from public.weekly_scores where week_start=wk and (case cat when 'bottles' then bottles else wins end)>0
               order by rk limit 3 loop
        insert into public.competition_payouts(week_start,category,rank,user_id,caps,points)
        values(wk,cat,r.rk,r.user_id,caps[r.rk],pts[r.rk]) on conflict do nothing;
        if found then
          update public.profiles set bottlecaps=bottlecaps+caps[r.rk], xp=xp+pts[r.rk] where id=r.user_id;
          n := n+1;
        end if;
      end loop;
    end loop;
    -- Woche ohne Gewinner trotzdem als erledigt markieren
    insert into public.competition_payouts(week_start,category,rank,user_id,caps,points)
    select wk,'done',0,(select user_id from public.weekly_scores where week_start=wk limit 1),0,0 on conflict do nothing;
  end loop;
  return n;
end $function$;

create or replace function public.weekly_ranking(category text)
returns table(rank bigint, user_id uuid, username text, score integer)
language plpgsql security definer set search_path to 'public' as $function$
begin
  if category not in ('bottles','wins') then raise exception 'Unbekannte Kategorie'; end if;
  perform public.resolve_competitions();
  return query
    select row_number() over (order by case category when 'bottles' then w.bottles else w.wins end desc, w.user_id),
           w.user_id, p.username, case category when 'bottles' then w.bottles else w.wins end
    from public.weekly_scores w join public.profiles p on p.id=w.user_id
    where w.week_start=public.kiez_week(current_date) and not p.is_banned
      and (case category when 'bottles' then w.bottles else w.wins end)>0
    order by 1 limit 20;
end $function$;
grant execute on function public.weekly_ranking(text) to authenticated;

-- ---------- Erfolge: 32 Stück, datengetrieben ----------
alter table public.achievement_defs
  add column if not exists stat text,
  add column if not exists threshold numeric not null default 0,
  add column if not exists reward_caps integer not null default 0;

insert into public.achievement_defs(id,name,description,reward,sort_order,stat,threshold,reward_caps) values
 ('first_bottles','Erster Sack','20 Flaschen gesammelt',5,1,'bottles_total',20,1),
 ('collector','Pfandbaron','100 Flaschen gesammelt',20,2,'bottles_total',100,2),
 ('bottles_1000','Containerkönig','1.000 Flaschen gesammelt',50,3,'bottles_total',1000,5),
 ('bottles_10000','Flaschenflüsterer','10.000 Flaschen gesammelt',200,4,'bottles_total',10000,15),
 ('bottles_100000','Pfandlegende','100.000 Flaschen gesammelt',1000,5,'bottles_total',100000,50),
 ('level_five','Kiezbekannt','Level 5 erreicht',15,10,'level',5,2),
 ('veteran','Kiezlegende','Level 10 erreicht',50,11,'level',10,5),
 ('level_25','Stadtgespräch','Level 25 erreicht',150,12,'level',25,10),
 ('level_50','Kiezfürst','Level 50 erreicht',500,13,'level',50,25),
 ('level_100','Kiezkönig','Level 100 erreicht',2000,14,'level',100,100),
 ('first_win','Erste Schelle','Ersten Kampf gewonnen',10,20,'wins',1,1),
 ('wins_10','Hinterhof-Boxer','10 Kämpfe gewonnen',30,21,'wins',10,3),
 ('wins_100','Kiezschläger','100 Kämpfe gewonnen',150,22,'wins',100,15),
 ('wins_1000','Unbesiegbar','1.000 Kämpfe gewonnen',1000,23,'wins',1000,60),
 ('rich','Kleingeldkönig','100 € auf einmal besessen',25,30,'money',100,2),
 ('rich_1000','Geldsack','1.000 € auf einmal besessen',100,31,'money',1000,10),
 ('earned_10000','Großverdiener','10.000 € mit Pfand verdient',300,32,'bottle_money',10000,20),
 ('attack_25','Schlagkräftig','Angriff Stufe 25',50,40,'attack_skill',25,5),
 ('defense_25','Dickes Fell','Verteidigung Stufe 25',50,41,'defense_skill',25,5),
 ('social_20','Kiezdiplomat','Sozialkontakte Stufe 20',80,42,'social_skill',20,8),
 ('music_5','Straßenmusiker','Fünftes Instrument besessen',60,43,'music_level',5,6),
 ('house_10','Eigenes Dach','Unterkunft Stufe 10 bewohnt',100,50,'shelter_level',10,10),
 ('house_20','Burgherr','In der Burg eingezogen',500,51,'shelter_level',20,40),
 ('area_5','Stadtkenner','Alle Sammelgebiete freigeschaltet',100,52,'area_level',5,10),
 ('streak_7','Stammgast','7 Tage in Folge eingeloggt',20,60,'login_streak',7,5),
 ('streak_30','Urgestein','30 Tage in Folge eingeloggt',100,61,'login_streak',30,25),
 ('pet_owner','Tierfreund','Ersten Begleiter gekauft',10,70,'pets',1,2),
 ('pet_wins_10','Tierflüsterer','10 Tierkämpfe gewonnen',50,71,'pet_wins',10,8),
 ('plunder_5','Sammler','5 verschiedene Plunderstücke gefunden',30,80,'plunder_kinds',5,5),
 ('plunder_all','Plunderkönig','Jedes Plunderstück gefunden',300,81,'plunder_kinds',14,30),
 ('friends_5','Beliebt','5 Freunde gefunden',20,90,'friends',5,3),
 ('gang_member','Bandenmitglied','Einer Bande beigetreten',10,91,'in_gang',1,2),
 ('donations_50','Spendenmagnet','50 Spenden über deinen Link erhalten',60,92,'donations',50,8),
 ('crimes_25','Unterwelt','25 Verbrechen erfolgreich begangen',60,93,'crimes',25,6)
on conflict (id) do update set name=excluded.name, description=excluded.description, reward=excluded.reward,
  sort_order=excluded.sort_order, stat=excluded.stat, threshold=excluded.threshold, reward_caps=excluded.reward_caps;

create or replace function public.check_achievements()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; st jsonb; unlocked jsonb := '[]'::jsonb; a record; paid numeric;
begin
  p := public.kiez_actor();
  st := jsonb_build_object(
    'bottles_total',(select coalesce(sum(progress),0) from public.daily_missions where user_id=p.id),
    'level',p.level,'wins',p.wins,'money',p.money,'bottle_money',p.bottles_lifetime_earned,
    'attack_skill',p.attack_skill,'defense_skill',p.defense_skill,'social_skill',p.social_skill,'music_level',p.music_level,
    'shelter_level',p.shelter_level,'area_level',p.area_level,'login_streak',p.login_streak,
    'pets',(select count(*) from public.user_pets where user_id=p.id),
    'pet_wins',p.pet_wins,
    'plunder_kinds',(select count(*) from public.user_plunder where user_id=p.id),
    'friends',(select count(*) from public.friendships where (user_id=p.id or friend_id=p.id) and status='accepted'),
    'in_gang',(select count(*) from public.gang_members where user_id=p.id),
    'donations',p.donations_received,
    'crimes',(select count(*) from public.side_action_log where user_id=p.id and action_type like 'crime:%' and success));
  for a in select d.* from public.achievement_defs d
           where d.stat is not null and coalesce((st->>d.stat)::numeric,0) >= d.threshold
             and not exists(select 1 from public.user_achievements u where u.user_id=p.id and u.achievement_id=d.id)
           order by d.sort_order loop
    insert into public.user_achievements(user_id,achievement_id) values(p.id,a.id);
    select least(a.reward, greatest(0,cash_capacity-money)) into paid from public.profiles where id=p.id;
    update public.profiles set money=money+paid, bottlecaps=bottlecaps+a.reward_caps where id=p.id;
    unlocked := unlocked || jsonb_build_array(jsonb_build_object('name',a.name,'reward',paid,'caps',a.reward_caps));
  end loop;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('unlocked',unlocked,'stats',st,'profile',to_jsonb(p));
end $function$;

-- ---------- Admin: Events verwalten ----------
create or replace function public.kiez_require_admin()
returns void language plpgsql security definer set search_path to 'public' as $function$
begin
  if not coalesce((select is_admin from public.profiles where id=auth.uid()),false) then raise exception 'Nur für Admins'; end if;
end $function$;

create or replace function public.admin_create_event(event_name text, event_description text, starts timestamptz, ends timestamptz,
  bottle_bonus integer, xp_bonus integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare e public.events;
begin
  perform public.kiez_require_admin();
  if char_length(trim(coalesce(event_name,''))) not between 3 and 60 then raise exception 'Name 3 bis 60 Zeichen'; end if;
  if ends<=starts then raise exception 'Ende muss nach dem Start liegen'; end if;
  if bottle_bonus not between 0 and 200 or xp_bonus not between 0 and 200 then raise exception 'Bonus 0 bis 200 Prozent'; end if;
  insert into public.events(name,description,starts_at,ends_at,bottle_bonus,xp_bonus)
  values(trim(event_name),trim(coalesce(event_description,'')),starts,ends,bottle_bonus,xp_bonus) returning * into e;
  return to_jsonb(e);
end $function$;

create or replace function public.admin_delete_event(event_id bigint)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.kiez_require_admin();
  delete from public.events where id=event_id;
  return jsonb_build_object('deleted',event_id);
end $function$;

revoke execute on function public.kiez_require_admin() from public, anon, authenticated;
revoke execute on function public.resolve_competitions() from public, anon;
grant execute on function public.resolve_competitions() to authenticated;
