-- 0008: Restliche Pennergame-Funktionen – Systemnachrichten, gelesene Post, Profilbild, Werbelink (Freunde werben),
-- Gegenstände verkaufen, öffentliches Kiez-Brett, Namensänderung, Kiez-Lotto, Erfolgs-Fortschritt

-- ---------- Systemnachrichten ----------
create table if not exists public.notifications(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz);
create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);
alter table public.notifications enable row level security;
drop policy if exists "own notifications" on public.notifications;
create policy "own notifications" on public.notifications for select using (user_id = auth.uid());
grant select on public.notifications to authenticated;
revoke insert, update, delete, truncate on public.notifications from anon, authenticated;

create or replace function public.kiez_notify(uid uuid, k text, txt text)
returns void language sql security definer set search_path to 'public' as $$
  insert into public.notifications(user_id,kind,body) select uid,k,txt where uid is not null
$$;
revoke execute on function public.kiez_notify(uuid,text,text) from public, anon, authenticated;

create or replace function public.kiez_name(uid uuid) returns text language sql stable security definer set search_path to 'public' as
$$ select coalesce((select username from public.profiles where id=uid),'Jemand') $$;

-- Kampf: Verteidiger erfährt davon
create or replace function public.kiez_notify_fight() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.kiez_notify(new.defender_id,'kampf',
    case when new.winner_id=new.defender_id
      then public.kiez_name(new.attacker_id)||' hat dich angegriffen – du hast gewonnen ('||new.defender_power||':'||new.attacker_power||').'
      else public.kiez_name(new.attacker_id)||' hat dich verprügelt ('||new.attacker_power||':'||new.defender_power||') und '||
           replace(to_char(new.loot,'FM999999990.00'),'.',',')||' € erbeutet.' end);
  return new;
end $function$;
drop trigger if exists fights_notify on public.fights;
create trigger fights_notify after insert on public.fights for each row execute function public.kiez_notify_fight();

create or replace function public.kiez_notify_pet_fight() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.kiez_notify(new.defender_id,'tierkampf', public.kiez_name(new.attacker_id)||'s Tier hat deins herausgefordert – '||
    case when new.winner_id=new.defender_id then 'dein Begleiter hat gewonnen.' else 'dein Begleiter hat verloren.' end);
  return new;
end $function$;
drop trigger if exists pet_fights_notify on public.pet_fights;
create trigger pet_fights_notify after insert on public.pet_fights for each row execute function public.kiez_notify_pet_fight();

create or replace function public.kiez_notify_friend() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if tg_op='INSERT' then perform public.kiez_notify(new.friend_id,'freund',public.kiez_name(new.user_id)||' möchte mit dir befreundet sein.');
  elsif new.status='accepted' and old.status<>'accepted' then perform public.kiez_notify(new.user_id,'freund',public.kiez_name(new.friend_id)||' hat deine Freundschaftsanfrage angenommen.');
  end if;
  return new;
end $function$;
drop trigger if exists friendships_notify on public.friendships;
create trigger friendships_notify after insert or update on public.friendships for each row execute function public.kiez_notify_friend();

create or replace function public.kiez_notify_guestbook() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.owner_id<>new.author_id then perform public.kiez_notify(new.owner_id,'gaestebuch',public.kiez_name(new.author_id)||' hat in dein Gästebuch geschrieben.'); end if;
  return new;
end $function$;
drop trigger if exists guestbook_notify on public.guestbook_entries;
create trigger guestbook_notify after insert on public.guestbook_entries for each row execute function public.kiez_notify_guestbook();

create or replace function public.kiez_notify_gang_request() returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare gname text := (select name from public.gangs where id=new.gang_id); m record;
begin
  if new.kind='invite' then perform public.kiez_notify(new.user_id,'bande','Die Bande „'||gname||'“ lädt dich ein. Annehmen unter Bande.');
  else
    for m in select user_id from public.gang_members where gang_id=new.gang_id and role in ('owner','co','officer') loop
      perform public.kiez_notify(m.user_id,'bande',public.kiez_name(new.user_id)||' bewirbt sich bei eurer Bande.');
    end loop;
  end if;
  return new;
end $function$;
drop trigger if exists gang_requests_notify on public.gang_requests;
create trigger gang_requests_notify after insert on public.gang_requests for each row execute function public.kiez_notify_gang_request();

create or replace function public.kiez_notify_war() returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare m record; a text := (select name from public.gangs where id=new.attacker_gang); d text := (select name from public.gangs where id=new.defender_gang);
begin
  if tg_op='INSERT' then
    for m in select user_id from public.gang_members where gang_id=new.defender_gang loop
      perform public.kiez_notify(m.user_id,'bande','⚔️ „'||a||'“ hat eurer Bande den Krieg erklärt! 24 Stunden – jeder Sieg zählt.'); end loop;
  elsif new.resolved and not old.resolved then
    for m in select user_id from public.gang_members where gang_id in (new.attacker_gang,new.defender_gang) loop
      perform public.kiez_notify(m.user_id,'bande','Bandenkrieg „'||a||'“ gegen „'||d||'“ beendet ('||new.attacker_score||':'||new.defender_score||').'); end loop;
  end if;
  return new;
end $function$;
drop trigger if exists gang_wars_notify on public.gang_wars;
create trigger gang_wars_notify after insert or update on public.gang_wars for each row execute function public.kiez_notify_war();

create or replace function public.kiez_notify_payout() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.category in ('bottles','wins') then
    perform public.kiez_notify(new.user_id,'wettbewerb','🏆 Wochenwettbewerb: Platz '||new.rank||' bei '||
      case new.category when 'bottles' then 'Flaschen' else 'Siegen' end||' – +'||new.caps||' Kronkorken und +'||new.points||' Punkte!');
  end if;
  return new;
end $function$;
drop trigger if exists payouts_notify on public.competition_payouts;
create trigger payouts_notify after insert on public.competition_payouts for each row execute function public.kiez_notify_payout();

create or replace function public.mark_notifications_read()
returns integer language sql security definer set search_path to 'public' as $$
  with u as (update public.notifications set read_at=now() where user_id=auth.uid() and read_at is null returning 1) select count(*)::int from u
$$;

create or replace function public.mark_messages_read()
returns integer language sql security definer set search_path to 'public' as $$
  with u as (update public.messages set read_at=now() where recipient_id=auth.uid() and read_at is null returning 1) select count(*)::int from u
$$;

-- Ungelesene Post + Systemnachrichten auf einen Blick
create or replace function public.unread_counts()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object(
    'messages',(select count(*) from public.messages where recipient_id=auth.uid() and read_at is null),
    'notifications',(select count(*) from public.notifications where user_id=auth.uid() and read_at is null))
$$;

-- ---------- Profilbild (klein, als Daten-URL) ----------
alter table public.profiles add column if not exists avatar text;
create or replace function public.set_avatar(image text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  if image is not null and (image !~ '^data:image/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$' or char_length(image)>120000) then
    raise exception 'Bild ungültig oder zu groß'; end if;
  update public.profiles set avatar=image where id=p.id returning * into p;
  return jsonb_build_object('ok',true);
end $function$;

-- ---------- Freunde werben (Werbelink ?ref=Name) ----------
alter table public.profiles
  add column if not exists referred_by uuid references public.profiles(id) on delete set null,
  add column if not exists referral_rewarded boolean not null default false,
  add column if not exists username_changed_at timestamptz;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare wanted text := trim(coalesce(new.raw_user_meta_data->>'username','')); ref uuid;
begin
  if not public.valid_game_name(wanted,3,20)
     or exists(select 1 from public.profiles where lower(username)=lower(wanted)) then
    wanted := 'Kiezkind_' || substr(new.id::text,1,6);
  end if;
  select id into ref from public.profiles where lower(username)=lower(trim(coalesce(new.raw_user_meta_data->>'ref',''))) and not is_banned;
  insert into public.profiles(id, username, referred_by) values(new.id, wanted, ref);
  if ref is not null then perform public.kiez_notify(ref,'werben',wanted||' ist über deinen Werbelink in den Kiez gekommen. Erreicht '||wanted||' Level 5, bekommst du 25 Kronkorken.'); end if;
  return new;
end $function$;

create or replace function public.kiez_referral_reward() returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.level>=5 and old.level<5 and new.referred_by is not null and not new.referral_rewarded then
    update public.profiles set bottlecaps=bottlecaps+25, xp=xp+100 where id=new.referred_by;
    update public.profiles set referral_rewarded=true, bottlecaps=bottlecaps+10 where id=new.id;
    perform public.kiez_notify(new.referred_by,'werben','🎉 '||new.username||' hat Level 5 erreicht: +25 Kronkorken und +100 Punkte für dich!');
    perform public.kiez_notify(new.id,'werben','🎉 Level 5! Als Geworbener bekommst du 10 Kronkorken.');
  end if;
  return new;
end $function$;
drop trigger if exists profile_referral on public.profiles;
-- ohne "of level": das Level setzt der BEFORE-Trigger aus den Punkten, es steht nie selbst im UPDATE
create trigger profile_referral after update on public.profiles for each row when (new.level>=5 and old.level<5) execute function public.kiez_referral_reward();

-- ---------- Namensänderung (30 Kronkorken, höchstens alle 30 Tage) ----------
create or replace function public.change_username(new_name text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; clean text := trim(coalesce(new_name,''));
begin
  p := public.kiez_actor();
  if not public.valid_game_name(clean,3,20) then raise exception 'Name: 3 bis 20 Zeichen, nur Buchstaben, Zahlen, Leerzeichen, _ . -'; end if;
  if exists(select 1 from public.profiles where lower(username)=lower(clean) and id<>p.id) then raise exception 'Diesen Namen gibt es schon'; end if;
  if p.username_changed_at is not null and p.username_changed_at>now()-interval '30 days' then raise exception 'Den Namen kannst du nur alle 30 Tage ändern'; end if;
  if p.bottlecaps<30 then raise exception 'Eine Namensänderung kostet 30 Kronkorken'; end if;
  update public.profiles set username=clean, username_changed_at=now(), bottlecaps=bottlecaps-30 where id=p.id returning * into p;
  return to_jsonb(p);
end $function$;

-- ---------- Gegenstände verkaufen (50 % des Kaufpreises) ----------
create or replace function public.sell_item(wanted_item text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; inv public.inventory; it public.shop_items; price numeric(12,2); paid numeric(12,2);
begin
  p := public.kiez_actor();
  select * into inv from public.inventory where user_id=p.id and item_id=wanted_item for update;
  if inv.item_id is null or inv.quantity<1 then raise exception 'Das hast du nicht'; end if;
  if inv.equipped and inv.quantity<=1 then raise exception 'Leg den Gegenstand erst ab'; end if;
  select * into it from public.shop_items where id=wanted_item;
  price := round(coalesce(it.price,0)*0.5,2);
  paid := least(price, greatest(0,p.cash_capacity-p.money));
  if inv.quantity<=1 then delete from public.inventory where user_id=p.id and item_id=wanted_item;
  else update public.inventory set quantity=quantity-1 where user_id=p.id and item_id=wanted_item; end if;
  update public.profiles set money=money+paid where id=p.id returning * into p;
  return jsonb_build_object('item',it.name,'paid',paid,'lost',price-paid,'profile',to_jsonb(p));
end $function$;

-- ---------- Kiez-Brett (öffentliche Pinnwand) ----------
create table if not exists public.board_posts(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now());
create index if not exists board_posts_idx on public.board_posts(created_at desc);
alter table public.board_posts enable row level security;
drop policy if exists "board public" on public.board_posts;
create policy "board public" on public.board_posts for select using (true);
grant select on public.board_posts to authenticated;
revoke insert, update, delete, truncate on public.board_posts from anon, authenticated;
create trigger guard_banned_actor before insert or delete or update on public.board_posts for each row execute function public.block_banned_actor();

create or replace function public.post_board(message_body text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; clean text := trim(coalesce(message_body,'')); pid bigint;
begin
  p := public.kiez_actor();
  if char_length(clean) not between 2 and 300 then raise exception 'Beitrag muss 2 bis 300 Zeichen haben'; end if;
  if exists(select 1 from public.board_posts where user_id=p.id and created_at>now()-interval '30 seconds') then raise exception 'Nicht so schnell – warte 30 Sekunden'; end if;
  insert into public.board_posts(user_id,body) values(p.id,clean) returning id into pid;
  return jsonb_build_object('id',pid);
end $function$;

create or replace function public.delete_board_post(post_id bigint)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  delete from public.board_posts where id=post_id and (user_id=p.id or p.is_admin);
  if not found then raise exception 'Beitrag nicht gefunden'; end if;
  return jsonb_build_object('deleted',post_id);
end $function$;

-- ---------- Kiez-Lotto: Zahl 1–49 tippen, Ziehung jeden Sonntag ----------
create table if not exists public.lotto_tickets(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  draw_week date not null,
  number integer not null check (number between 1 and 49),
  created_at timestamptz not null default now());
create index if not exists lotto_week_idx on public.lotto_tickets(draw_week, number);
create table if not exists public.lotto_draws(
  draw_week date primary key,
  number integer not null,
  pot numeric(12,2) not null,
  winners integer not null,
  prize numeric(12,2) not null,
  created_at timestamptz not null default now());
alter table public.lotto_tickets enable row level security;
alter table public.lotto_draws enable row level security;
drop policy if exists "own tickets" on public.lotto_tickets;
create policy "own tickets" on public.lotto_tickets for select using (user_id = auth.uid());
drop policy if exists "draws public" on public.lotto_draws;
create policy "draws public" on public.lotto_draws for select using (true);
grant select on public.lotto_tickets, public.lotto_draws to authenticated;
revoke insert, update, delete, truncate on public.lotto_tickets, public.lotto_draws from anon, authenticated;

-- Topf: 80 % der Einsätze der Woche + Jackpot aus Wochen ohne Gewinner + 20 € Grundstock
create or replace function public.kiez_lotto_pot(wk date) returns numeric language sql stable as $$
  select 20 + 0.8*2*(select count(*) from public.lotto_tickets where draw_week=wk)
       -- Jackpot: Topf der letzten Ziehung, falls niemand gewonnen hat (enthält bereits ältere Jackpots)
       + coalesce((select case when winners=0 then pot else 0 end from public.lotto_draws where draw_week<wk order by draw_week desc limit 1),0)
$$;

create or replace function public.resolve_lotto()
returns integer language plpgsql security definer set search_path to 'public' as $function$
declare wk date; num int; pot numeric; w int; prize numeric; t record; n int := 0;
begin
  for wk in select distinct draw_week from public.lotto_tickets where draw_week<public.kiez_week(current_date)
            and draw_week not in (select draw_week from public.lotto_draws) order by 1 loop
    num := 1+floor(random()*49)::int; pot := public.kiez_lotto_pot(wk);
    select count(*) into w from public.lotto_tickets where draw_week=wk and number=num;
    prize := case when w>0 then round(pot/w,2) else 0 end;
    insert into public.lotto_draws(draw_week,number,pot,winners,prize) values(wk,num,pot,w,prize);
    for t in select distinct user_id from public.lotto_tickets where draw_week=wk loop
      if exists(select 1 from public.lotto_tickets where draw_week=wk and user_id=t.user_id and number=num) then
        -- Lottogewinne werden voll ausgezahlt, auch über den Geldbehälter hinaus (Ausnahme von der Deckelung)
        update public.profiles set money=money+prize*(select count(*) from public.lotto_tickets where draw_week=wk and user_id=t.user_id and number=num) where id=t.user_id;
        perform public.kiez_notify(t.user_id,'lotto','🎰 LOTTO-GEWINN! Die Zahl war '||num||'. Du bekommst '||replace(to_char(prize,'FM999999990.00'),'.',',')||' € pro richtigem Los.');
      else
        perform public.kiez_notify(t.user_id,'lotto','Kiez-Lotto: Die Zahl war '||num||'. Leider kein Gewinn.');
      end if;
    end loop;
    n := n+1;
  end loop;
  return n;
end $function$;

create or replace function public.buy_lotto_ticket(chosen integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; wk date := public.kiez_week(current_date);
begin
  p := public.kiez_actor();
  perform public.resolve_lotto();
  if chosen is null or chosen not between 1 and 49 then raise exception 'Wähle eine Zahl von 1 bis 49'; end if;
  if (select count(*) from public.lotto_tickets where user_id=p.id and draw_week=wk)>=10 then raise exception 'Höchstens 10 Lose pro Woche'; end if;
  if p.money<2 then raise exception 'Ein Los kostet 2 €'; end if;
  update public.profiles set money=money-2 where id=p.id returning * into p;
  insert into public.lotto_tickets(user_id,draw_week,number) values(p.id,wk,chosen);
  return jsonb_build_object('number',chosen,'pot',public.kiez_lotto_pot(wk),'profile',to_jsonb(p));
end $function$;

create or replace function public.lotto_info()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare wk date := public.kiez_week(current_date);
begin
  perform public.resolve_lotto();
  return jsonb_build_object('pot',public.kiez_lotto_pot(wk),'draw_at',wk+7,
    'tickets',(select count(*) from public.lotto_tickets where draw_week=wk),
    'mine',(select coalesce(jsonb_agg(number order by id),'[]') from public.lotto_tickets where draw_week=wk and user_id=auth.uid()),
    'last',(select to_jsonb(d) from public.lotto_draws d order by draw_week desc limit 1));
end $function$;

-- ---------- Erfolgs-Fortschritt ohne Freischalten ----------
create or replace function public.kiez_stats(p public.profiles)
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object(
    'bottles_total',(select coalesce(sum(progress),0) from public.daily_missions where user_id=p.id),
    'level',p.level,'wins',p.wins,'money',p.money,'bottle_money',p.bottles_lifetime_earned,
    'attack_skill',p.attack_skill,'defense_skill',p.defense_skill,'social_skill',p.social_skill,'music_level',p.music_level,
    'shelter_level',p.shelter_level,'area_level',p.area_level,'login_streak',p.login_streak,
    'pets',(select count(*) from public.user_pets where user_id=p.id),'pet_wins',p.pet_wins,
    'plunder_kinds',(select count(*) from public.user_plunder where user_id=p.id),
    'friends',(select count(*) from public.friendships where (user_id=p.id or friend_id=p.id) and status='accepted'),
    'in_gang',(select count(*) from public.gang_members where user_id=p.id),
    'donations',p.donations_received,
    'crimes',(select count(*) from public.side_action_log where user_id=p.id and action_type like 'crime:%' and success))
$$;
revoke execute on function public.kiez_stats(public.profiles) from public, anon, authenticated;

create or replace function public.check_achievements()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; st jsonb; unlocked jsonb := '[]'::jsonb; a record; paid numeric;
begin
  p := public.kiez_actor();
  st := public.kiez_stats(p);
  for a in select d.* from public.achievement_defs d
           where d.stat is not null and coalesce((st->>d.stat)::numeric,0) >= d.threshold
             and not exists(select 1 from public.user_achievements u where u.user_id=p.id and u.achievement_id=d.id)
           order by d.sort_order loop
    insert into public.user_achievements(user_id,achievement_id) values(p.id,a.id);
    select least(a.reward, greatest(0,cash_capacity-money)) into paid from public.profiles where id=p.id;
    update public.profiles set money=money+paid, bottlecaps=bottlecaps+a.reward_caps where id=p.id;
    perform public.kiez_notify(p.id,'erfolg','🎖 Erfolg „'||a.name||'“ freigeschaltet!');
    unlocked := unlocked || jsonb_build_array(jsonb_build_object('name',a.name,'reward',paid,'caps',a.reward_caps));
  end loop;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('unlocked',unlocked,'stats',st,'profile',to_jsonb(p));
end $function$;

create or replace function public.achievement_progress()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  select * into p from public.profiles where id=auth.uid();
  if p.id is null then raise exception 'Spielerprofil fehlt'; end if;
  return public.kiez_stats(p);
end $function$;
