-- 0024: Immer etwas zu tun (ROADMAP 1, 2, 3, 38–44): Computer-Gegner + wöchentlicher Kiezboss, 3 Tagesaufgaben + Wochenbonus,
-- Ereignisse auf der Pfandtour, Mülltonne alle 3 Min., kurze Touren (3/5 Min.), seltene Chancen, Glückssträhne,
-- Blitzaufträge alle 5 Min., Flaschen-Sortierspiel, Übersicht „Als Nächstes“.

-- ---------- Glückssträhne (41): Aktionen im Abstand von höchstens 5 Min. ----------
alter table public.profiles add column if not exists streak integer not null default 0;
alter table public.profiles add column if not exists streak_at timestamptz;

-- Zentrales Aktionsprotokoll für Aufgaben, Blitzaufträge und Strähne
create table if not exists public.kiez_actions(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null, amount integer not null default 1,
  created_at timestamptz not null default now());
create index if not exists kiez_actions_user_time on public.kiez_actions(user_id, created_at desc);
alter table public.kiez_actions enable row level security;
revoke all on public.kiez_actions from anon, authenticated;

-- ---------- 2: Tagesaufgaben ----------
create table if not exists public.daily_tasks(
  user_id uuid not null references public.profiles(id) on delete cascade,
  day date not null, slot integer not null check (slot between 1 and 3),
  kind text not null, target integer not null, progress integer not null default 0, claimed boolean not null default false,
  primary key(user_id, day, slot));
alter table public.daily_tasks enable row level security;
drop policy if exists daily_tasks_own on public.daily_tasks;
create policy daily_tasks_own on public.daily_tasks for select using (user_id = auth.uid());
grant select on public.daily_tasks to authenticated;
alter table public.profiles add column if not exists week_bonus_week date;

create or replace function public.kiez_daily_tasks_ensure(uid uuid)
returns void language plpgsql security definer set search_path to 'public' as $function$
declare pool text[] := array['bottles','beg','bin','npc','crime','wins','sort']; tg int[] := array[60,3,5,2,2,1,1]; picked int[]; i int; k int;
begin
  if exists(select 1 from public.daily_tasks where user_id=uid and day=current_date) then return; end if;
  -- 3 verschiedene Aufgaben, pro Spieler und Tag fest (Zufall mit Tages-Samen)
  select array_agg(x) into picked from (select x from generate_series(1,7) x order by md5(uid::text||current_date::text||x::text) limit 3) s;
  for i in 1..3 loop
    k := picked[i];
    insert into public.daily_tasks(user_id,day,slot,kind,target) values(uid,current_date,i,pool[k],tg[k]) on conflict do nothing;
  end loop;
end $function$;

-- ---------- 42: Blitzaufträge (alle 5 Min. ein neuer) ----------
create table if not exists public.flash_tasks(
  user_id uuid not null references public.profiles(id) on delete cascade,
  slot bigint not null, kind text not null, done_at timestamptz,
  primary key(user_id, slot));
alter table public.flash_tasks enable row level security;
revoke all on public.flash_tasks from anon, authenticated;

create or replace function public.kiez_flash_slot() returns bigint language sql stable as $$ select floor(extract(epoch from now())/300)::bigint $$;
create or replace function public.kiez_flash_kind(uid uuid, slot bigint)
returns text language sql immutable as $$
  select (array['bin','beg','bottles','npc','crime'])[1 + abs(hashtext(uid::text||slot::text)) % 5]
$$;

-- Jede Aktion: Tagesaufgaben, Blitzauftrag, Strähne weiterzählen
create or replace function public.kiez_act(uid uuid, k text, amount integer default 1)
returns void language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; fslot bigint := public.kiez_flash_slot(); st int;
begin
  if uid is null or amount <= 0 then return; end if;
  insert into public.kiez_actions(user_id,kind,amount) values(uid,k,amount);
  perform public.kiez_daily_tasks_ensure(uid);
  update public.daily_tasks set progress=least(target,progress+amount) where user_id=uid and day=current_date and kind=k;
  -- Blitzauftrag: passt die Aktion zum aktuellen Auftrag → erledigt, 1 Kronkorken + 0,50 €
  if public.kiez_flash_kind(uid,fslot)=k and not exists(select 1 from public.flash_tasks f where f.user_id=uid and f.slot=fslot) then
    insert into public.flash_tasks(user_id,slot,kind,done_at) values(uid,fslot,k,now());
    update public.profiles set bottlecaps=bottlecaps+1 where id=uid;
    perform public.kiez_pay(uid,0.50);
  end if;
  -- Glückssträhne: jede 5. Aktion in Folge (Abstand ≤ 5 Min.) bringt 1 Kronkorken
  select * into p from public.profiles where id=uid;
  st := case when p.streak_at > now()-interval '5 minutes' then p.streak+1 else 1 end;
  update public.profiles set streak=st, streak_at=now(), bottlecaps=bottlecaps+case when st % 5 = 0 then 1 else 0 end where id=uid;
end $function$;
revoke execute on function public.kiez_act(uuid,text,integer) from public, anon, authenticated;

-- Bestehende Aktionen anschließen (Trigger auf die vorhandenen Protokolle)
create or replace function public.kiez_act_trigger()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare d int;
begin
  if tg_table_name='daily_missions' then
    d := new.progress;
    if tg_op='UPDATE' then d := d - old.progress; end if;
    if d > 0 then perform public.kiez_act(new.user_id,'bottles',d); end if;
  elsif tg_table_name='beg_log' then perform public.kiez_act(new.user_id,'beg');
  elsif tg_table_name='fights' then perform public.kiez_act(new.winner_id,'wins');
  elsif tg_table_name='side_action_log' and new.action_type like 'crime:%' and new.success then perform public.kiez_act(new.user_id,'crime');
  end if;
  return new;
end $function$;
drop trigger if exists daily_missions_act on public.daily_missions;
create trigger daily_missions_act after insert or update of progress on public.daily_missions for each row execute function public.kiez_act_trigger();
drop trigger if exists beg_log_act on public.beg_log;
create trigger beg_log_act after insert on public.beg_log for each row execute function public.kiez_act_trigger();
drop trigger if exists fights_act on public.fights;
create trigger fights_act after insert on public.fights for each row execute function public.kiez_act_trigger();
drop trigger if exists side_action_act on public.side_action_log;
create trigger side_action_act after insert on public.side_action_log for each row execute function public.kiez_act_trigger();

create or replace function public.daily_tasks_status()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare me uuid := auth.uid(); wk date := public.kiez_week(current_date);
begin
  if me is null then raise exception 'Nicht angemeldet'; end if;
  perform public.kiez_daily_tasks_ensure(me);
  return jsonb_build_object('tasks',(select jsonb_agg(jsonb_build_object('slot',slot,'kind',kind,'target',target,'progress',progress,'claimed',claimed) order by slot)
      from public.daily_tasks where user_id=me and day=current_date),
    'week_done',(select count(*) from public.daily_tasks where user_id=me and day>=wk and claimed),
    'week_bonus_claimed',(select week_bonus_week from public.profiles where id=me)=wk);
end $function$;

create or replace function public.claim_daily_task(task_slot integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; t public.daily_tasks; wk date := public.kiez_week(current_date); n int; bonus boolean := false;
begin
  p := public.kiez_actor();
  select * into t from public.daily_tasks where user_id=p.id and day=current_date and slot=task_slot for update;
  if t.user_id is null then raise exception 'Diese Aufgabe gibt es heute nicht'; end if;
  if t.claimed then raise exception 'Schon abgeholt'; end if;
  if t.progress < t.target then raise exception 'Noch nicht geschafft (% von %)', t.progress, t.target; end if;
  update public.daily_tasks set claimed=true where user_id=p.id and day=current_date and slot=task_slot;
  update public.profiles set bottlecaps=bottlecaps+2, xp=xp+20 where id=p.id;
  perform public.kiez_pay(p.id, 2.00);
  -- Wochenbonus: 15 Tagesaufgaben in einer Woche → 25 Kronkorken
  select count(*) into n from public.daily_tasks where user_id=p.id and day>=wk and claimed;
  if n >= 15 and p.week_bonus_week is distinct from wk then
    update public.profiles set bottlecaps=bottlecaps+25, week_bonus_week=wk where id=p.id; bonus := true;
  end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('caps',2,'xp',20,'money',2,'week_bonus',bonus,'profile',to_jsonb(p));
end $function$;

-- ---------- 38: Mülltonne ----------
alter table public.profiles add column if not exists bin_at timestamptz;
create or replace function public.dig_bin()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r numeric := random(); what text; amt numeric := 0; pl text; pln text;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  if p.bin_at > now()-interval '3 minutes' then raise exception 'Die Tonne ist leer – in % Sek. kommt neuer Müll', ceil(extract(epoch from (p.bin_at+interval '3 minutes'-now()))); end if;
  update public.profiles set bin_at=now(), cleanliness=greatest(0,cleanliness-2) where id=p.id;
  if r < 0.08 then
    what := 'ratte'; update public.profiles set energy=greatest(0,energy-5), cleanliness=greatest(0,cleanliness-5) where id=p.id;
  elsif r < 0.10 then
    what := 'plunder'; pl := public.kiez_random_plunder(); perform public.kiez_give_plunder(p.id,pl); select name into pln from public.plunder_catalog where id=pl;
  elsif r < 0.25 then
    what := 'kronkorken'; amt := 1+floor(random()*2); update public.profiles set bottlecaps=bottlecaps+amt::int where id=p.id;
  elsif r < 0.35 then
    what := 'geld'; amt := round((0.10+random()*0.90)::numeric,2); perform public.kiez_pay(p.id,amt);
  else
    what := 'flaschen'; amt := 1+floor(random()*5); update public.profiles set bottles=bottles+amt::int where id=p.id;
    insert into public.daily_missions(user_id,progress) values(p.id,amt::int)
    on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  end if;
  perform public.kiez_act(p.id,'bin');
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('what',what,'amount',amt,'plunder',pl,'plunder_name',pln,'profile',to_jsonb(p));
end $function$;

-- ---------- 39: kurze Touren ----------
create or replace function public.start_collection(duration_minutes integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  if p.cleanliness<20 then raise exception 'Du bist zu dreckig für die Tour – erst waschen (mindestens 20 Prozent Sauberkeit nötig)'; end if;
  if duration_minutes not in (3,5,10,30,60,240,480) then raise exception 'Ungültige Sammelzeit'; end if;
  if p.collection_ends_at is not null and p.collection_ends_at>now() then raise exception 'Der Einkaufswagen ist noch unterwegs'; end if;
  if p.collection_ends_at is not null then raise exception 'Erst den Einkaufswagen ausladen'; end if;
  if p.collection_ready_at is not null and p.collection_ready_at>now() then raise exception 'Der Einkaufswagen braucht noch Pause'; end if;
  update public.profiles set collection_started_at=now(),collection_ends_at=now()+make_interval(mins=>duration_minutes),collection_minutes=duration_minutes
  where id=p.id returning * into p;
  return to_jsonb(p);
end $function$;

-- ---------- 1: Computer-Gegner in jedem Level-Bereich ----------
create table if not exists public.npc_fights(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  npc text not null, won boolean not null, loot numeric(12,2) not null default 0, xp integer not null default 0,
  created_at timestamptz not null default now());
create index if not exists npc_fights_user on public.npc_fights(user_id, npc, created_at desc);
alter table public.npc_fights enable row level security;
drop policy if exists npc_fights_own on public.npc_fights;
create policy npc_fights_own on public.npc_fights for select using (user_id = auth.uid());
grant select on public.npc_fights to authenticated;

-- Gegner wachsen mit dem Spieler: Stärke = eigene Kampfkraft × Faktor
create or replace function public.kiez_npcs()
returns table(id text, name text, factor numeric, loot_base numeric, xp integer, description text) language sql immutable as $$
  values ('suffkopp','Suff-Kopp Karl',0.70,0.50,4,'Torkelt mehr als er schlägt.'),
         ('pfandneider','Pfandneider Paul',0.90,1.00,6,'Will deine Flaschen – kriegt aber keine.'),
         ('tuersteher','Türsteher Tommy',1.10,2.00,9,'Breit wie ein Container.'),
         ('hafenboxer','Hafenboxer Hanne',1.30,3.50,13,'Hat noch nie verloren. Sagt sie.'),
         ('kiezlegende','Kiezlegende Lutz',1.60,6.00,20,'Nur für ganz Harte.')
$$;

create or replace function public.npc_overview()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; a int; d int;
begin
  select * into p from public.profiles where id=auth.uid();
  if p.id is null then raise exception 'Nicht angemeldet'; end if;
  a := public.kiez_attack_power(p); d := public.kiez_defense_power(p);
  return (select jsonb_agg(jsonb_build_object('id',n.id,'name',n.name,'description',n.description,
      'power',round((a+d)/2.0*n.factor)::int,'loot',round(n.loot_base*(1+p.level*0.05),2),'xp',n.xp,
      'ready_at',(select max(f.created_at)+interval '10 minutes' from public.npc_fights f where f.user_id=p.id and f.npc=n.id having max(f.created_at)>now()-interval '10 minutes'))
    order by n.factor) from public.kiez_npcs() n);
end $function$;

-- Kampf gegen einen Computer-Gegner: 10 Energie, pro Gegner alle 10 Min.
create or replace function public.fight_npc(npc_id text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; n record; mine int; theirs int; won boolean; loot numeric := 0; gx int := 0;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  select * into n from public.kiez_npcs() x where x.id=npc_id;
  if n.id is null then raise exception 'Diesen Gegner gibt es nicht'; end if;
  if exists(select 1 from public.npc_fights where user_id=p.id and npc=npc_id and created_at>now()-interval '10 minutes') then
    raise exception '% hat erst mal genug – in ein paar Minuten wieder', n.name; end if;
  if p.energy < 10 then raise exception 'Du brauchst 10 Energie'; end if;
  mine := round((public.kiez_attack_power(p))*(0.75+random()*0.5));
  theirs := round((public.kiez_attack_power(p)+public.kiez_defense_power(p))/2.0*n.factor*(0.75+random()*0.5));
  won := mine >= theirs;
  if won then loot := round((n.loot_base*(1+p.level*0.05)*(0.8+random()*0.4))::numeric,2); gx := n.xp; perform public.kiez_pay(p.id,loot); end if;
  update public.profiles set energy=energy-10, xp=xp+gx, cleanliness=greatest(0,cleanliness-2) where id=p.id returning * into p;
  insert into public.npc_fights(user_id,npc,won,loot,xp) values(p.id,npc_id,won,loot,gx);
  if won then perform public.kiez_act(p.id,'npc'); end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('won',won,'npc',n.name,'mine',mine,'theirs',theirs,'loot',loot,'xp',gx,'profile',to_jsonb(p));
end $function$;

-- ---------- 1: Kiezboss der Woche – alle Spieler gemeinsam ----------
create table if not exists public.world_boss(
  week_start date primary key, name text not null, max_hp integer not null, hp integer not null, defeated_at timestamptz);
create table if not exists public.world_boss_hits(
  week_start date not null, user_id uuid not null references public.profiles(id) on delete cascade,
  damage integer not null default 0, hits integer not null default 0, last_hit_at timestamptz,
  primary key(week_start, user_id));
alter table public.world_boss enable row level security;
alter table public.world_boss_hits enable row level security;
drop policy if exists world_boss_read on public.world_boss;
create policy world_boss_read on public.world_boss for select using (true);
drop policy if exists world_boss_hits_read on public.world_boss_hits;
create policy world_boss_hits_read on public.world_boss_hits for select using (true);
grant select on public.world_boss, public.world_boss_hits to authenticated;

create or replace function public.kiez_world_boss()
returns public.world_boss language plpgsql security definer set search_path to 'public' as $function$
declare b public.world_boss; wk date := public.kiez_week(current_date); n int;
begin
  select * into b from public.world_boss where week_start=wk;
  if b.week_start is not null then return b; end if;
  n := greatest(10, public.kiez_active_players());
  insert into public.world_boss(week_start,name,max_hp,hp) values(wk,(array['Der Abrissbagger','Ordnungsamt-Otto','Der Müllkönig','Security-Sven'])[1+extract(week from wk)::int % 4],400*n,400*n)
  on conflict do nothing;
  select * into b from public.world_boss where week_start=wk;
  return b;
end $function$;

create or replace function public.world_boss_hit()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; b public.world_boss; wk date := public.kiez_week(current_date); dmg int; h public.world_boss_hits; x record;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  b := public.kiez_world_boss();
  select * into b from public.world_boss where week_start=wk for update;
  if b.defeated_at is not null then raise exception 'Der Kiezboss liegt schon am Boden – nächste Woche kommt ein neuer'; end if;
  select * into h from public.world_boss_hits where week_start=wk and user_id=p.id;
  if h.last_hit_at > now()-interval '1 hour' then raise exception 'Du kannst erst in % Min. wieder zuschlagen', ceil(extract(epoch from (h.last_hit_at+interval '1 hour'-now()))/60); end if;
  if p.energy < 10 then raise exception 'Du brauchst 10 Energie'; end if;
  dmg := greatest(1, round(public.kiez_attack_power(p)*(0.8+random()*0.4)))::int;
  update public.profiles set energy=energy-10 where id=p.id;
  insert into public.world_boss_hits(week_start,user_id,damage,hits,last_hit_at) values(wk,p.id,dmg,1,now())
  on conflict (week_start,user_id) do update set damage=world_boss_hits.damage+dmg, hits=world_boss_hits.hits+1, last_hit_at=now();
  update public.world_boss set hp=greatest(0,hp-dmg), defeated_at=case when hp-dmg<=0 then now() end where week_start=wk returning * into b;
  perform public.kiez_act(p.id,'npc');
  if b.defeated_at is not null then
    for x in select user_id, damage from public.world_boss_hits where week_start=wk loop
      update public.profiles set bottlecaps=bottlecaps+15, xp=xp+150 where id=x.user_id;
      perform public.kiez_pay(x.user_id, 5.00);
      perform public.kiez_notify(x.user_id,'boss','Der Kiezboss „'||b.name||'“ ist besiegt! Für dich: 5 €, 15 Kronkorken, 150 Punkte.');
    end loop;
  end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('damage',dmg,'hp',b.hp,'max_hp',b.max_hp,'defeated',b.defeated_at is not null,'profile',to_jsonb(p));
end $function$;

create or replace function public.world_boss_status()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare b public.world_boss; wk date := public.kiez_week(current_date);
begin
  if auth.uid() is null then raise exception 'Nicht angemeldet'; end if;
  b := public.kiez_world_boss();
  return jsonb_build_object('name',b.name,'hp',b.hp,'max_hp',b.max_hp,'defeated',b.defeated_at is not null,'week_ends',wk+7,
    'next_hit_at',(select last_hit_at+interval '1 hour' from public.world_boss_hits where week_start=wk and user_id=auth.uid() and last_hit_at>now()-interval '1 hour'),
    'my_damage',coalesce((select damage from public.world_boss_hits where week_start=wk and user_id=auth.uid()),0),
    'top',coalesce((select jsonb_agg(jsonb_build_object('name',public.kiez_name(user_id),'user_id',user_id,'damage',damage) order by damage desc)
      from (select * from public.world_boss_hits where week_start=wk order by damage desc limit 10) t),'[]'::jsonb),
    'fighters',(select count(*) from public.world_boss_hits where week_start=wk));
end $function$;

-- ---------- 3: Ereignisse auf der Pfandtour ----------
create table if not exists public.tour_events(
  user_id uuid not null references public.profiles(id) on delete cascade,
  tour_at timestamptz not null, kind text not null, resolved boolean not null default false, outcome text,
  primary key(user_id, tour_at));
alter table public.tour_events enable row level security;
revoke all on public.tour_events from anon, authenticated;

-- Nach dem Ausladen (collection_ready_at gesetzt) mit 35 % ein Ereignis zur Entscheidung
create or replace function public.tour_event()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; e public.tour_events; k text;
begin
  select * into p from public.profiles where id=auth.uid();
  if p.id is null then raise exception 'Nicht angemeldet'; end if;
  if p.collection_ready_at is null or p.collection_ready_at < now()-interval '10 minutes' then return null; end if;
  select * into e from public.tour_events where user_id=p.id and tour_at=p.collection_ready_at;
  if e.user_id is null then
    k := case when random() < 0.35 then (array['hund','polizei','container'])[1+floor(random()*3)::int] else 'keins' end;
    insert into public.tour_events(user_id,tour_at,kind,resolved) values(p.id,p.collection_ready_at,k,k='keins') on conflict do nothing returning * into e;
  end if;
  if e.resolved then return null; end if;
  return jsonb_build_object('kind',e.kind,
    'text',case e.kind when 'hund' then 'Ein bissiger Hund bewacht einen Container voller Flaschen.' when 'polizei' then 'Eine Streife hält an und mustert deinen Einkaufswagen.' else 'Ein Container quillt über vor Pfand – aber es stinkt bestialisch.' end,
    'options',case e.kind when 'hund' then jsonb_build_array('Wurst geben (0,50 €)','Weggehen','Es drauf ankommen lassen')
                          when 'polizei' then jsonb_build_array('Freundlich grüßen','Wegrennen','Pfandbon zeigen')
                          else jsonb_build_array('Reinklettern','Nur oben rausgreifen','Liegen lassen') end);
end $function$;

create or replace function public.resolve_tour_event(choice integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; e public.tour_events; msg text; b int := 0;
begin
  p := public.kiez_actor();
  select * into e from public.tour_events where user_id=p.id and tour_at=p.collection_ready_at and not resolved for update;
  if e.user_id is null then raise exception 'Kein offenes Ereignis'; end if;
  if choice not between 1 and 3 then raise exception 'Ungültige Wahl'; end if;
  if e.kind='hund' then
    if choice=1 then
      if p.money < 0.50 then raise exception 'Dafür reicht deine Kohle nicht'; end if;
      update public.profiles set money=money-0.50 where id=p.id; b := 15; msg := 'Der Hund frisst, du räumst den Container leer: +15 Flaschen.';
    elsif choice=2 then msg := 'Du gehst lieber. Nichts passiert.';
    elsif random() < 0.5 then b := 25; msg := 'Der Hund pennt – du holst dir 25 Flaschen!';
    else update public.profiles set energy=greatest(0,energy-5), cleanliness=greatest(0,cleanliness-10) where id=p.id; msg := 'Autsch, gebissen! −5 Energie, −10 % Sauberkeit.'; end if;
  elsif e.kind='polizei' then
    if choice=1 then update public.profiles set xp=xp+3 where id=p.id; msg := 'Die Beamten nicken dir zu. +3 Punkte für gutes Benehmen.';
    elsif choice=2 then
      if random() < 0.6 then msg := 'Du bist schneller – weg bist du.';
      else update public.profiles set money=greatest(0,money-2) where id=p.id; msg := 'Erwischt: 2 € Verwarngeld.'; end if;
    else update public.profiles set xp=xp+5 where id=p.id; msg := 'Du zeigst den Pfandbon – alles in Ordnung. +5 Punkte.'; end if;
  else
    if choice=1 then b := 30; update public.profiles set cleanliness=greatest(0,cleanliness-15) where id=p.id; msg := 'Bis zur Hüfte im Müll: +30 Flaschen, −15 % Sauberkeit.';
    elsif choice=2 then b := 10; msg := 'Ein paar Flaschen von oben: +10.';
    else msg := 'Zu eklig. Du lässt es liegen.'; end if;
  end if;
  if b > 0 then
    update public.profiles set bottles=bottles+b where id=p.id;
    insert into public.daily_missions(user_id,progress) values(p.id,b) on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  end if;
  update public.tour_events set resolved=true, outcome=msg where user_id=p.id and tour_at=e.tour_at;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('message',msg,'bottles',b,'profile',to_jsonb(p));
end $function$;

-- ---------- 40: seltene Chancen („Tourist verliert 2 €“) ----------
create table if not exists public.chances(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null, text text not null,
  created_at timestamptz not null default now(), expires_at timestamptz not null, claimed boolean not null default false);
create index if not exists chances_user on public.chances(user_id, created_at desc);
alter table public.chances enable row level security;
revoke all on public.chances from anon, authenticated;

-- Der Client fragt höchstens alle 2 Min.; Server entscheidet selten (8 %), höchstens 3 am Tag
create or replace function public.chance_poll()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare me uuid := auth.uid(); c public.chances; t text[] := array['Ein Tourist verliert 2 € – schnell aufheben!','Aus einem Automaten fällt Wechselgeld!','Ein Betrunkener lässt Kleingeld fallen!'];
begin
  if me is null then raise exception 'Nicht angemeldet'; end if;
  select * into c from public.chances where user_id=me and not claimed and expires_at>now() order by id desc limit 1;
  if c.id is not null then return jsonb_build_object('id',c.id,'text',c.text,'amount',c.amount,'expires_at',c.expires_at); end if;
  if exists(select 1 from public.chances where user_id=me and created_at>now()-interval '2 minutes') then return null; end if;
  if (select count(*) from public.chances where user_id=me and created_at>current_date) >= 3 then return null; end if;
  if random() >= 0.08 then
    insert into public.chances(user_id,amount,text,expires_at,claimed) values(me,0,'',now(),true); return null; end if;
  insert into public.chances(user_id,amount,text,expires_at) values(me,round((1+random()*2)::numeric,2),t[1+floor(random()*3)::int],now()+interval '15 seconds') returning * into c;
  return jsonb_build_object('id',c.id,'text',c.text,'amount',c.amount,'expires_at',c.expires_at);
end $function$;

create or replace function public.chance_claim(chance bigint)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; c public.chances;
begin
  p := public.kiez_actor();
  select * into c from public.chances where id=chance and user_id=p.id for update;
  if c.id is null or c.claimed then raise exception 'Zu spät – jemand anderes war schneller'; end if;
  if c.expires_at < now() then update public.chances set claimed=true where id=c.id; raise exception 'Zu spät – das Geld ist weg'; end if;
  update public.chances set claimed=true where id=c.id;
  perform public.kiez_pay(p.id, c.amount);
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('amount',c.amount,'profile',to_jsonb(p));
end $function$;

-- ---------- 43: Flaschen-Sortierspiel (30 Sek.) ----------
create table if not exists public.sort_games(
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  items text not null, started_at timestamptz not null default now(), finished boolean not null default false, score integer);
alter table public.sort_games enable row level security;
revoke all on public.sort_games from anon, authenticated;

-- 20 Gegenstände: g = Glas, p = Plastik, d = Dose. Alle 20 Min. einmal.
create or replace function public.sort_game_start()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; seq text := ''; i int; g public.sort_games;
begin
  p := public.kiez_actor();
  if exists(select 1 from public.sort_games where user_id=p.id and started_at>now()-interval '20 minutes') then
    raise exception 'Die Sortieranlage ist noch belegt – in % Min. wieder', ceil(extract(epoch from ((select max(started_at) from public.sort_games where user_id=p.id)+interval '20 minutes'-now()))/60); end if;
  for i in 1..20 loop seq := seq || (array['g','p','d'])[1+floor(random()*3)::int]; end loop;
  insert into public.sort_games(user_id,items) values(p.id,seq) returning * into g;
  return jsonb_build_object('id',g.id,'items',seq,'seconds',30);
end $function$;

create or replace function public.sort_game_finish(game bigint, answers text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; g public.sort_games; right_ int := 0; i int; b int;
begin
  p := public.kiez_actor();
  select * into g from public.sort_games where id=game and user_id=p.id for update;
  if g.id is null or g.finished then raise exception 'Dieses Spiel ist schon vorbei'; end if;
  update public.sort_games set finished=true where id=g.id;
  if now() > g.started_at + interval '35 seconds' then raise exception 'Zeit abgelaufen – das zählt nicht'; end if;
  for i in 1..least(20,char_length(coalesce(answers,''))) loop
    if substr(answers,i,1) = substr(g.items,i,1) then right_ := right_+1; end if;
  end loop;
  b := right_;  -- jede richtig sortierte Flasche = 1 Pfandflasche
  update public.sort_games set score=right_ where id=g.id;
  if b > 0 then
    update public.profiles set bottles=bottles+b where id=p.id;
    insert into public.daily_missions(user_id,progress) values(p.id,b) on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  end if;
  perform public.kiez_act(p.id,'sort');
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('right',right_,'bottles',b,'profile',to_jsonb(p));
end $function$;

-- ---------- 44: „Als Nächstes“ – alle Countdowns auf einen Blick ----------
create or replace function public.next_actions()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; fslot bigint := public.kiez_flash_slot();
begin
  select * into p from public.profiles where id=auth.uid();
  if p.id is null then raise exception 'Nicht angemeldet'; end if;
  return jsonb_build_object(
    'now', now(),
    'tour_ends_at', p.collection_ends_at, 'tour_ready_at', p.collection_ready_at,
    'training_ends_at', p.training_ends_at, 'training_type', p.training_type,
    'bin_ready_at', case when p.bin_at > now()-interval '3 minutes' then p.bin_at+interval '3 minutes' end,
    'beg_ready_at', case when p.last_beg_at > now()-interval '40 seconds' then p.last_beg_at+interval '40 seconds' end,
    'sort_ready_at', (select max(started_at)+interval '20 minutes' from public.sort_games where user_id=p.id having max(started_at)>now()-interval '20 minutes'),
    'boss_ready_at', (select last_hit_at+interval '1 hour' from public.world_boss_hits where week_start=public.kiez_week(current_date) and user_id=p.id and last_hit_at>now()-interval '1 hour'),
    'flash', jsonb_build_object('kind', public.kiez_flash_kind(p.id,fslot), 'ends_at', to_timestamp((fslot+1)*300),
       'done', exists(select 1 from public.flash_tasks f where f.user_id=p.id and f.slot=fslot)),
    'streak', case when p.streak_at > now()-interval '5 minutes' then p.streak else 0 end,
    'streak_until', case when p.streak_at > now()-interval '5 minutes' then p.streak_at+interval '5 minutes' end,
    'tasks_open', (select count(*) from public.daily_tasks where user_id=p.id and day=current_date and not claimed and progress>=target),
    'energy', p.energy);
end $function$;
create or replace function public.finish_collection()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; found_count int; factor numeric; efficiency numeric; alcohol_factor numeric := 1.0;
  weather jsonb := public.kiez_weather(current_date); weather_factor numeric; plunder_factor numeric := 1.0;
  gained_xp int; found_nails int; found_wood int; found_shards int; found_textile int; caps int; pl text; pl_name text;
begin
  select * into p from public.profiles where id=auth.uid() for update;
  if p.id is null or p.is_banned then raise exception 'Zugriff gesperrt'; end if;
  if p.collection_ends_at is null then raise exception 'Keine Pfandtour aktiv'; end if;
  if p.collection_ends_at>now() then raise exception 'Der Einkaufswagen ist noch unterwegs'; end if;
  factor := (array[1.0,1.25,1.55,1.95,2.5])[least(p.area_level,5)];
  efficiency := case p.collection_minutes when 3 then 1.0 when 5 then 1.0 when 10 then 1.0 when 30 then 0.88 when 60 then 0.78 when 240 then 0.62 when 480 then 0.52 else 0.50 end;
  if p.alcohol_level >= 5 then alcohol_factor := 0.6; else alcohol_factor := 1 + least(p.alcohol_level,4.99)*0.15; end if;
  weather_factor := 1 + ((weather->>'bonus')::numeric + public.kiez_event_bonus('bottles'))/100;
  plunder_factor := 1 + (public.kiez_plunder_bonus(p)->>'bottle')::int/100.0;  -- angelegter Plunder + fertige Sets
  found_count := greatest(1,floor((p.collection_minutes/10.0)*(5+p.streetwise*0.8+(p.bag_level-1)*2)*factor*efficiency*alcohol_factor
                  *weather_factor*plunder_factor*(0.85+random()*0.30))::int);
  gained_xp := round(greatest(case when p.collection_minutes<10 then 2 else 5 end,floor(p.collection_minutes/10.0)::int*2) * (1 + public.kiez_event_bonus('xp')/100.0))::int;
  found_nails := (random()<least(0.35,0.10+p.collection_minutes/480.0*0.20))::int;
  found_wood := (random()<least(0.32,0.09+p.collection_minutes/480.0*0.18))::int;
  found_shards := (random()<least(0.10,0.02+p.collection_minutes/480.0*0.06))::int;
  found_textile := (random()<least(0.28,0.08+p.collection_minutes/480.0*0.16))::int;
  caps := floor(random()*(1+p.collection_minutes/60.0))::int;
  if random() < least(0.45, 0.04+p.collection_minutes/480.0*0.36)*least(1.0,p.collection_minutes/10.0) then
    pl := public.kiez_random_plunder();
    perform public.kiez_give_plunder(p.id, pl);
    select name into pl_name from public.plunder_catalog where id=pl;
  end if;
  update public.profiles set bottles=bottles+found_count, mat_nails=mat_nails+found_nails, mat_wood=mat_wood+found_wood,
    mat_shards=mat_shards+found_shards, mat_textile=mat_textile+found_textile, bottlecaps=bottlecaps+caps,
    cleanliness=greatest(0,cleanliness-least(80,p.collection_minutes/10)), xp=xp+gained_xp,
    collection_started_at=null, collection_ends_at=null, collection_minutes=null, collection_ready_at=now()+interval '30 seconds'
  where id=p.id returning * into p;
  insert into public.daily_missions(user_id,progress) values(p.id,found_count)
  on conflict(user_id,mission_day) do update set progress=daily_missions.progress+excluded.progress;
  return jsonb_build_object('found',found_count,'xp',gained_xp,'alcohol_bonus',alcohol_factor,'weather',weather,
    'nails',found_nails,'wood',found_wood,'shards',found_shards,'textile',found_textile,'bottlecaps',caps,
    'plunder',pl,'plunder_name',pl_name,'profile',to_jsonb(p));
end $function$;
