-- 0027: Charakter, Sozial, Welt (ROADMAP 23, 26–34): Kosmetik, Ruf bei Kiez-Gruppen, Mentoren, Geschenke, Glücksrad,
-- Duo-Pfandtour, Tag und Nacht, Live-Stadtereignisse, Viertel-Ereignisse, Nebenquests von Kiez-Figuren.

-- ---------- 31: Tag und Nacht ----------
create or replace function public.kiez_daytime()
returns text language sql stable as $$
  select case when extract(hour from now() at time zone 'Europe/Berlin') >= 22 or extract(hour from now() at time zone 'Europe/Berlin') < 6 then 'nacht' else 'tag' end
$$;

-- ---------- 26: Ruf ----------
alter table public.profiles add column if not exists rep_police integer not null default 0 check (rep_police between -100 and 100);
alter table public.profiles add column if not exists rep_underworld integer not null default 0 check (rep_underworld between -100 and 100);
alter table public.profiles add column if not exists rep_neighbors integer not null default 0 check (rep_neighbors between -100 and 100);
create or replace function public.kiez_rep(uid uuid, pol int, und int, nb int)
returns void language sql security definer set search_path to 'public' as $$
  update public.profiles set rep_police=greatest(-100,least(100,rep_police+pol)), rep_underworld=greatest(-100,least(100,rep_underworld+und)),
    rep_neighbors=greatest(-100,least(100,rep_neighbors+nb)) where id=uid
$$;
revoke execute on function public.kiez_rep(uuid,int,int,int) from public, anon, authenticated;
-- Ruf folgt den Taten: Verbrechen/Siege → Unterwelt, Schnorren/Mülltonne/Jobs → Nachbarn, gutes Benehmen (Jobs, Tagesaufgaben) → Polizei
create or replace function public.kiez_rep_trigger()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  case new.kind
    when 'crime' then perform public.kiez_rep(new.user_id,-2,2,-1);
    when 'wins' then perform public.kiez_rep(new.user_id,0,1,0);
    when 'npc' then perform public.kiez_rep(new.user_id,0,1,0);
    when 'beg' then perform public.kiez_rep(new.user_id,0,0,1);
    when 'bin' then perform public.kiez_rep(new.user_id,0,0,1);
    when 'job' then perform public.kiez_rep(new.user_id,1,0,1);
    else null;
  end case;
  return new;
end $function$;
drop trigger if exists kiez_actions_rep on public.kiez_actions;
create trigger kiez_actions_rep after insert on public.kiez_actions for each row execute function public.kiez_rep_trigger();

create or replace function public.reputation_status()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object('police',rep_police,'underworld',rep_underworld,'neighbors',rep_neighbors,
    'unlocks',jsonb_build_array(
      jsonb_build_object('group','Polizei','need',30,'have',rep_police>=30,'text','Razzien treffen dich nicht mehr'),
      jsonb_build_object('group','Unterwelt','need',50,'have',rep_underworld>=50,'text','Verbrechen bringen 10 % mehr'),
      jsonb_build_object('group','Unterwelt','need',30,'have',rep_underworld>=30,'text','Kredithai leiht doppelt so viel'),
      jsonb_build_object('group','Nachbarn','need',30,'have',rep_neighbors>=30,'text','Schnorren bringt 10 % mehr')))
  from public.profiles where id=auth.uid()
$$;

-- Kredithai: Unterwelt-Ruf ab 30 verdoppelt den Rahmen
create or replace function public.loan_take(amount numeric)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; amt numeric(12,2) := round(coalesce(amount,0),2); maxl numeric;
begin
  p := public.kiez_actor();
  if exists(select 1 from public.loans where user_id=p.id) then raise exception 'Erst den alten Kredit zurückzahlen'; end if;
  maxl := 20*p.level*case when p.rep_underworld>=30 then 2 else 1 end;
  if amt < 5 or amt > maxl then raise exception 'Kredit zwischen 5 € und % €', maxl; end if;
  insert into public.loans(user_id,amount,owed,due_at) values(p.id,amt,round(amt*1.20,2),now()+interval '3 days');
  perform public.kiez_pay(p.id, amt);
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('amount',amt,'owed',round(amt*1.20,2),'due_at',now()+interval '3 days','profile',to_jsonb(p));
end $function$;
create or replace function public.loan_status()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object('loan',(select to_jsonb(l) from public.loans l where l.user_id=auth.uid()),
    'max',(select 20*level*case when rep_underworld>=30 then 2 else 1 end from public.profiles where id=auth.uid()))
$$;

-- ---------- 32/33: Live-Stadtereignisse und Viertel-Ereignisse ----------
create table if not exists public.city_events(
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('bottles','beg','xp','razzia')), bonus integer not null default 0,
  district text, title text not null, body text not null,
  starts_at timestamptz not null default now(), ends_at timestamptz not null);
create index if not exists city_events_time on public.city_events(ends_at desc);
alter table public.city_events enable row level security;
drop policy if exists city_events_read on public.city_events;
create policy city_events_read on public.city_events for select using (true);
grant select on public.city_events to authenticated, anon;

-- Alle 3 Std. ein neues einstündiges Ereignis (lazy beim Abfragen)
create or replace function public.kiez_city_event_ensure()
returns void language plpgsql security definer set search_path to 'public' as $function$
declare k int; d text;
begin
  if exists(select 1 from public.city_events where starts_at > now()-interval '3 hours') then return; end if;
  k := floor(random()*5)::int;
  select id into d from public.districts order by random() limit 1;
  insert into public.city_events(kind,bonus,district,title,body,ends_at) values
   (case k when 0 then 'bottles' when 1 then 'beg' when 2 then 'xp' when 3 then 'bottles' else 'razzia' end,
    case k when 0 then 100 when 1 then 30 when 2 then 25 when 3 then 30 else 0 end,
    case when k=4 then d end,
    case k when 0 then 'Konzert im Stadtpark' when 1 then 'Weihnachtsmarkt-Stimmung' when 2 then 'Kiez-Fest' when 3 then 'Flohmarkt am Hafen' else 'Razzia im Viertel' end,
    case k when 0 then 'Eine Stunde lang: doppelt so viel Pfand auf allen Touren.' when 1 then 'Die Leute sind großzügig: Schnorren +30 %.'
           when 2 then 'Alle feiern: +25 % Punkte auf Pfandtouren.' when 3 then 'Überall leere Flaschen: Pfand +30 %.'
           else 'Die Polizei durchkämmt '||coalesce((select name from public.districts where id=d),'ein Viertel')||': Verbrechen dort deutlich riskanter.' end,
    now()+interval '1 hour');
end $function$;
revoke execute on function public.kiez_city_event_ensure() from public, anon, authenticated;

create or replace function public.kiez_city_bonus(k text)
returns integer language sql stable security definer set search_path to 'public' as $$
  select coalesce(sum(bonus),0)::int from public.city_events where kind=k and now() between starts_at and ends_at
$$;
create or replace function public.kiez_district_event(p public.profiles, k text)
returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.city_events where kind=k and now() between starts_at and ends_at and (district is null or district=p.district))
$$;

create or replace function public.city_events_now()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.kiez_city_event_ensure();
  return jsonb_build_object('daytime',public.kiez_daytime(),'time',public.kiez_time(),
    'events',coalesce((select jsonb_agg(jsonb_build_object('title',title,'body',body,'kind',kind,'bonus',bonus,'ends_at',ends_at) order by ends_at)
      from public.city_events where now() between starts_at and ends_at),'[]'::jsonb),
    'next',(select max(starts_at)+interval '3 hours' from public.city_events));
end $function$;

-- ---------- 30: Duo-Pfandtour mit Freund ----------
alter table public.profiles add column if not exists duo_with uuid references public.profiles(id) on delete set null;
alter table public.profiles add column if not exists duo_until timestamptz;
create table if not exists public.duo_invites(
  from_id uuid not null references public.profiles(id) on delete cascade, to_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(from_id,to_id));
alter table public.duo_invites enable row level security;
revoke all on public.duo_invites from anon, authenticated;
create or replace function public.kiez_friends(a uuid, b uuid) returns boolean language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from public.friendships f where f.status='accepted' and ((f.user_id=a and f.friend_id=b) or (f.user_id=b and f.friend_id=a)))
$$;
create or replace function public.duo_invite(friend uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  if not public.kiez_friends(p.id, friend) then raise exception 'Nur mit Freunden'; end if;
  -- Liegt schon eine Einladung vom Freund vor → Duo startet (3 Stunden)
  if exists(select 1 from public.duo_invites where from_id=friend and to_id=p.id and created_at>now()-interval '1 hour') then
    delete from public.duo_invites where (from_id=friend and to_id=p.id) or (from_id=p.id and to_id=friend);
    update public.profiles set duo_with=case when id=p.id then friend else p.id end, duo_until=now()+interval '3 hours' where id in (p.id, friend);
    perform public.kiez_notify(friend,'duo',p.username||' ist dabei: 3 Stunden zu zweit auf Pfandtour – beide +15 % Flaschen, solange ihr gleichzeitig unterwegs seid.');
    return jsonb_build_object('status','active','until',now()+interval '3 hours');
  end if;
  insert into public.duo_invites(from_id,to_id) values(p.id,friend) on conflict (from_id,to_id) do update set created_at=now();
  perform public.kiez_notify(friend,'duo',p.username||' will mit dir zu zweit auf Pfandtour – unter Freunde einladen, um anzunehmen.');
  return jsonb_build_object('status','invited');
end $function$;

-- Zentraler Bonus fürs Pfand (wird von finish_collection genutzt): Events, Happy Hour, Nacht, Stadtereignis, Duo
create or replace function public.kiez_event_bonus(kind text)
returns integer language sql stable security definer set search_path to 'public' as $$
  select coalesce((select sum(case kind when 'bottles' then bottle_bonus else xp_bonus end) from public.events where now() between starts_at and ends_at),0)::int
       + case when kind='bottles' and public.kiez_time()='happyhour' then 10 else 0 end
       + case when kind='bottles' and public.kiez_daytime()='nacht' then 10 else 0 end
       + public.kiez_city_bonus(case when kind='bottles' then 'bottles' else 'xp' end)
       + case when kind='bottles' and exists(select 1 from public.profiles me join public.profiles pa on pa.id=me.duo_with
             where me.id=auth.uid() and me.duo_until>now() and pa.collection_ends_at is not null and pa.collection_ends_at > now()-interval '30 minutes') then 15 else 0 end
$$;

-- ---------- 23: Kosmetik (für Kronkorken) ----------
create table if not exists public.cosmetics(
  id text primary key, kind text not null check (kind in ('frame','titlecolor')), name text not null, value text not null, price_caps integer not null, sort_order integer not null default 0);
insert into public.cosmetics(id,kind,name,value,price_caps,sort_order) values
 ('frame_holz','frame','Holzrahmen','#8a5a2b',10,1),('frame_blech','frame','Blechrahmen','#9aa3a8',20,2),('frame_messing','frame','Messingrahmen','#d1a94f',40,3),
 ('frame_rost','frame','Rostrahmen','#9b3c1f',40,4),('frame_gold','frame','Goldrahmen','#f0c33c',100,5),
 ('tc_rost','titlecolor','Titel in Rost','#e0795a',15,10),('tc_moos','titlecolor','Titel in Moosgrün','#8fc26a',15,11),('tc_blau','titlecolor','Titel in Kanalblau','#6fb3e0',15,12),('tc_gold','titlecolor','Titel in Gold','#f0c33c',60,13)
on conflict (id) do nothing;
alter table public.cosmetics enable row level security;
drop policy if exists cosmetics_read on public.cosmetics;
create policy cosmetics_read on public.cosmetics for select using (true);
grant select on public.cosmetics to authenticated, anon;
create table if not exists public.user_cosmetics(user_id uuid not null references public.profiles(id) on delete cascade, cosmetic_id text not null references public.cosmetics(id), primary key(user_id,cosmetic_id));
alter table public.user_cosmetics enable row level security;
drop policy if exists user_cosmetics_own on public.user_cosmetics;
create policy user_cosmetics_own on public.user_cosmetics for select using (user_id=auth.uid());
grant select on public.user_cosmetics to authenticated;
alter table public.profiles add column if not exists avatar_frame text references public.cosmetics(id);
alter table public.profiles add column if not exists title_color text references public.cosmetics(id);

create or replace function public.buy_cosmetic(wanted text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; c public.cosmetics;
begin
  p := public.kiez_actor();
  select * into c from public.cosmetics where id=wanted; if c.id is null then raise exception 'Gibt es nicht'; end if;
  if exists(select 1 from public.user_cosmetics where user_id=p.id and cosmetic_id=wanted) then raise exception 'Hast du schon'; end if;
  if p.bottlecaps < c.price_caps then raise exception 'Dafür brauchst du % Kronkorken', c.price_caps; end if;
  update public.profiles set bottlecaps=bottlecaps-c.price_caps where id=p.id;
  insert into public.user_cosmetics(user_id,cosmetic_id) values(p.id,wanted);
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('bought',c.name,'profile',to_jsonb(p));
end $function$;
create or replace function public.use_cosmetic(k text, wanted text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  if wanted is not null and not exists(select 1 from public.user_cosmetics u join public.cosmetics c on c.id=u.cosmetic_id where u.user_id=p.id and u.cosmetic_id=wanted and c.kind=k) then raise exception 'Das hast du nicht'; end if;
  if k='frame' then update public.profiles set avatar_frame=wanted where id=p.id returning * into p;
  elsif k='titlecolor' then update public.profiles set title_color=wanted where id=p.id returning * into p;
  else raise exception 'Unbekannt'; end if;
  return jsonb_build_object('profile',to_jsonb(p));
end $function$;

-- ---------- 27: Mentoren ----------
alter table public.profiles add column if not exists mentor_id uuid references public.profiles(id) on delete set null;
create or replace function public.set_mentor(mentor uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.profiles;
begin
  p := public.kiez_actor();
  if p.mentor_id is not null then raise exception 'Du hast schon einen Mentor'; end if;
  if p.level >= 20 then raise exception 'Mentoren gibt es nur bis Level 20'; end if;
  select * into m from public.profiles where id=mentor and not is_banned;
  if m.id is null or m.id=p.id then raise exception 'Spieler unbekannt'; end if;
  if m.level < 30 then raise exception 'Mentor muss mindestens Level 30 sein'; end if;
  if (select count(*) from public.profiles where mentor_id=m.id and level<20) >= 5 then raise exception 'Dieser Mentor hat schon 5 Schützlinge'; end if;
  update public.profiles set mentor_id=m.id where id=p.id returning * into p;
  perform public.kiez_notify(m.id,'mentor',p.username||' hat dich als Mentor gewählt. Für jeden 5. Level eures Schützlings gibt es für euch beide Belohnungen.');
  return jsonb_build_object('mentor',m.username);
end $function$;
-- Level 5/10/15/20 des Schützlings: beide +5 Kronkorken, Mentor zusätzlich 1 € je Level
create or replace function public.kiez_mentor_trigger()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare l int;
begin
  if new.mentor_id is null or new.level <= old.level then return new; end if;
  for l in select x from generate_series(old.level+1,new.level) x where x % 5 = 0 and x <= 20 loop
    update public.profiles set bottlecaps=bottlecaps+5 where id in (new.id,new.mentor_id);
    perform public.kiez_pay(new.mentor_id, l);
    perform public.kiez_notify(new.mentor_id,'mentor','Dein Schützling '||new.username||' ist Level '||l||': +5 Kronkorken und '||l||' € für dich.');
    perform public.kiez_notify(new.id,'mentor','Level '||l||' mit Mentor geschafft: +5 Kronkorken.');
  end loop;
  return new;
end $function$;
drop trigger if exists profiles_mentor on public.profiles;
-- Level wird per Trigger aus den Punkten gesetzt → „update of level“ feuert nicht; daher auf jede Änderung prüfen
create trigger profiles_mentor after update on public.profiles for each row when (new.level > old.level) execute function public.kiez_mentor_trigger();
-- Gleicher Fehler beim Ticker (0025): Level-Aufstiege erschienen nie
drop trigger if exists profiles_ticker on public.profiles;
create trigger profiles_ticker after update on public.profiles for each row when (new.level > old.level) execute function public.kiez_ticker_trigger();
create or replace function public.mentor_status()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object('mentor',(select jsonb_build_object('id',m.id,'name',m.username,'level',m.level) from public.profiles m where m.id=p.mentor_id),
    'mentees',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'name',x.username,'level',x.level)) from public.profiles x where x.mentor_id=p.id),'[]'::jsonb),
    'can_choose',p.mentor_id is null and p.level<20,'can_mentor',p.level>=30,
    'candidates',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.username,'level',c.level) order by c.level desc) from (select * from public.profiles c where c.level>=30 and not c.is_banned and c.id<>p.id order by c.energy_updated_at desc limit 15) c),'[]'::jsonb))
  from public.profiles p where p.id=auth.uid()
$$;

-- ---------- 28: Geschenke an Freunde ----------
alter table public.profiles add column if not exists gifts_day date;
alter table public.profiles add column if not exists gifts_caps integer not null default 0;
create or replace function public.send_gift(friend uuid, gift_kind text, ref text, qty integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; fname text; have int; what text;
begin
  p := public.kiez_actor();
  if not public.kiez_friends(p.id, friend) then raise exception 'Geschenke nur an Freunde'; end if;
  select username into fname from public.profiles where id=friend;
  if gift_kind='caps' then
    if qty < 1 or qty > 20 then raise exception '1 bis 20 Kronkorken'; end if;
    if (case when p.gifts_day=current_date then p.gifts_caps else 0 end) + qty > 20 then raise exception 'Höchstens 20 Kronkorken pro Tag verschenken'; end if;
    if p.bottlecaps < qty then raise exception 'So viele Kronkorken hast du nicht'; end if;
    update public.profiles set bottlecaps=bottlecaps-qty, gifts_caps=case when gifts_day=current_date then gifts_caps+qty else qty end, gifts_day=current_date where id=p.id;
    update public.profiles set bottlecaps=bottlecaps+qty where id=friend; what := qty||' Kronkorken';
  elsif gift_kind='plunder' then
    select quantity into have from public.user_plunder where user_id=p.id and plunder_id=ref for update;
    if coalesce(have,0) < 1 then raise exception 'Das hast du nicht'; end if;
    if p.equipped_plunder=ref and have<2 then raise exception 'Leg es erst ab'; end if;
    update public.user_plunder set quantity=quantity-1 where user_id=p.id and plunder_id=ref;
    delete from public.user_plunder where user_id=p.id and plunder_id=ref and quantity=0;
    perform public.kiez_give_plunder(friend, ref); what := (select name from public.plunder_catalog where id=ref);
  elsif gift_kind='bier' then
    if p.money < 1 then raise exception 'Ein Bier kostet 1 €'; end if;
    update public.profiles set money=money-1 where id=p.id;
    update public.profiles set energy=least(100,energy+10) where id=friend; what := 'ein Bier (+10 Energie)';
  else raise exception 'Unbekanntes Geschenk'; end if;
  perform public.kiez_notify(friend,'geschenk',p.username||' hat dir etwas geschenkt: '||what||'.');
  perform public.kiez_rep(p.id,0,0,1);
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('gift',what,'to',fname,'profile',to_jsonb(p));
end $function$;

-- ---------- 29: Glücksrad (1 Dreh am Tag) ----------
alter table public.profiles add column if not exists wheel_day date;
create or replace function public.spin_wheel()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r numeric := random()*100; slot int; label text; pl text;
begin
  p := public.kiez_actor();
  if p.wheel_day = current_date then raise exception 'Heute schon gedreht – morgen wieder'; end if;
  update public.profiles set wheel_day=current_date where id=p.id;
  if r < 20 then slot := 0; label := 'Niete – nur ein leerer Joghurtbecher.';
  elsif r < 40 then slot := 1; perform public.kiez_pay(p.id,0.50); label := '0,50 €';
  elsif r < 55 then slot := 2; perform public.kiez_pay(p.id,1.00); label := '1,00 €';
  elsif r < 70 then slot := 3; update public.profiles set bottlecaps=bottlecaps+2 where id=p.id; label := '2 Kronkorken';
  elsif r < 82 then slot := 4; update public.profiles set energy=least(100,energy+20) where id=p.id; label := '+20 Energie';
  elsif r < 92 then slot := 5; update public.profiles set bottlecaps=bottlecaps+5 where id=p.id; label := '5 Kronkorken';
  elsif r < 98 then slot := 6; pl := public.kiez_random_plunder(); perform public.kiez_give_plunder(p.id,pl); label := 'Plunder: '||(select name from public.plunder_catalog where id=pl);
  else slot := 7; perform public.kiez_pay(p.id,5.00); label := 'Hauptgewinn: 5,00 €!'; end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('slot',slot,'label',label,'profile',to_jsonb(p));
end $function$;

-- ---------- 34: Nebenquests von Kiez-Figuren ----------
create table if not exists public.side_quest_defs(
  quest text not null, step integer not null, figure text not null, title text not null, body text not null,
  kind text not null, target integer not null, reward_money numeric(12,2) not null default 0, reward_caps integer not null default 0, reward_xp integer not null default 0,
  primary key(quest, step));
insert into public.side_quest_defs values
 ('oma','1','Oma Hilde','Die Einkaufstüte','„Junge, hilf mir mal: Sammel 40 Flaschen, dann backe ich dir was.“','bottles',40,1.00,2,15),
 ('oma','2','Oma Hilde','Nicht so stinkig','„Und schnorr nicht so zerzaust – geh 3× schnorren, aber freundlich!“','beg',3,1.50,2,20),
 ('oma','3','Oma Hilde','Kuchen für alle','„Bring mir noch 5 Sachen aus der Mülltonne, für den Flohmarkt.“','bin',5,3.00,5,40),
 ('kemal','1','Kiosk-Kemal','Aushilfe','„Mach mal einen Nebenjob, dann sehen wir weiter.“','job',1,1.00,2,15),
 ('kemal','2','Kiosk-Kemal','Ärger vor der Tür','„Da lungern Typen rum – verprügel 2 Computer-Gegner.“','npc',2,2.50,3,30),
 ('kemal','3','Kiosk-Kemal','Sortierprofi','„Sortier mir zweimal das Leergut.“','sort',2,4.00,5,50),
 ('ratte','1','Ratten-Rudi','Kleiner Gefallen','„Psst… beg mal ein Verbrechen für mich.“','crime',1,2.00,2,20),
 ('ratte','2','Ratten-Rudi','Mehr Mut','„Drei Siege gegen echte Gegner, dann reden wir.“','wins',3,5.00,4,50),
 ('ratte','3','Ratten-Rudi','Der große Coup','„Noch drei Dinger drehen – dann bist du einer von uns.“','crime',3,10.00,8,80)
on conflict do nothing;
alter table public.side_quest_defs enable row level security;
drop policy if exists side_quest_defs_read on public.side_quest_defs;
create policy side_quest_defs_read on public.side_quest_defs for select using (true);
grant select on public.side_quest_defs to authenticated;
create table if not exists public.side_quests(
  user_id uuid not null references public.profiles(id) on delete cascade, quest text not null,
  step integer not null default 1, started_at timestamptz not null default now(), done boolean not null default false,
  primary key(user_id, quest));
alter table public.side_quests enable row level security;
drop policy if exists side_quests_own on public.side_quests;
create policy side_quests_own on public.side_quests for select using (user_id=auth.uid());
grant select on public.side_quests to authenticated;

create or replace function public.side_quests_status()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'Nicht angemeldet'; end if;
  insert into public.side_quests(user_id,quest) select me, q from (values ('oma'),('kemal'),('ratte')) v(q) on conflict do nothing;
  return (select jsonb_agg(jsonb_build_object('quest',s.quest,'figure',d.figure,'step',s.step,'steps',(select max(step) from public.side_quest_defs x where x.quest=s.quest),
      'done',s.done,'title',d.title,'body',d.body,'kind',d.kind,'target',d.target,
      'progress',least(d.target,(select coalesce(sum(a.amount),0) from public.kiez_actions a where a.user_id=me and a.kind=d.kind and a.created_at>=s.started_at)),
      'reward_money',d.reward_money,'reward_caps',d.reward_caps,'reward_xp',d.reward_xp) order by s.quest)
    from public.side_quests s left join public.side_quest_defs d on d.quest=s.quest and d.step=s.step where s.user_id=me);
end $function$;

create or replace function public.claim_side_quest(q text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; s public.side_quests; d public.side_quest_defs; prog int; last_ int;
begin
  p := public.kiez_actor();
  select * into s from public.side_quests where user_id=p.id and quest=q for update;
  if s.user_id is null or s.done then raise exception 'Nichts abzuholen'; end if;
  select * into d from public.side_quest_defs where quest=q and step=s.step;
  select coalesce(sum(amount),0) into prog from public.kiez_actions where user_id=p.id and kind=d.kind and created_at>=s.started_at;
  if prog < d.target then raise exception 'Noch nicht geschafft (% von %)', prog, d.target; end if;
  select max(step) into last_ from public.side_quest_defs where quest=q;
  update public.side_quests set step=least(step+1,last_), started_at=now(), done=(step>=last_) where user_id=p.id and quest=q;
  update public.profiles set bottlecaps=bottlecaps+d.reward_caps, xp=xp+d.reward_xp where id=p.id;
  perform public.kiez_pay(p.id, d.reward_money);
  if q='ratte' then perform public.kiez_rep(p.id,-3,5,0); elsif q='oma' then perform public.kiez_rep(p.id,2,0,5); else perform public.kiez_rep(p.id,2,1,2); end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('figure',d.figure,'money',d.reward_money,'caps',d.reward_caps,'xp',d.reward_xp,'finished',s.step>=last_,'profile',to_jsonb(p));
end $function$;
create or replace function public.commit_crime(crime_id integer)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare
  p public.profiles;
  names text[]:=array['Handtaschenraub','Ladendiebstahl','Auto aufbrechen','Einbruch','Tankstellenüberfall','Bankraub','Kaugummiautomat aufbrechen'];
  risks int[]:=array[15,22,30,42,55,70,18];
  rewardmin numeric[]:=array[8,18,45,90,180,450,10];
  rewardmax numeric[]:=array[18,35,80,160,320,900,20];
  bails numeric[]:=array[8,18,35,70,150,400,10];
  jailmins int[]:=array[8,12,20,35,60,120,9];
  cost int[]:=array[6,8,10,14,18,22,7];
  idx int; caught boolean; reward numeric;
begin
  p := public.kiez_actor();
  perform public.kiez_assert_free(p);
  idx:=crime_id;
  if idx is null or idx<1 or idx>array_length(names,1) then raise exception 'Unbekanntes Verbrechen'; end if;
  if p.energy<cost[idx] then raise exception 'Dafür reicht deine Energie nicht'; end if;
  -- Razzia (22:00–22:30 Uhr): Polizei überall, Risiko +20 Punkte
  -- Razzia (22:00–22:30) +20, Razzia im eigenen Viertel +15, nachts +5; guter Ruf bei der Polizei schützt vor Razzien
  caught:=random()*100<risks[idx]
    + case when public.kiez_time()='razzia' and p.rep_police<30 then 20 else 0 end
    + case when public.kiez_district_event(p,'razzia') and p.rep_police<30 then 15 else 0 end
    + case when public.kiez_daytime()='nacht' then 5 else 0 end;
  if caught then
    update public.profiles set energy=energy-cost[idx],jail_until=now()+make_interval(mins=>jailmins[idx]),jail_bail=bails[idx] where id=p.id returning * into p;
    insert into public.side_action_log(user_id,action_type,success,money_change,xp_change) values(p.id,'crime:'||names[idx],false,0,0);
    return jsonb_build_object('caught',true,'name',names[idx],'bail',bails[idx],'jail_minutes',jailmins[idx],'profile',to_jsonb(p));
  end if;
  reward:=round((rewardmin[idx]+random()::numeric*(rewardmax[idx]-rewardmin[idx])),2);
  -- Nachts +20 %, Unterwelt-Ruf ab 50: +10 %
  reward:=round(reward*(1+case when public.kiez_daytime()='nacht' then 0.2 else 0 end+case when p.rep_underworld>=50 then 0.1 else 0 end),2);
  reward:=least(reward,greatest(0,p.cash_capacity-p.money));
  update public.profiles set energy=energy-cost[idx],money=money+reward,xp=xp+greatest(3,cost[idx]) where id=p.id returning * into p;
  insert into public.side_action_log(user_id,action_type,success,money_change,xp_change) values(p.id,'crime:'||names[idx],true,reward,greatest(3,cost[idx]));
  return jsonb_build_object('caught',false,'name',names[idx],'reward',reward,'profile',to_jsonb(p));
end $function$;

create or replace function public.kiez_beg_factors(p public.profiles)
returns jsonb language plpgsql stable security definer set search_path to 'public' as $function$
declare sym int; f_pet numeric; f_clean numeric; f_speech numeric;
begin
  select coalesce(max(pc.health*up.level),0) into sym from public.user_pets up join public.pet_catalog pc on pc.id=up.pet_id
  where up.user_id=p.id and up.active;
  f_pet := least(3.0, 1 + coalesce(sym,0)/200.0);
  f_clean := case public.kiez_clean_tier(p.cleanliness) when 'gepflegt' then 1.2 when 'normal' then 1.0 when 'schmuddelig' then 0.6 else 0.2 end;
  f_speech := 1 + least(p.speech_skill,150)*0.01;
  if public.kiez_time()='mittag' then f_clean := f_clean*1.2; end if;  -- Mittagspause 12–13 Uhr: +20 %
  if public.kiez_daytime()='nacht' then f_clean := f_clean*0.7; end if;            -- nachts gibt kaum einer was
  if p.rep_neighbors>=30 then f_clean := f_clean*1.1; end if;                        -- Nachbarn mögen dich
  f_clean := f_clean*(1+public.kiez_city_bonus('beg')/100.0);
  return jsonb_build_object('sympathy',sym,'pet',round(f_pet,3),'clean',round(f_clean,3),'speech',round(f_speech,3),
    'total',round(f_pet*f_clean*f_speech,3),'tier',public.kiez_clean_tier(p.cleanliness));
end $function$;
revoke execute on function public.kiez_beg_factors(public.profiles) from public, anon, authenticated;
