-- 0030: Fahrzeuge II (ROADMAP 58–62): Wohnmobil als Unterkunft, Fahrer-Jobs (spät), Straßenrennen mit Zuschauerwetten,
-- Autodiebstahl mit Schutz (Lenkradkralle, Garage, Tier im Auto), Banden-Transporter.

alter table public.gangs add column if not exists transporter integer not null default 0 check (transporter between 0 and 3);

-- ---------- 59: Fahrer-Jobs (brauchen Fahrzeug) ----------
drop function if exists public.kiez_jobs();
create or replace function public.kiez_jobs()
returns table(id text, name text, minutes integer, pay numeric, energy integer, min_level integer, description text, vehicle_tier integer) language sql immutable as $$
  values ('flyer','Flyer verteilen',20,1.20,5,1,'Zettel für die Dönerbude an jede Tür.',0),
         ('spuelen','Teller spülen',60,3.50,10,3,'Hinterm Imbiss, heißes Wasser inklusive.',0),
         ('umzug','Umzugshelfer',120,8.00,20,8,'Kisten schleppen, Trinkgeld hoffen.',0),
         ('nachtwache','Nachtwache am Bauzaun',240,15.00,15,15,'Aufpassen, dass keiner den Bagger klaut.',0),
         ('messe','Messehelfer',480,32.00,25,30,'Stände aufbauen, Häppchen abstauben.',0),
         ('kurier','Kurierfahrten',90,14.00,10,40,'Päckchen quer durch die Stadt – mit Mofa oder besser.',4),
         ('umzugsfahrer','Umzugsfahrer',180,32.00,15,55,'Mit dem Kombi Möbel schaukeln.',5),
         ('sperrmuell','Sperrmüll-Tour',240,50.00,20,70,'Transporter voll, Wertstoffhof leer.',6)
$$;

-- ---------- 60: Straßenrennen ----------
create table if not exists public.races(
  id bigint generated by default as identity primary key,
  challenger_id uuid not null references public.profiles(id) on delete cascade, challenger_vehicle text not null,
  opponent_id uuid references public.profiles(id) on delete cascade, opponent_vehicle text,
  stake numeric(12,2) not null, created_at timestamptz not null default now(),
  starts_at timestamptz, resolved boolean not null default false, winner_id uuid, cp integer, op integer);
alter table public.races enable row level security;
drop policy if exists races_read on public.races;
create policy races_read on public.races for select using (true);
grant select on public.races to authenticated;
alter table public.bets drop constraint if exists bets_kind_check;
alter table public.bets add constraint bets_kind_check check (kind in ('war','pet','race'));

create or replace function public.kiez_race_power(uid uuid, vid text)
returns integer language sql stable security definer set search_path to 'public' as $$
  select coalesce((select v.speed*2 + v.bonus + case when (uv.tuning->>'motor')::boolean then 15 else 0 end + case when (uv.tuning->>'reifen')::boolean then 10 else 0 end + uv.condition/5
    from public.vehicles v join public.user_vehicles uv on uv.vehicle_id=v.id and uv.user_id=uid where v.id=vid),0)
$$;
create or replace function public.settle_races()
returns integer language plpgsql security definer set search_path to 'public' as $function$
declare r public.races; a int; b int; w uuid; n int := 0; pool numeric; winpool numeric; bt record; ws text;
begin
  for r in select * from public.races where not resolved and starts_at is not null and starts_at<=now() for update skip locked loop
    a := public.kiez_race_power(r.challenger_id,r.challenger_vehicle) + floor(random()*30)::int;
    b := public.kiez_race_power(r.opponent_id,r.opponent_vehicle) + floor(random()*30)::int;
    w := case when a>=b then r.challenger_id else r.opponent_id end; ws := case when a>=b then 'a' else 'b' end;
    update public.races set resolved=true, winner_id=w, cp=a, op=b where id=r.id;
    perform public.kiez_pay(w, round(r.stake*1.9,2));
    perform public.kiez_notify(r.challenger_id,'rennen',case when w=r.challenger_id then 'Rennen gewonnen! ' else 'Rennen verloren. ' end||a||' zu '||b||'.');
    perform public.kiez_notify(r.opponent_id,'rennen',case when w=r.opponent_id then 'Rennen gewonnen! ' else 'Rennen verloren. ' end||b||' zu '||a||'.');
    select sum(amount), sum(amount) filter (where side=ws) into pool, winpool from public.bets where kind='race' and ref=r.id::text and not settled;
    for bt in select * from public.bets where kind='race' and ref=r.id::text and not settled for update loop
      if coalesce(winpool,0)=0 then update public.bets set settled=true, payout=bt.amount where id=bt.id; perform public.kiez_pay(bt.user_id,bt.amount);
      elsif bt.side=ws then update public.bets set settled=true, payout=round(pool*0.95*bt.amount/winpool,2) where id=bt.id; perform public.kiez_pay(bt.user_id,round(pool*0.95*bt.amount/winpool,2));
      else update public.bets set settled=true, payout=0 where id=bt.id; end if;
    end loop;
    n := n+1;
  end loop;
  -- Offene Herausforderungen nach 24 Std. zurückgeben
  for r in select * from public.races where opponent_id is null and not resolved and created_at<now()-interval '24 hours' for update skip locked loop
    update public.races set resolved=true where id=r.id; perform public.kiez_pay(r.challenger_id, r.stake);
  end loop;
  return n;
end $function$;
revoke execute on function public.settle_races() from public, anon, authenticated;

create or replace function public.race_challenge(stake numeric)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; st numeric(12,2) := round(coalesce(stake,0),2); rid bigint;
begin
  p := public.kiez_actor();
  if coalesce((select sort_order from public.vehicles where id=p.vehicle),0) < 4 then raise exception 'Rennen nur mit Motorfahrzeug'; end if;
  if st < 5 or st > 500 then raise exception 'Einsatz 5 bis 500 €'; end if;
  if p.money < st then raise exception 'Dafür reicht deine Kohle nicht'; end if;
  if exists(select 1 from public.races where challenger_id=p.id and not resolved) then raise exception 'Du hast schon ein Rennen offen'; end if;
  update public.profiles set money=money-st where id=p.id;
  insert into public.races(challenger_id,challenger_vehicle,stake) values(p.id,p.vehicle,st) returning id into rid;
  return jsonb_build_object('id',rid);
end $function$;
create or replace function public.race_accept(race bigint)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r public.races;
begin
  p := public.kiez_actor();
  select * into r from public.races where id=race and opponent_id is null and not resolved for update;
  if r.id is null then raise exception 'Das Rennen ist schon vergeben'; end if;
  if r.challenger_id=p.id then raise exception 'Nicht gegen dich selbst'; end if;
  if coalesce((select sort_order from public.vehicles where id=p.vehicle),0) < 4 then raise exception 'Rennen nur mit Motorfahrzeug'; end if;
  if p.money < r.stake then raise exception 'Dafür reicht deine Kohle nicht'; end if;
  update public.profiles set money=money-r.stake where id=p.id;
  update public.races set opponent_id=p.id, opponent_vehicle=p.vehicle, starts_at=now()+interval '10 minutes' where id=r.id;
  perform public.kiez_notify(r.challenger_id,'rennen',p.username||' nimmt dein Rennen an – Start in 10 Minuten, Zuschauer können wetten.');
  return jsonb_build_object('starts_at',now()+interval '10 minutes');
end $function$;
create or replace function public.race_bet(race bigint, bet_side text, amount numeric)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; r public.races; amt numeric(12,2) := round(coalesce(amount,0),2);
begin
  p := public.kiez_actor();
  select * into r from public.races where id=race and not resolved and starts_at>now();
  if r.id is null then raise exception 'Auf dieses Rennen kann man nicht (mehr) wetten'; end if;
  if p.id in (r.challenger_id,r.opponent_id) then raise exception 'Fahrer wetten nicht'; end if;
  if bet_side not in ('a','b') then raise exception 'Ungültige Seite'; end if;
  if amt < 0.5 or amt > 50 then raise exception 'Einsatz 0,50 € bis 50 €'; end if;
  if p.money < amt then raise exception 'Dafür reicht deine Kohle nicht'; end if;
  if exists(select 1 from public.bets where user_id=p.id and kind='race' and ref=race::text) then raise exception 'Du hast schon gewettet'; end if;
  update public.profiles set money=money-amt where id=p.id;
  insert into public.bets(user_id,kind,ref,side,amount) values(p.id,'race',race::text,bet_side,amt);
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('amount',amt,'profile',to_jsonb(p));
end $function$;
create or replace function public.races_overview()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
begin
  perform public.settle_races();
  return coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'challenger',public.kiez_name(r.challenger_id),'challenger_id',r.challenger_id,
      'cv',(select name from public.vehicles where id=r.challenger_vehicle),'opponent',public.kiez_name(r.opponent_id),'ov',(select name from public.vehicles where id=r.opponent_vehicle),
      'stake',r.stake,'starts_at',r.starts_at,'resolved',r.resolved,'winner',public.kiez_name(r.winner_id),'cp',r.cp,'op',r.op,'mine',auth.uid() in (r.challenger_id,r.opponent_id),
      'my_bet',exists(select 1 from public.bets b where b.user_id=auth.uid() and b.kind='race' and b.ref=r.id::text)) order by r.created_at desc)
    from (select * from public.races where not resolved or created_at>now()-interval '1 day' order by created_at desc limit 20) r),'[]'::jsonb);
end $function$;

-- ---------- 61: Autodiebstahl und Schutz ----------
alter table public.user_vehicles add column if not exists kralle boolean not null default false;
alter table public.user_vehicles add column if not exists garage boolean not null default false;
alter table public.user_vehicles add column if not exists stolen_until timestamptz;
create table if not exists public.car_thefts(thief_id uuid not null references public.profiles(id) on delete cascade, owner_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now());
create index if not exists car_thefts_idx on public.car_thefts(thief_id, owner_id, created_at desc);
alter table public.car_thefts enable row level security;
revoke all on public.car_thefts from anon, authenticated;

create or replace function public.buy_car_protection(kind text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; price numeric;
begin
  p := public.kiez_actor();
  if not exists(select 1 from public.user_vehicles where user_id=p.id and vehicle_id=p.vehicle) then raise exception 'Erst ein Fahrzeug fahren'; end if;
  price := case kind when 'kralle' then 15 when 'garage' then 100 end;
  if price is null then raise exception 'Unbekannt'; end if;
  if p.money < price then raise exception 'Dafür reicht deine Kohle nicht (% €)', price; end if;
  update public.profiles set money=money-price where id=p.id;
  if kind='kralle' then update public.user_vehicles set kralle=true where user_id=p.id and vehicle_id=p.vehicle;
  else update public.user_vehicles set garage=true where user_id=p.id and vehicle_id=p.vehicle; end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('kind',kind,'price',price,'profile',to_jsonb(p));
end $function$;

-- Chance 50 % + Taschendiebstahl-Stufe; Kralle −25, Garage −35, Begleiter im Auto −15. Erfolg: Hehler zahlt 10 % des Neupreises,
-- Besitzer muss 12 Std. mit dem Einkaufswagen fahren. Misserfolg: 20 Min. Knast.
create or replace function public.steal_vehicle(target_id uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; o public.profiles; uv public.user_vehicles; v public.vehicles; chance numeric; ok_ boolean; cash numeric := 0;
begin
  p := public.kiez_actor(); perform public.kiez_assert_free(p);
  if target_id=p.id then raise exception 'Nicht das eigene Auto'; end if;
  select * into o from public.profiles where id=target_id;
  select * into v from public.vehicles where id=o.vehicle;
  if v.id is null or v.sort_order < 4 then raise exception 'Da gibt es kein Motorfahrzeug zu klauen'; end if;
  select * into uv from public.user_vehicles where user_id=o.id and vehicle_id=v.id for update;
  if uv.stolen_until > now() then raise exception 'Das Auto ist schon weg'; end if;
  if exists(select 1 from public.car_thefts where thief_id=p.id and owner_id=o.id and created_at>now()-interval '24 hours') then raise exception 'Bei dem hast du es heute schon versucht'; end if;
  if p.energy < 15 then raise exception 'Du brauchst 15 Energie'; end if;
  chance := 50 + least(p.pickpocket_skill,40) - case when uv.kralle then 25 else 0 end - case when uv.garage then 35 else 0 end
            - case when exists(select 1 from public.user_pets where user_id=o.id and active) then 15 else 0 end;
  ok_ := random()*100 < greatest(5,chance);
  insert into public.car_thefts(thief_id,owner_id) values(p.id,o.id);
  update public.profiles set energy=energy-15 where id=p.id;
  if ok_ then
    cash := round(v.price*0.10,2);
    update public.user_vehicles set stolen_until=now()+interval '12 hours', condition=greatest(0,condition-30) where user_id=o.id and vehicle_id=v.id;
    update public.profiles set vehicle='wagen' where id=o.id and collection_ends_at is null;
    perform public.kiez_pay(p.id, cash);
    perform public.kiez_notify(o.id,'diebstahl','Dein '||v.name||' wurde geklaut! 12 Stunden fährst du Einkaufswagen. Schutz: Lenkradkralle, Garage, Begleiter.');
    perform public.kiez_rep(p.id,-3,3,-1);
  else
    update public.profiles set jail_until=now()+interval '20 minutes', jail_bail=15 where id=p.id;
    perform public.kiez_notify(o.id,'diebstahl',p.username||' wollte dein '||v.name||' klauen – erwischt!');
  end if;
  select * into p from public.profiles where id=p.id;
  return jsonb_build_object('stolen',ok_,'chance',greatest(5,chance),'cash',cash,'vehicle',v.name,'profile',to_jsonb(p));
end $function$;

-- Gestohlenes Fahrzeug darf nicht benutzt werden
create or replace function public.use_vehicle(wanted text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles;
begin
  p := public.kiez_actor();
  if p.collection_ends_at is not null then raise exception 'Erst die Tour beenden'; end if;
  if wanted<>'wagen' and not exists(select 1 from public.user_vehicles where user_id=p.id and vehicle_id=wanted) then raise exception 'Das Fahrzeug hast du nicht'; end if;
  if exists(select 1 from public.user_vehicles where user_id=p.id and vehicle_id=wanted and stolen_until>now()) then raise exception 'Das Fahrzeug ist noch geklaut'; end if;
  update public.profiles set vehicle=wanted where id=p.id returning * into p;
  return jsonb_build_object('profile',to_jsonb(p));
end $function$;

create or replace function public.theft_targets()
returns jsonb language sql stable security definer set search_path to 'public' as $$
  select coalesce(jsonb_agg(jsonb_build_object('user_id',o.id,'name',o.username,'level',o.level,'vehicle',v.name,'kralle',uv.kralle,'garage',uv.garage) order by v.sort_order desc),'[]'::jsonb)
  from public.profiles me join public.profiles o on o.id<>me.id and not o.is_banned and o.level between floor(me.level*0.8) and ceil(me.level*1.5)
  join public.vehicles v on v.id=o.vehicle and v.sort_order>=4 join public.user_vehicles uv on uv.user_id=o.id and uv.vehicle_id=v.id
  where me.id=auth.uid() and coalesce(uv.stolen_until,'-infinity')<now()
$$;

-- ---------- 62: Banden-Transporter ----------
create or replace function public.buy_gang_transporter()
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; g public.gangs; price numeric;
begin
  p := public.kiez_actor();
  m := public.kiez_gang_can('build');
  select * into g from public.gangs where id=m.gang_id for update;
  if g.transporter >= 3 then raise exception 'Schon der beste Transporter'; end if;
  if g.level < 3+3*g.transporter then raise exception 'Dafür braucht die Bande Level %', 3+3*g.transporter; end if;
  price := (array[2000,5000,10000])[g.transporter+1];
  if g.balance < price then raise exception 'Zu wenig in der Bandenkasse (% €)', price; end if;
  update public.gangs set balance=balance-price, transporter=transporter+1 where id=g.id returning * into g;
  perform public.kiez_gang_log(g.id,p.id,'room',-price,'hat den Banden-Transporter auf Stufe '||g.transporter||' gebracht');
  return jsonb_build_object('level',g.transporter,'price',price);
end $function$;
create or replace function public.kiez_defense_power(p public.profiles)
returns integer language sql stable security definer set search_path to 'public' as $$
  select p.defense_skill*3
    + (array[1,4,8,17,21,24,28,31,34,42,51,58,64,73,82,89,102,125,147,158])[least(greatest(p.shelter_level,1),20)]
    + coalesce((select sum(s.defense) from public.inventory i join public.shop_items s on s.id=i.item_id where i.user_id=p.id and i.equipped),0)
    + coalesce((select sum(pc.defense*up.defense_level) from public.user_pets up join public.pet_catalog pc on pc.id=up.pet_id where up.user_id=p.id and up.active),0)
    + coalesce((select g.defense_level*2 from public.gang_members gm join public.gangs g on g.id=gm.gang_id where gm.user_id=p.id),0) + public.kiez_zwinger_bonus(p.id)
    + (public.kiez_plunder_bonus(p)->>'defense')::int
    + coalesce((select sum(amount) from public.user_active_defenses where user_id=p.id and (expires_at is null or expires_at>now())),0)
    + public.kiez_stench_defense(p)
    + 3*p.legend
    + case when exists(select 1 from public.user_vehicles where user_id=p.id and vehicle_id='wohnmobil') then 40 else 0 end  -- Wohnmobil als Unterkunft
$$;

create or replace function public.kiez_bottle_theft(p public.profiles)
returns public.profiles language plpgsql security definer set search_path to 'public' as $function$
declare days int; left_ int; lost int; rate numeric := (10-2*p.bottle_storage)/100.0 * case when exists(select 1 from public.user_vehicles where user_id=p.id and vehicle_id='wohnmobil') then 0.5 else 1 end;  -- Wohnmobil: halber Klau
begin
  if p.bottles <= 0 then return p; end if;
  days := floor(extract(epoch from (now()-p.bottles_checked_at))/86400);
  if days < 1 then return p; end if;
  left_ := floor(p.bottles*power(1-rate,days)); lost := greatest(least(days,p.bottles), p.bottles-left_);
  update public.profiles set bottles=greatest(0,bottles-lost) where id=p.id;
  update public.profiles set bottles_checked_at=p.bottles_checked_at+make_interval(days=>days) where id=p.id returning * into p;
  perform public.kiez_notify(p.id,'pfand','Während du weg warst, hat jemand '||lost||' Pfandflaschen aus deinem Lager geklaut. Verkauf regelmäßig oder bau dein Lager aus!');
  return p;
end $function$;

create or replace function public.start_job(job text)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; j record;
begin
  p := public.kiez_actor(); perform public.kiez_assert_free(p);
  select * into j from public.kiez_jobs() x where x.id=job; if j.id is null then raise exception 'Diesen Job gibt es nicht'; end if;
  if p.job_id is not null then raise exception 'Du hast schon einen Job laufen'; end if;
  if p.level < j.min_level then raise exception 'Diesen Job gibt es erst ab Level %', j.min_level; end if;
  if j.vehicle_tier > coalesce((select sort_order from public.vehicles where id=p.vehicle),0) then
    raise exception 'Dafür brauchst du mindestens: %', (select name from public.vehicles where sort_order=j.vehicle_tier); end if;
  if p.energy < j.energy then raise exception 'Du brauchst % Energie', j.energy; end if;
  update public.profiles set energy=energy-j.energy, job_id=j.id, job_ends_at=now()+make_interval(mins=>j.minutes) where id=p.id returning * into p;
  return jsonb_build_object('job',j.name,'ends_at',p.job_ends_at,'profile',to_jsonb(p));
end $function$;

create or replace function public.join_gang_raid(raid bigint)
returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare p public.profiles; m public.gang_members; r public.gang_raids; s text; pw int;
begin
  p := public.kiez_actor();
  m := public.kiez_my_gang('member');
  select * into r from public.gang_raids where id=raid and not resolved and ends_at>now();
  if r.id is null then raise exception 'Dieser Überfall ist schon vorbei'; end if;
  s := case when m.gang_id=r.attacker_gang then 'attack' when m.gang_id=r.defender_gang then 'defense' end;
  if s is null then raise exception 'Das ist nicht der Kampf eurer Bande'; end if;
  if exists(select 1 from public.gang_raid_members where raid_id=r.id and user_id=p.id) then raise exception 'Du bist schon dabei'; end if;
  if p.energy < 10 then raise exception 'Du brauchst 10 Energie'; end if;
  update public.profiles set energy=energy-10 where id=p.id returning * into p;
  pw := case s when 'attack' then public.kiez_attack_power(p) else public.kiez_defense_power(p) end;
  pw := round(pw*(1+0.05*coalesce((select transporter from public.gangs where id=m.gang_id),0)));  -- Banden-Transporter
  insert into public.gang_raid_members(raid_id,user_id,side,power) values(r.id,p.id,s,pw);
  return jsonb_build_object('side',s,'power',pw,'profile',to_jsonb(p));
end $function$;

create or replace function public.kiez_track_district()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
declare pts int; d text; g uuid;
begin
  if not public.kiez_feature_on('districts') then return new; end if;  -- Einfluss-Wertung pausiert
  pts := (new.bottles - case when tg_op='UPDATE' then old.bottles else 0 end)
       + 20*(new.wins - case when tg_op='UPDATE' then old.wins else 0 end);
  pts := round(pts*(1+0.10*coalesce((select g.transporter from public.gang_members m join public.gangs g on g.id=m.gang_id where m.user_id=new.user_id),0)));  -- Banden-Transporter
  if pts > 0 then
    select district into d from public.profiles where id=new.user_id;
    select gang_id into g from public.gang_members where user_id=new.user_id;
    if d is not null and g is not null then
      insert into public.district_influence(district_id,gang_id,week_start,points) values(d,g,new.week_start,pts)
      on conflict (district_id,gang_id,week_start) do update set points=public.district_influence.points+excluded.points;
    end if;
  end if;
  return new;
end $function$;
