-- ROADMAP 154: Alle Beschreibungen im Kiez-Ton – assi, pennermäßig, mit Augenzwinkern (eigene Texte).
-- Nur Texte, keine Werte.

update public.shop_items s set description=v.d from (values
 -- Waffen
 ('toothpick','Zehn Zahnstocher mit Gummiband. Tut weh, wenn der andere mitspielt.'),
 ('bottle','Aus der Limo ist schon lange nix mehr drin – dafür jetzt ne Kante.'),
 ('taped_gloves','Luftballons vom Kindergeburtstag, randvoll. Nass macht auch Eindruck.'),
 ('silvesterknaller','Vom 1. Januar aus dem Rinnstein gerettet. Knallt meistens.'),
 ('spraydose','Eigentlich für Graffiti. Aber wer malt, verliert.'),
 ('gummiknueppel','„Gefunden“. Vor dem Revier. Frag nicht.'),
 ('gullideckel','Zwanzig Kilo Stadtverwaltung. Heben ist schon Training.'),
 ('chain_lock','Das Fahrrad ist weg, das Schloss ist geblieben. Jetzt schwingt es.'),
 ('shopping_cart_ram','Vier Finger, ein Argument. Klirrt beim Winken.'),
 ('heizungsrohr','Aus nem Abrisshaus. War noch warm, als du es mitgenommen hast.'),
 ('hammer','Vom Baumarkt-Grabbeltisch. Jeder Streit sieht aus wie ein Nagel.'),
 ('pfefferspray','Abgelaufen seit 2019. Brennt trotzdem wie Hölle.'),
 ('elektroschocker','Bzzzt. Batterie hält genau drei Streits.'),
 ('feuerloescher','Löscht Brände, Durst und Gegner – in dieser Reihenfolge.'),
 ('street_sign','Keiner weiß, woher. Alle wissen, wem man ausweicht.'),
 ('nagelkeule','Brett, Nägel, schlechte Laune. Selbst gebastelt, stolz drauf.'),
 ('brechstange','Macht Türen, Kisten und Diskussionen auf.'),
 ('baseballschlaeger','Nie ein Spiel gesehen. Kennt trotzdem jeden Homerun.'),
 ('vorschlaghammer','Vom Abrissplatz „geliehen“. Rückgabe unwahrscheinlich.'),
 ('kettensaege_ohne_kette','Brummt nur. Aber wie. Die meisten rennen schon beim Anlassen.'),
 ('stuhlbein_nunchakus','Zwei Stuhlbeine, eine Fahrradkette, drei Kung-Fu-Filme auf VHS.'),
 ('eishockeyschlaeger','Mit Gaffa geflickt. Checkt jeden an die Bande.'),
 ('einkaufswagen_rammbock','Vorne Brett, hinten Anlauf, dazwischen du. Quietscht beim Angriff.'),
 ('laubblaeser_kanone','Schießt Kastanien mit 200 Sachen. Im Herbst unschlagbar.'),
 ('streusalz_schleuder','Aus dem Streugutkasten vom Bezirksamt. Brennt in den Augen, rutscht unter den Füßen.'),
 ('gabelstaplergabel','Eigentlich trägt man die zu zweit. Du bist halt allein.'),
 ('abrissbirne','Bowlingkugel an Kette. Strike – und der Gegner liegt.'),
 ('feuerwehraxt','Hing hinter Glas mit „Im Notfall einschlagen“. Es war ein Notfall.'),
 ('kiezkoenig_zepter','Stahlrohr, Kronkorken-Krone, null Diskussion. Das Ende jeder Nahrungskette.'),
 -- Kleidung & Schutz
 ('jacket','Die Motten waren zuerst da. Hält trotzdem ein, zwei Schellen ab.'),
 ('umbrella','Nur noch die linke Hälfte. Wer rechts steht, hat Pech.'),
 ('cart','Tiefergelegt, mit Wackelrad. Der Einkaufswagen, vor dem die Discounter warnen.'),
 ('traffic_vest','Leuchtet so grell, dass Gegner daneben hauen. Vom Bauzaun mitgenommen.'),
 ('cardboard_armor','Drei Lagen Umzugskarton. Bei Regen: Pappmaché.'),
 ('construction_helmet','Schutzklasse: irgendwo gefunden. Delle von Vorbesitzer inklusive.'),
 ('winter_coat','Hat drei Winter unter der Brücke überlebt. Riecht auch so.'),
 ('flohmarkt_lederjacke','Zwei Euro vom Flohmarkt. Riecht nach Rock ’n’ Roll und Kellerbier.'),
 ('motorradkombi','Motorrad hast du keins. Aber stürzen kannst du jetzt stilvoll.'),
 ('feuerwehrjacke','Übersteht Brand, Regen und Kneipenschlägerei. Die Jungs von der Wache wollen sie nicht zurück.'),
 ('gebrauchte_schutzweste','Ein Loch hat sie schon. Frag nicht, wo das herkommt.'),
 ('bundeswehrparka','Hundert Taschen, in jeder ein Kronkorken und ein altes Brötchen.'),
 ('chemieschutzanzug','Hält Säure, Gestank und schlechte Laune ab. Juckt wie Sau.'),
 ('stichschutzweste','Vom Security-Typen aus der Disko. Er hat sie „verloren“.'),
 ('imkeranzug_verstaerkt','Keine Biene kommt durch. Keine Faust auch nicht.'),
 ('kampfmittelanzug','Wiegt 40 Kilo, man schwitzt wie im Hochsommer – aber nix kommt durch.'),
 ('theaterruestung','Aus dem Fundus vom Stadttheater. Scheppert bei jedem Schritt, aber hält.'),
 ('kiez_panzermantel','Mantel mit eingenähten Blechplatten. Wenn du kommst, geht der Kiez in Deckung.'),
 -- Zubehör
 ('chain_gloves','Stichfest. Perfekt zum Wühlen im Altglas ohne Tetanusspritze.'),
 ('whistle','Einmal pfeifen und Ratten, Ordnungsamt und Konkurrenz sind weg.'),
 ('folding_spade','Gräbt Pfand aus dem Sandkasten und Gegner in den Boden.'),
 ('flashlight','Findet im dunkelsten Hinterhof noch die letzte Flasche. Und dein Gebiss.'),
 ('survival_backpack','Mehr Fächer als ein Behördenformular. Und mehr Platz für Dosen.'),
 ('walkie_talkie','„Kollege, Ordnungsamt an der Ecke!“ – rechtzeitig gewarnt ist halb gewonnen.'),
 ('solar_panel_set','Lädt das Handy und wärmt nachts die Finger. Fast wie Stadtwerke.'),
 ('cart_engine','Rasenmähermotor am Einkaufswagen. Brummt, stinkt, fährt 12 km/h. Endgeil.'),
 ('armored_handcart','Der Rolls-Royce unter den Karren. Mit Blech gegen Neider.'),
 ('lucky_bottle','Taucht immer wieder auf, egal wie oft du sie wegwirfst. Unheimlich. Nützlich.'),
 ('nachtsichtgeraet','Grünes Bild, klare Sache: Flaschen und Feinde im Dunkeln.'),
 ('sperrmuell_drohne','Aus drei kaputten Drohnen zusammengeschraubt. Fliegt schief, sieht aber alles.'),
 ('akku_stirnlampe','Hände frei für Flaschen. Blendet nebenbei jeden Angreifer.'),
 ('waermebildkamera','Zeigt, wer hinter dem Container lauert. Und wer da gerade pinkelt.'),
 ('motor_sackkarre','Schleppt 20 Kisten und rammt zur Not den Konkurrenten.'),
 ('ghettoblaster','Bass so tief, dass dem Gegner die Plomben rausfallen.'),
 ('kiez_funknetz','Drei Funkgeräte, drei Kumpels, ein Plan. Keiner kommt unbemerkt vorbei.'),
 ('stahl_lastenanhaenger','Hält alles aus. Auch einen Gegner, der sich dahinter versteckt.'),
 ('notstromaggregat','Strom für Licht, Handy und Kühlschrank-Bier. Unter der Brücke bist du jetzt Stadtwerk.'),
 ('kiez_alarmanlage','Blinkt, heult, klingelt. Dein Lager ist sicherer als die Sparkasse.'),
 ('kiezkoenig_siegelring','Einmal draufschauen und alle wissen, wer hier der König ist.'),
 -- Basteln
 ('holzschild','Drei Bretter, zwei Nägel, ein Gedanke. Hält überraschend was ab.'),
 ('stachelschild','Holzschild mit Nägeln nach außen. Umarmen verboten.'),
 ('doppeltes_holzschild','Doppelt Holz, doppelt Ruhe. Wiegt wie ein Kühlschrank.'),
 ('glasstachelschild','Scherben im Rand. Wer da reinhaut, blutet und bereut.'),
 ('feiner_anzug','Fast schon respektabel. Bis man die Flecken sieht.'),
 ('ramponierter_anzug','Löchrig wie Käse, aber immerhin ein Anzug. Fürs Amt reicht''s.'),
 ('kaputter_regenschirm','Hält noch die Hälfte vom Regen ab. Und die Hälfte der Schläge.'),
 ('regenschirm','Ganz. Mit allen Speichen. Der pure Luxus.')
) v(id,d) where s.id=v.id;

update public.pet_catalog c set description=v.d from (values
 ('cockroach','Überlebt alles – Atomkrieg, Kammerjäger und deine Kochkünste.'),
 ('goldfish','Dreht im Gurkenglas seine Runden. Vergisst nach drei Sekunden, dass er dich hasst.'),
 ('mouse','Klaut dir die Krümel, schläft in deinem Schuh. Beste Mitbewohnerin.'),
 ('hamster','Stopft sich Kronkorken in die Backen. Sparkonto auf vier Beinen.'),
 ('budgie','Kann „Pfand!“ sagen und „Ordnungsamt!“. Mehr braucht keiner.'),
 ('pigeon','Frisst deine Brötchen, kackt auf deinen Schlafsack. Treu ist sie trotzdem.'),
 ('rat','Kennt jeden Gully der Stadt. Mitleid gibt’s von Passanten dafür null.'),
 ('rabbit','Hoppelt schneller weg als ein Kollege, wenn die Rechnung kommt.'),
 ('ferret','Klaut Feuerzeuge, Schnürsenkel und Herzen. Stinkt ein bisschen, wie du.'),
 ('cat','Herrscht über jeden Hinterhof. Dich duldet sie nur wegen des Dosenfutters.'),
 ('falcon','Sieht von oben jede Pfandflasche im Umkreis von zwei Kilometern.'),
 ('snake','Liegt still im Schlafsack. Keiner klaut mehr was.'),
 ('goat','Frisst Knöllchen, Mahnbescheide und gegnerische Hosen.'),
 ('poodle','Frisur besser als deine. Beißt, wenn einer blöd guckt.'),
 ('trained_mouse','Kann Männchen machen und Hut halten. Passanten schmelzen dahin.'),
 ('eagle','Stürzt sich auf alles, was glänzt – Pfanddosen und Glatzen.'),
 ('shepherd_dog','Ehemals Polizeihund, wegen „Arbeitsverweigerung“ entlassen. Jetzt dein Kumpel.'),
 ('pitbull','Kurz, breit, keine Fragen. Mitleid gibt’s dafür kaum – Respekt umso mehr.'),
 ('cocker_spaniel','Hundeblick der Extraklasse. Bis er zubeißt.'),
 ('chihuahua','Zittert, kläfft, sieht zum Knuddeln aus. Die Leute werfen dir Geld zu.'),
 ('horse','Vom Reiterhof abgehauen. Frisst Heu vom Spielplatz und trägt deine Säcke.'),
 ('giraffe','Sieht über jeden Zaun, wo noch Flaschen stehen. Passt unter keine Brücke.'),
 ('crocodile','Wohnt in der Badewanne vom Obdachlosenheim. Keiner will mehr baden.'),
 ('tiger','Aus einem Privatzoo entlaufen. Seitdem ist der Hinterhof ruhig.'),
 ('monkey','Macht Kunststücke vor der Bäckerei. Die Kasse klingelt, der Bäcker weint.'),
 ('rhino','Zwei Tonnen schlechte Laune. Parkt, wo es will.'),
 ('wolf','Kam eines Nachts aus dem Stadtwald und hat beschlossen: Du gehörst jetzt zum Rudel.'),
 ('bear','Plündert Mülltonnen besser als du. Brummt einmal – dann ist Ruhe im Kiez.'),
 ('lion','Aus dem Wanderzirkus abgehauen. Frisst nur Döner mit alles.'),
 ('gorilla','Stark, klug, nachtragend. Klopft sich auf die Brust, und die Straße ist leer.'),
 ('elephant','Vergisst nie, wer dir krumm kam. Tritt auch nie daneben.')
) v(id,d) where c.id=v.id;

update public.plunder_catalog c set description=v.d from (values
 ('alufolienkrone','Aus Dönerpapier gefaltet. Für den König des Kiez reicht’s.'),
 ('arbeitshandschuhe','Riechen nach Baustelle und ehrlicher Arbeit. Beides kennst du nur vom Hörensagen.'),
 ('bauhelm','Mit Lampe drauf. Endlich siehst du im Container, was du anfasst.'),
 ('dosenpanzer','Zwölf leere Bierdosen am Gürtel. Klingt wie ein Glockenspiel, hält wie ne Rüstung.'),
 ('ein_handschuh','Der andere liegt garantiert irgendwo am Bahnhof. Wie immer.'),
 ('fahrradkette','Das Rad ist lange weg. Die Kette rasselt jetzt für dich.'),
 ('glueckspfandbon','Pfandbon von 1998. Der Automat lacht, du glaubst trotzdem dran.'),
 ('goldene_dose','Die sagenumwobene Ein-Euro-Dose. Andere suchen ihr Leben lang danach.'),
 ('goldkette','Echt vergoldet. Also: echt gelb. Glänzt wie ein Bordstein im Regen.'),
 ('kiezzepter','Besenstiel mit Glitzerkleber. Wer’s trägt, bekommt Respekt – oder Mitleid.'),
 ('kronkorkenkette','Hundert Kronkorken auf Draht. Klimpert bei jedem Schritt wie ein Sparschwein.'),
 ('kuerbislaterne','Grinst gruselig, leuchtet nicht, stinkt nach drei Tagen.'),
 ('lebkuchenherz','„Kiezkönig“ in Zuckerguss. Hart wie ein Pflasterstein – taugt auch als einer.'),
 ('leeres_feuerzeug','Macht keine Flamme, aber das Klicken beruhigt.'),
 ('megafon','Batterie leer. Du schreist einfach selbst rein. Wirkt genauso.'),
 ('plastikblume','Welkt nie, riecht nie, gefällt der Omma am Bahnhof trotzdem.'),
 ('rostiger_schluessel','Passt in kein Schloss der Stadt. Du probierst trotzdem jede Tür.'),
 ('schokohase','Ohr fehlt, Rest ist Weihnachtsschoki vom letzten Jahr. Schmeckt.'),
 ('sonnenbrille','Ein Glas fehlt. Cool bleibt man trotzdem – auf einem Auge.'),
 ('stadtplan','Mit Kuli markiert: alle guten Container. Ein Schatz, fleckig vom Kaffee.'),
 ('taschenlampe','Keine Batterie. Leuchtet, wenn du fest genug dran glaubst.'),
 ('taubenfutter','Die gefiederte Bande folgt dir überall hin. Und findet Flaschen.'),
 ('taubenpfeife','Die Tauben hören auf dich. Also manchmal. Also eigentlich nie.'),
 ('wasserpistole','Für heiße Tage im Park. Oder für den Typen, der dir die Bank geklaut hat.'),
 ('weihnachtsmuetze','Bimmelt bei jedem Schritt. Die Leute geben im Winter doppelt.'),
 ('wunderkerze','Silvester war wild. Du erinnerst dich an nix.')
) v(id,d) where c.id=v.id;

update public.vehicles c set description=v.d from (values
 ('wagen','Quietscht, eiert, zieht nach links. Aber er gehört dir – also fast.'),
 ('bollerwagen','Vom Vatertag übrig geblieben. Passen mehr Kisten rein als Bier.'),
 ('fahrrad','Gelber Anhänger, drei Gänge, zwei davon gehen. Schneller zum nächsten Container.'),
 ('lastenrad','Der Kofferraum der Hipster. Jetzt voller Pfand statt Bio-Gemüse.'),
 ('mofa','Knattert, qualmt, 25 km/h bergab. Braucht Sprit und nen Lappen.'),
 ('kombi','Rost hält zusammen, was der TÜV trennen will. Kofferraum für drei Säcke.'),
 ('transporter','Da passt ein halber Wertstoffhof rein. Und du schläfst hinten drin.'),
 ('wohnmobil','Rollende Villa mit Pfandlager. Du bist jetzt offiziell Camper, nicht Penner.')
) v(id,d) where c.id=v.id;

update public.plunder_sets c set description=v.d from (values
 ('bauarbeiter','Helm, Lampe, Handschuhe – siehst aus wie Nachtschicht, bist aber nur Pfandschicht.'),
 ('kiezadel','Krone, Zepter, Goldkette: Der Kiez verneigt sich. Oder lacht. Hauptsache Aufmerksamkeit.'),
 ('taubenkoenig','Die Tauben folgen dir und finden Flaschen. Die Leute wechseln die Straßenseite.'),
 ('pfandjaeger','Wer diese drei hat, riecht Pfand durch Beton.'),
 ('strassenkaempfer','Rasselt, klimpert, knallt. Keiner legt sich mehr mit dir an.')
) v(id,d) where c.id=v.id;

update public.districts c set description=v.d from (values
 ('bahnhof','Pendler, Pfandautomaten, Taubenkacke. Hier fängt jeder an.'),
 ('altstadt','Kopfsteinpflaster, Kneipen, Touristen mit lockerem Kleingeld und lockeren Flaschen.'),
 ('hafen','Container, Kräne und Seeleute mit Riesendurst. Pfand im Überfluss.'),
 ('stadtpark','Grillpartys am Wochenende. Montagmorgen ist hier Weihnachten.'),
 ('markt','Markttage, Straßenmusik, Omas mit Kleingeld im Portemonnaie.'),
 ('villen','Wenig Flaschen, aber dicke Geldbeutel und ein Sicherheitsdienst, der nervt.')
) v(id,d) where c.id=v.id;

update public.cities c set description=v.d from (values
 ('hafenstadt','Die Stadt, in der alles begann: Bahnhof, Hafen, Villen und Pfand bis zum Abwinken.'),
 ('bergstadt','Steile Gassen, frische Luft, reiche Wandertouristen. Später – erst Kondition aufbauen.'),
 ('flussstadt','Brücken zum Drunterpennen, Flaschen im Schilf. Öffnet, wenn die Hafenstadt voll ist.')
) v(id,d) where c.id=v.id;

update public.achievement_defs c set description=v.d from (values
 ('first_bottles','20 Flaschen gesammelt – der erste Sack ist immer der schwerste.'),
 ('collector','100 Flaschen gesammelt. Die Nachbarn nennen dich jetzt „Baron“.'),
 ('bottles_1000','1.000 Flaschen gesammelt. Du riechst Pfand gegen den Wind.'),
 ('bottles_10000','10.000 Flaschen gesammelt. Die Flaschen reden mit dir.'),
 ('bottles_100000','100.000 Flaschen gesammelt. Die Getränkeindustrie kennt deinen Namen.'),
 ('earned_10000','10.000 € mit Pfand verdient. Das Finanzamt weiß nix davon.'),
 ('rich','100 € auf einmal in der Tasche. Heute gibt’s Dosenbier mit Etikett.'),
 ('rich_1000','1.000 € auf einmal in der Tasche. Pass bloß auf, dass keiner guckt.'),
 ('first_win','Den ersten Kampf gewonnen. Die erste Schelle verteilt.'),
 ('wins_10','10 Kämpfe gewonnen. Im Hinterhof spricht man über dich.'),
 ('wins_100','100 Kämpfe gewonnen. Kollegen wechseln die Straßenseite.'),
 ('wins_1000','1.000 Kämpfe gewonnen. Selbst die Tauben haben Angst.'),
 ('crimes_25','25 Verbrechen erfolgreich. Die Streife kennt dich beim Vornamen.'),
 ('attack_25','Angriff Stufe 25. Deine Fäuste haben Waffenschein-Pflicht.'),
 ('defense_25','Verteidigung Stufe 25. Schläge prallen ab wie am Türsteher.'),
 ('social_20','Sozialkontakte Stufe 20. Du kennst jeden – und jeder schuldet dir was.'),
 ('area_5','Alle Sammelgebiete frei. Kein Container der Stadt ist vor dir sicher.'),
 ('house_10','Unterkunft Stufe 10. Ein eigenes Dach – fast wie ein richtiges Zuhause.'),
 ('house_20','In der Burg eingezogen. Jetzt fehlt nur noch der Graben.'),
 ('level_five','Level 5. Die Oma am Bahnhof grüßt dich schon.'),
 ('veteran','Level 10. Du gehörst zum Inventar vom Kiez.'),
 ('level_25','Level 25. Die ganze Stadt redet über dich – nicht nur Gutes.'),
 ('level_50','Level 50. Kiezfürst. Man verbeugt sich, wenn du vorbeischlurfst.'),
 ('level_100','Level 100. Kiezkönig. Die Krone ist aus Alu, der Respekt echt.'),
 ('music_5','Fünftes Instrument. Du nervst jetzt professionell.'),
 ('pet_owner','Erster Begleiter gekauft. Endlich einer, der dir zuhört.'),
 ('pet_wins_10','10 Tierkämpfe gewonnen. Dein Viech hat mehr Fans als du.'),
 ('plunder_5','5 verschiedene Plunderstücke gefunden. Messie-Anfänger.'),
 ('plunder_all','Jedes Plunderstück gefunden. Deine Platte ist ein Museum.'),
 ('friends_5','5 Freunde gefunden. Mehr als die meisten mit Wohnung.'),
 ('gang_member','Einer Bande beigetreten. Endlich jemand, der dir Rückendeckung gibt.'),
 ('streak_7','7 Tage in Folge eingeloggt. Stammgast – wie in der Eckkneipe.'),
 ('streak_30','30 Tage in Folge eingeloggt. Urgestein. Du hast den Kiez nie verlassen.'),
 ('donations_50','50 Spenden über deinen Link. Deine Tante hat bestimmt 40 davon gegeben.')
) v(id,d) where c.id=v.id;

-- Namen mit richtigen Umlauten
update public.shop_items set name='Funkgerät' where id='walkie_talkie';
update public.pet_catalog set name='Schäferhund' where id='shepherd_dog';
update public.pet_catalog set name='Äffchen' where id='monkey';
